MelanoBot: string::FormatterConfig Class Reference
string::FormatterConfig Class Reference
Custom string formatting (Utf-8)
#include <string.hpp>
Public Member Functions
FormatterConfig ()
std::string ascii (char c) const override
Encode a single ASCII character.
std::string ascii (const std::string &s) const override
Encode a simple ASCII string.
std::string color (const color::Color12 &color) const override
Encode a color code.
std::string format_flags (FormatFlags flags) const override
Encode format flags.
std::string clear () const override
Clear all formatting.
FormattedString decode (const std::string &source) const override
Decode a string.
std::string name () const override
Name of the format.
Public Member Functions inherited from string::FormatterUtf8
std::string unicode (const Unicode &c) const override
Encode a unicode (non-ASCII) character.
std::string qfont (const QFont &c) const override
Encode a Darkpaces weird character.
Public Member Functions inherited from string::Formatter
Formatter ()=default
Formatter (const Formatter &)=delete
Formatter (Formatter &&)=delete
Formatter & operator= (const Formatter &)=delete
Formatter & operator= (Formatter &&)=delete
virtual ~Formatter ()
Additional Inherited Members
Static Public Member Functions inherited from string::Formatter
static Formatter * formatter (const std::string &name)
Get a string formatter from name.
static Registry & registry ()
Get the formatter registry singleton.
Detailed Description
Custom string formatting (Utf-8)
Style formatting:
## #
#-# clear all formatting
#-b# bold
#-u# underline
#1# red
#xf00# red
#red# red
#nocolor# no color
Definition at line 785 of file string.hpp.
Constructor & Destructor Documentation
string::FormatterConfig::FormatterConfig () inline explicit
Definition at line 788 of file string.hpp.
Referenced by handler::Help::on_handle().
Member Function Documentation
std::string string::FormatterConfig::ascii (char c) const override virtual
Encode a single ASCII character.
Reimplemented from string::FormatterUtf8.
Definition at line 473 of file string.cpp.
std::string string::FormatterConfig::ascii (const std::string & s) const override virtual
Encode a simple ASCII string.
Reimplemented from string::FormatterUtf8.
Definition at line 477 of file string.cpp.
std::string string::FormatterConfig::clear () const override virtual
Clear all formatting.
Reimplemented from string::FormatterUtf8.
Definition at line 469 of file string.cpp.
std::string string::FormatterConfig::color (const color::Color12 & color) const override virtual
Encode a color code.
Todo:
Background colors?
Reimplemented from string::FormatterUtf8.
Definition at line 442 of file string.cpp.
FormattedString string::FormatterConfig::decode (const std::string & source) const override virtual
Decode a string.
Reimplemented from string::FormatterUtf8.
Definition at line 481 of file string.cpp.
Referenced by xonotic::XonoticMatchScore::handle_end(), handler::SearchVideoYoutube::json_success(), handler::Help::on_handle(), xonotic::ConnectionEvents::on_handle(), xonotic::XonoticJoinPart::on_handle(), handler::EventMessageBase::on_handle(), xonotic::XonoticMatchStart::on_handle(), xonotic::ShowVoteCall::on_handle(), xonotic::ShowVoteResult::on_handle(), xonotic::ShowVoteStop::on_handle(), xonotic::ShowVoteLogin::on_handle(), and xonotic::ShowVoteDo::on_handle().
std::string string::FormatterConfig::format_flags (FormatFlags flags) const override virtual
Encode format flags.
Reimplemented from string::FormatterUtf8.
Definition at line 460 of file string.cpp.
std::string string::FormatterConfig::name () const override virtual
Name of the format.
Reimplemented from string::FormatterUtf8.
Definition at line 558 of file string.cpp.
The documentation for this class was generated from the following files:
src/string/string.hpp
src/string/string.cpp