MelanoBot: handler::Help Class Reference
handler::Help Class Reference
Handler showing help on the available handlers.
Public Member Functions
Help (const Settings &settings, Melanobot *bot)
Public Member Functions inherited from handler::SimpleAction
SimpleAction (const std::string &default_trigger, const Settings &settings, Melanobot *bot)
Sets up the trigger.
bool can_handle (const network::Message &msg) const override
virtual bool handle (network::Message &msg) override
std::string get_property (const std::string &name) const override
Public Member Functions inherited from handler::Handler
Handler (const Settings &settings, Melanobot *bot)
Handler (const Handler &)=delete
Handler & operator= (const Handler &)=delete
virtual ~Handler ()
virtual void initialize ()
Called at startup in case it needs to perform some initialization.
virtual void finalize ()
Called when the connection ends.
virtual bool authorized (const network::Message &msg) const
Checks if a message is authorized to be executed by this message.
void populate_properties (const std::vector< std::string > &properties, PropertyTree &output) const override
Simply appends globally the given property.
Public Member Functions inherited from handler::HandlerContainer
virtual ~HandlerContainer ()
Protected Member Functions
bool on_handle (network::Message &msg) override
Required for concrete handlers, performs the handler actions.
Protected Member Functions inherited from handler::SimpleAction
void reply_to (const network::Message &msg, const string::FormattedString &text) const override
Send a reply to a message.
Protected Member Functions inherited from handler::Handler
void reply_to (const network::Message &msg, const std::string &text) const
Private Member Functions
bool cleanup (network::Message &msg, PropertyTree &properties) const
Remove items the user can't perform.
boost::optional< PropertyTree > restructure (const PropertyTree &input, PropertyTree *parent) const
removes all internal nodes which don't have a name key
void gather (const PropertyTree &properties, std::vector< std::string > &out) const
Gathers top-level names.
boost::optional< const
PropertyTree & > find (const PropertyTree &tree, const std::string &name) const
Searches for a help item with the given name.
Private Attributes
std::string help_group
Only shows help for members of this group.
Additional Inherited Members
Protected Attributes inherited from handler::SimpleAction
std::string trigger
String identifying the action.
bool direct = false
std::string synopsis
Help synopsis.
std::string help ="Undocumented"
Help string.
bool public_reply = true
Whether to reply publicly or just to the sender of the message.
Protected Attributes inherited from handler::Handler
std::string auth
Authorization group required for a user message to be handled.
int priority = 0
Message priority.
Melanobot * bot = nullptr
Pointer to the main bot.
Detailed Description
Handler showing help on the available handlers.
Note
It is trongly recommended that this is enabled
Todo:
option for inline help (synopsis+message all on the same line)
Definition at line 58 of file misc.cpp.
Constructor & Destructor Documentation
handler::Help::Help (const Settings & settings, Melanobot * bot) inline
Definition at line 61 of file misc.cpp.
Member Function Documentation
bool handler::Help::cleanup (network::Message & msg, PropertyTree & properties) const inline private
Remove items the user can't perform.
Returns
false if propeties shall not be considered
Definition at line 134 of file misc.cpp.
Referenced by cleanup(), and on_handle().
boost::optional<const PropertyTree&> handler::Help::find (const PropertyTree & tree, const std::string & name) const inline private
Searches for a help item with the given name.
Definition at line 198 of file misc.cpp.
Referenced by find(), and on_handle().
void handler::Help::gather (const PropertyTree & properties, std::vector< std::string > & out) const inline private
Gathers top-level names.
Definition at line 184 of file misc.cpp.
Referenced by gather(), and on_handle().
bool handler::Help::on_handle (network::Message & msg) inline override protected virtual
Required for concrete handlers, performs the handler actions.
Returns
true if the message has been handled and needs no further processing
Implements handler::Handler.
Definition at line 70 of file misc.cpp.
boost::optional<PropertyTree> handler::Help::restructure (const PropertyTree & input, PropertyTree * parent) const inline private
removes all internal nodes which don't have a name key
Definition at line 154 of file misc.cpp.
Referenced by on_handle(), and restructure().
Member Data Documentation
std::string handler::Help::help_group private
Only shows help for members of this group.
Definition at line 128 of file misc.cpp.
Referenced by cleanup(), and Help().
The documentation for this class was generated from the following file:
src/handler/misc.cpp