MelanoBot: handler::AbstractList Class Reference
handler::AbstractList Class Reference abstract
Handles a list of elements (base class)
#include <simple-group.hpp>
Public Member Functions
AbstractList (const std::string &default_trigger, bool clear, const Settings &settings, handler::HandlerContainer *parent)
virtual bool add (const std::string &element)=0
Adds element to the list.
virtual bool remove (const std::string &element)=0
Removes element from the list.
virtual bool clear ()=0
Removes all elements from the list.
virtual std::vector< std::string > elements () const =0
Returns a vector containing all the elements of the string.
std::string get_property (const std::string &name) const override
Public Member Functions inherited from handler::SimpleGroup
SimpleGroup (const Settings &settings, handler::HandlerContainer *parent)
bool can_handle (const network::Message &msg) const override
void populate_properties (const std::vector< std::string > &properties, PropertyTree &output) const override
Simply appends globally the given property.
void initialize () override
Called at startup in case it needs to perform some initialization.
void finalize () override
Called when the connection ends.
Public Member Functions inherited from handler::SimpleAction
SimpleAction (const std::string &default_trigger, const Settings &settings, handler::HandlerContainer *parent)
Sets up the trigger.
virtual bool handle (network::Message &msg) override
Public Member Functions inherited from handler::Handler
Handler (const Settings &settings, HandlerContainer *parent)
Handler (const Handler &)=delete
Handler & operator= (const Handler &)=delete
virtual ~Handler ()
Melanobot * melanobot () const final
Get the top-level bot for this HandlerContainer.
virtual bool authorized (const network::Message &msg) const
Checks if a message is authorized to be executed by this message.
Public Member Functions inherited from handler::HandlerContainer
virtual ~HandlerContainer ()
Protected Member Functions
bool on_handle (network::Message &msg) override
Required for concrete handlers, performs the handler actions.
Protected Member Functions inherited from handler::SimpleAction
std::string reply_channel (const network::Message &msg) const override
Returns the preferred output channel for the given message.
Protected Member Functions inherited from handler::Handler
virtual void reply_to (const network::Message &input, network::OutputMessage output) const
Send a reply to a message.
void reply_to (const network::Message &msg, const string::FormattedString &text) const
void reply_to (const network::Message &msg, const std::string &text) const
template<class HandlerT >
HandlerT * get_parent () const
Find the parent handler with the given type.
Additional Inherited Members
Protected Attributes inherited from handler::SimpleGroup
std::vector< std::unique_ptr
< Handler > > children
Contained handlers.
std::string channels
std::string name
Name to show in help.
std::string help_group
Selects whether to be shown in help.
network::Connection * source = nullptr
Accepted connection (Null => all connections)
Protected Attributes inherited from handler::SimpleAction
std::string trigger
String identifying the action.
bool direct = false
std::string synopsis
Help synopsis.
std::string help ="Undocumented"
Help string.
bool public_reply = true
Whether to reply publicly or just to the sender of the message.
Protected Attributes inherited from handler::Handler
std::string auth
Authorization group required for a user message to be handled.
int priority {0}
Message priority.
Melanobot * bot {nullptr}
Pointer to the main bot.
Handler * parent_handler {nullptr}
Pointer to a handler containing this one.
Detailed Description
Handles a list of elements (base class)
Note
Derived classes shall provide the property list_name which contains a human-readable name of the list, used for descriptions of the handler.
Definition at line 74 of file simple-group.hpp.
Constructor & Destructor Documentation
handler::AbstractList::AbstractList (const std::string & default_trigger, bool clear, const Settings & settings, handler::HandlerContainer * parent)
Parameters
default_trigger Default trigger/group name
clear Whether to allow clearing the list
settings Handler settings
bot Main bot
Definition at line 226 of file simple-group.cpp.
Referenced by handler::AdminGroup::AdminGroup().
Member Function Documentation
virtual bool handler::AbstractList::add (const std::string & element) pure virtual
Adds element to the list.
Returns
true on success
Implemented in handler::AdminGroup.
Referenced by handler::ListInsert::on_handle().
virtual bool handler::AbstractList::clear () pure virtual
Removes all elements from the list.
Returns
true on success
Implemented in handler::AdminGroup.
Referenced by handler::ListClear::on_handle().
virtual std::vector<std::string> handler::AbstractList::elements () const pure virtual
Returns a vector containing all the elements of the string.
Implemented in handler::AdminGroup.
Referenced by on_handle().
std::string handler::AbstractList::get_property (const std::string & name) const inline override virtual
Extra properties:
trigger
name (same as trigger)
direct
help
synopsis
Reimplemented from handler::SimpleGroup.
Reimplemented in handler::AdminGroup.
Definition at line 107 of file simple-group.hpp.
Referenced by get_property(), handler::AdminGroup::get_property(), on_handle(), handler::ListInsert::on_handle(), handler::ListRemove::on_handle(), and handler::ListClear::on_handle().
bool handler::AbstractList::on_handle (network::Message & msg) override protected virtual
Required for concrete handlers, performs the handler actions.
Returns
true if the message has been handled and needs no further processing
Reimplemented from handler::SimpleGroup.
Definition at line 253 of file simple-group.cpp.
virtual bool handler::AbstractList::remove (const std::string & element) pure virtual
Removes element from the list.
Returns
true on success
Implemented in handler::AdminGroup.
Referenced by handler::ListRemove::on_handle().
The documentation for this class was generated from the following files:
modules/core/handler/simple-group.hpp
modules/core/handler/simple-group.cpp