MelanoBot: user::AuthSystem Class Reference
user::AuthSystem Class Reference
User authorization system.
#include <auth_system.hpp>
Public Member Functions
void add_user (const User &user, const std::vector< std::string > &groups)
Adds an user to a set of groups.
void add_user (const User &user, const std::string &group)
void remove_user (const User &user, const std::string &group)
Remove a user from the given group.
void add_group (const std::string &group)
Creates a group with the given name (if it doesn't exists)
void grant_access (const std::string &from, const std::string &to)
Grants access from group from to group to.
bool in_group (const User &user, const std::string &group, bool recursive=true)
Check if user is in group.
bool in_group (const User &user, const std::string &group, bool recursive=true) const
std::vector< User > users_with_auth (const std::string &group) const
Gets the list of users with the given authorization level.
Private Attributes
std::unordered_map
< std::string, UserGroup > user_groups
Detailed Description
User authorization system.
Definition at line 31 of file auth_system.hpp.
Member Function Documentation
void user::AuthSystem::add_group (const std::string & group) inline
Creates a group with the given name (if it doesn't exists)
Definition at line 62 of file auth_system.hpp.
Referenced by network::irc::IrcConnection::read_settings().
void user::AuthSystem::add_user (const User & user, const std::vector< std::string > & groups) inline
Adds an user to a set of groups.
If any of the groups doesn't exists, it will be created
Definition at line 39 of file auth_system.hpp.
Referenced by network::irc::IrcConnection::add_to_group().
void user::AuthSystem::add_user (const User & user, const std::string & group) inline
Definition at line 45 of file auth_system.hpp.
Referenced by add_user().
void user::AuthSystem::grant_access (const std::string & from, const std::string & to) inline
Grants access from group from to group to.
Definition at line 70 of file auth_system.hpp.
Referenced by network::irc::IrcConnection::read_settings().
bool user::AuthSystem::in_group (const User & user, const std::string & group, bool recursive = true) inline
Check if user is in group.
Definition at line 79 of file auth_system.hpp.
Referenced by network::irc::IrcConnection::add_to_group(), and network::irc::IrcConnection::remove_from_group().
bool user::AuthSystem::in_group (const User & user, const std::string & group, bool recursive = true) const inline
Definition at line 84 of file auth_system.hpp.
Referenced by network::irc::IrcConnection::user_auth().
void user::AuthSystem::remove_user (const User & user, const std::string & group) inline
Remove a user from the given group.
Definition at line 53 of file auth_system.hpp.
Referenced by network::irc::IrcConnection::remove_from_group().
std::vector<User> user::AuthSystem::users_with_auth (const std::string & group) const inline
Gets the list of users with the given authorization level.
Definition at line 96 of file auth_system.hpp.
Referenced by network::irc::IrcConnection::users_in_group().
Member Data Documentation
std::unordered_map<std::string,UserGroup> user::AuthSystem::user_groups private
Definition at line 106 of file auth_system.hpp.
Referenced by add_group(), add_user(), grant_access(), in_group(), remove_user(), and users_with_auth().
The documentation for this class was generated from the following file:
src/user/auth_system.hpp