MelanoBot: string::FormattedString Class Reference
string::FormattedString Class Reference
A formatted string.
#include <string.hpp>
Public Types
using container = std::vector< std::shared_ptr< const Element >>
using value_type = container::value_type
using reference = container::reference
using const_reference = container::const_reference
using iterator = container::iterator
using const_iterator = container::const_iterator
using difference_type = container::difference_type
using size_type = container::size_type
Public Member Functions
template<class Iterator >
FormattedString (const Iterator &i, const Iterator &j)
FormattedString (Formatter *formatter)
FormattedString (std::string ascii_string)
FormattedString ()=default
FormattedString (const FormattedString &)=default
FormattedString (FormattedString &&)=default
FormattedString & operator= (const FormattedString &)=default
FormattedString & operator= (FormattedString &&)=default
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
reference operator[] (size_type i)
const_reference operator[] (size_type i) const
size_type size () const
bool empty () const
void push_back (const_reference r)
iterator insert (const const_iterator &p, const value_type &t)
iterator insert (const const_iterator &p, size_type n, const value_type &t)
template<class InputIterator >
iterator insert (const const_iterator &p, const InputIterator &i, const InputIterator &j)
iterator insert (const const_iterator &p, const std::initializer_list< value_type > &il)
iterator erase (const const_iterator &q)
iterator erase (const const_iterator &p, const const_iterator &q)
void assign (size_type n, const value_type &t)
template<class InputIterator >
void assign (const InputIterator &i, const InputIterator &j)
void assign (const std::initializer_list< value_type > &il)
template<class ElementType , class... Args>
void append (Args &&...args)
Append an element.
void append (std::shared_ptr< Element > element)
void append (const FormattedString &string)
std::string encode (const std::string &format) const
Encode the string using the given formatter.
std::string encode (Formatter *formatter) const
Encode the string using the given formatter.
FormattedString & operator<< (const std::string &text)
FormattedString & operator<< (const char *text)
FormattedString & operator<< (const color::Color12 &color)
FormattedString & operator<< (const FormatFlags &format_flags)
FormattedString & operator<< (FormatFlags::FormatFlagsEnum format_flags)
FormattedString & operator<< (ClearFormatting)
FormattedString & operator<< (char c)
FormattedString & operator<< (const FormattedString &string)
template<class T >
FormattedString & operator<< (const T &obj)
Private Attributes
container elements
Formatter * input_formatter {nullptr}
Formatter used to decode std::string input using stream oprations.
Detailed Description
A formatted string.
Definition at line 452 of file string.hpp.
Member Typedef Documentation
using string::FormattedString::const_iterator = container::const_iterator
Definition at line 460 of file string.hpp.
using string::FormattedString::const_reference = container::const_reference
Definition at line 458 of file string.hpp.
using string::FormattedString::container = std::vector<std::shared_ptr<const Element>>
Definition at line 455 of file string.hpp.
using string::FormattedString::difference_type = container::difference_type
Definition at line 461 of file string.hpp.
using string::FormattedString::iterator = container::iterator
Definition at line 459 of file string.hpp.
using string::FormattedString::reference = container::reference
Definition at line 457 of file string.hpp.
using string::FormattedString::size_type = container::size_type
Definition at line 462 of file string.hpp.
using string::FormattedString::value_type = container::value_type
Definition at line 456 of file string.hpp.
Constructor & Destructor Documentation
template<class Iterator > string::FormattedString::FormattedString (const Iterator & i, const Iterator & j) inline
Definition at line 465 of file string.hpp.
string::FormattedString::FormattedString (Formatter * formatter) inline explicit
Definition at line 467 of file string.hpp.
Referenced by handler::Handler::reply_to().
string::FormattedString::FormattedString (std::string ascii_string) inline
Definition at line 469 of file string.hpp.
Referenced by handler::SearchWebSearx::json_success().
string::FormattedString::FormattedString () default
Referenced by handler::Help::on_handle(), handler::ListInsert::on_handle(), and handler::ListRemove::on_handle().
string::FormattedString::FormattedString (const FormattedString &) default
string::FormattedString::FormattedString (FormattedString &&) default
Member Function Documentation
template<class ElementType , class... Args> void string::FormattedString::append (Args &&... args) inline
Append an element.
Definition at line 544 of file string.hpp.
Referenced by irc::FormatterIrc::decode(), fun::FormatterRainbow::decode(), xonotic::Formatter::decode(), string::FormatterUtf8::decode(), string::FormatterAscii::decode(), string::FormatterAnsi::decode(), and FormattedString().
void string::FormattedString::append (std::shared_ptr< Element > element) inline
Definition at line 549 of file string.hpp.
Referenced by fun::FormatterRainbow::decode(), and operator<<().
void string::FormattedString::append (const FormattedString & string) inline
Definition at line 555 of file string.hpp.
Referenced by operator<<().
void string::FormattedString::assign (size_type n, const value_type & t) inline
Definition at line 524 of file string.hpp.
template<class InputIterator > void string::FormattedString::assign (const InputIterator & i, const InputIterator & j) inline
Definition at line 529 of file string.hpp.
void string::FormattedString::assign (const std::initializer_list< value_type > & il) inline
Definition at line 533 of file string.hpp.
iterator string::FormattedString::begin () inline
Definition at line 479 of file string.hpp.
const_iterator string::FormattedString::begin () const inline
Definition at line 481 of file string.hpp.
Referenced by append().
const_iterator string::FormattedString::cbegin () const inline
Definition at line 483 of file string.hpp.
const_iterator string::FormattedString::cend () const inline
Definition at line 484 of file string.hpp.
bool string::FormattedString::empty () const inline
Definition at line 490 of file string.hpp.
Referenced by handler::Help::on_handle(), operator<<(), and xonotic::XonoticConnection::say().
std::string string::FormattedString::encode (const std::string & format) const inline
Encode the string using the given formatter.
Exceptions
CriticalException if the formatter is invalid
Definition at line 564 of file string.hpp.
std::string string::FormattedString::encode (Formatter * formatter) const
Encode the string using the given formatter.
Exceptions
CriticalException if the formatter is invalid
Definition at line 183 of file string.cpp.
Referenced by encode(), Logger::log(), irc::handler::CtcpBase::reply_to(), and xonotic::XonoticConnection::say().
iterator string::FormattedString::end () inline
Definition at line 480 of file string.hpp.
const_iterator string::FormattedString::end () const inline
Definition at line 482 of file string.hpp.
Referenced by append().
iterator string::FormattedString::erase (const const_iterator & q) inline
Definition at line 515 of file string.hpp.
iterator string::FormattedString::erase (const const_iterator & p, const const_iterator & q) inline
Definition at line 519 of file string.hpp.
iterator string::FormattedString::insert (const const_iterator & p, const value_type & t) inline
Definition at line 497 of file string.hpp.
iterator string::FormattedString::insert (const const_iterator & p, size_type n, const value_type & t) inline
Definition at line 501 of file string.hpp.
template<class InputIterator > iterator string::FormattedString::insert (const const_iterator & p, const InputIterator & i, const InputIterator & j) inline
Definition at line 506 of file string.hpp.
iterator string::FormattedString::insert (const const_iterator & p, const std::initializer_list< value_type > & il) inline
Definition at line 510 of file string.hpp.
FormattedString& string::FormattedString::operator<< (const std::string & text) inline
Definition at line 577 of file string.hpp.
FormattedString& string::FormattedString::operator<< (const char * text) inline
Definition at line 588 of file string.hpp.
FormattedString& string::FormattedString::operator<< (const color::Color12 & color) inline
Definition at line 592 of file string.hpp.
FormattedString& string::FormattedString::operator<< (const FormatFlags & format_flags) inline
Definition at line 597 of file string.hpp.
FormattedString& string::FormattedString::operator<< (FormatFlags::FormatFlagsEnum format_flags) inline
Definition at line 602 of file string.hpp.
FormattedString& string::FormattedString::operator<< (ClearFormatting) inline
Definition at line 607 of file string.hpp.
FormattedString& string::FormattedString::operator<< (char c) inline
Definition at line 612 of file string.hpp.
FormattedString& string::FormattedString::operator<< (const FormattedString & string) inline
Definition at line 617 of file string.hpp.
template<class T > FormattedString& string::FormattedString::operator<< (const T & obj) inline
Definition at line 624 of file string.hpp.
FormattedString& string::FormattedString::operator= (const FormattedString &) default
FormattedString& string::FormattedString::operator= (FormattedString &&) default
reference string::FormattedString::operator[] (size_type i) inline
Definition at line 486 of file string.hpp.
const_reference string::FormattedString::operator[] (size_type i) const inline
Definition at line 487 of file string.hpp.
void string::FormattedString::push_back (const_reference r) inline
Definition at line 492 of file string.hpp.
size_type string::FormattedString::size () const inline
Definition at line 489 of file string.hpp.
Member Data Documentation
container string::FormattedString::elements private
Definition at line 632 of file string.hpp.
Referenced by append(), assign(), begin(), cbegin(), cend(), empty(), end(), erase(), FormattedString(), insert(), operator[](), push_back(), and size().
Formatter* string::FormattedString::input_formatter {nullptr} private
Formatter used to decode std::string input using stream oprations.
If it's nullptr, it will be interpreted as an ASCII string
Definition at line 638 of file string.hpp.
Referenced by FormattedString(), and operator<<().
The documentation for this class was generated from the following files:
src/string/string.hpp
src/string/string.cpp