MelanoBot: string::Utf8Parser Class Reference
string::Utf8Parser Class Reference
Class used to parse and convert UTF-8.
#include <string.hpp>
Public Types
using Byte = uint8_t
Public Member Functions
void parse (const std::string &string)
Parse the string.
bool finished () const
Whether the end of the string has been reached.
Static Public Member Functions
static std::string encode (uint32_t value)
Encode a unicode value to UTF-8.
static bool is_ascii (Byte b)
Whether a byte is a valid ascii character.
static char to_ascii (uint32_t unicode)
Transliterate a single character to ascii.
static char to_ascii (const std::string &utf8_char)
Transliterate a single character to ascii.
Public Attributes
std::function< void(uint8_t)> callback_ascii
std::function< void(uint32_t, const std::string &)> callback_utf8
std::function< void(const std::string &)> callback_invalid
std::function< void()> callback_end
QuickStream input
Private Member Functions
void check_valid ()
Handles an invalid/incomplete sequence.
Private Attributes
std::string utf8
Multibyte string.
uint32_t unicode
Multibyte value.
unsigned length = 0
Multibyte length.
Detailed Description
Class used to parse and convert UTF-8.
Definition at line 42 of file string.hpp.
Member Typedef Documentation
using string::Utf8Parser::Byte = uint8_t
Definition at line 45 of file string.hpp.
Member Function Documentation
void string::Utf8Parser::check_valid () private
Handles an invalid/incomplete sequence.
Definition at line 146 of file string.cpp.
Referenced by parse().
std::string string::Utf8Parser::encode (uint32_t value) static
Encode a unicode value to UTF-8.
Definition at line 118 of file string.cpp.
Referenced by JsonParser::parse_json_string(), xonotic::Formatter::qfont(), and to_ascii().
bool string::Utf8Parser::finished () const inline
Whether the end of the string has been reached.
Definition at line 62 of file string.hpp.
static bool string::Utf8Parser::is_ascii (Byte b) inline static
Whether a byte is a valid ascii character.
Definition at line 72 of file string.hpp.
void string::Utf8Parser::parse (const std::string & string)
Parse the string.
Definition at line 69 of file string.cpp.
Referenced by irc::FormatterIrc::decode(), fun::FormatterRainbow::decode(), xonotic::Formatter::decode(), string::FormatterUtf8::decode(), string::FormatterAnsi::decode(), and string::FormatterConfig::decode().
char string::Utf8Parser::to_ascii (uint32_t unicode) static
Transliterate a single character to ascii.
Definition at line 41 of file string.cpp.
char string::Utf8Parser::to_ascii (const std::string & utf8_char) static
Transliterate a single character to ascii.
Definition at line 48 of file string.cpp.
Referenced by to_ascii(), string::FormatterAscii::unicode(), and string::FormatterAnsi::unicode().
Member Data Documentation
std::function<void(uint8_t)> string::Utf8Parser::callback_ascii
Definition at line 47 of file string.hpp.
Referenced by irc::FormatterIrc::decode(), fun::FormatterRainbow::decode(), xonotic::Formatter::decode(), string::FormatterUtf8::decode(), string::FormatterAnsi::decode(), string::FormatterConfig::decode(), and parse().
std::function<void()> string::Utf8Parser::callback_end
Definition at line 50 of file string.hpp.
Referenced by xonotic::Formatter::decode(), string::FormatterUtf8::decode(), string::FormatterAnsi::decode(), string::FormatterConfig::decode(), and parse().
std::function<void(const std::string&)> string::Utf8Parser::callback_invalid
Definition at line 49 of file string.hpp.
Referenced by check_valid().
std::function<void(uint32_t,const std::string&)> string::Utf8Parser::callback_utf8
Definition at line 48 of file string.hpp.
Referenced by irc::FormatterIrc::decode(), fun::FormatterRainbow::decode(), xonotic::Formatter::decode(), string::FormatterUtf8::decode(), string::FormatterAnsi::decode(), string::FormatterConfig::decode(), and parse().
QuickStream string::Utf8Parser::input
Definition at line 52 of file string.hpp.
Referenced by irc::FormatterIrc::decode(), xonotic::Formatter::decode(), string::FormatterAnsi::decode(), string::FormatterConfig::decode(), finished(), and parse().
unsigned string::Utf8Parser::length = 0 private
Multibyte length.
Definition at line 87 of file string.hpp.
Referenced by check_valid(), and parse().
uint32_t string::Utf8Parser::unicode private
Multibyte value.
Definition at line 86 of file string.hpp.
Referenced by check_valid(), and parse().
std::string string::Utf8Parser::utf8 private
Multibyte string.
Definition at line 85 of file string.hpp.
Referenced by check_valid(), and parse().
The documentation for this class was generated from the following files:
src/string/string.hpp
src/string/string.cpp