MelanoBot: handler::CtcpBase Class Reference
handler::CtcpBase Class Reference
Base class for handling CTCP requests.
Public Member Functions
CtcpBase (const std::string &ctcp, const Settings &settings, Melanobot *bot)
bool can_handle (const network::Message &msg) override
Checks if a message can be handled.
Public Member Functions inherited from handler::Handler
Handler (const Settings &settings, Melanobot *bot)
virtual ~Handler ()
virtual bool handle (network::Message &msg)
Attempt to handle the message.
virtual void initialize ()
Called at startup in case it needs to perform some initialization.
virtual void finalize ()
Called when the connection ends.
virtual bool authorized (const network::Message &msg) const
Checks if a message is authorized to be executed by this message.
Protected Member Functions
void reply_to (const network::Message &msg, const string::FormattedString &text) const override
Sends a properly formatted reply corresponding to ctctp.
Protected Member Functions inherited from handler::Handler
virtual bool on_handle (network::Message &msg)=0
Attempt to handle the message.
void reply_to (const network::Message &msg, const std::string &text) const
Private Attributes
std::string ctcp
Name of the ctcp command to reply to.
Additional Inherited Members
Protected Attributes inherited from handler::Handler
std::string auth
Authorization group required for a user message to be handled.
int priority = 0
Message priority.
Melanobot * bot = nullptr
Pointer to the main bot.
Detailed Description
Base class for handling CTCP requests.
See also
http://www.irchelp.org/irchelp/rfc/ctcpspec.html
Definition at line 29 of file ctcp.cpp.
Constructor & Destructor Documentation
handler::CtcpBase::CtcpBase (const std::string & ctcp, const Settings & settings, Melanobot * bot) inline
Definition at line 33 of file ctcp.cpp.
Referenced by handler::CtcpPing::CtcpPing(), handler::CtcpSource::CtcpSource(), handler::CtcpTime::CtcpTime(), handler::CtcpUserInfo::CtcpUserInfo(), and handler::CtcpVersion::CtcpVersion().
Member Function Documentation
bool handler::CtcpBase::can_handle (const network::Message & msg) inline override virtual
Checks if a message can be handled.
Returns
true if the message can be handled by the handler
Todo:
const?
Reimplemented from handler::Handler.
Definition at line 40 of file ctcp.cpp.
void handler::CtcpBase::reply_to (const network::Message & msg, const string::FormattedString & text) const inline override protected virtual
Sends a properly formatted reply corresponding to ctctp.
Reimplemented from handler::Handler.
Definition at line 53 of file ctcp.cpp.
Member Data Documentation
std::string handler::CtcpBase::ctcp private
Name of the ctcp command to reply to.
Definition at line 64 of file ctcp.cpp.
Referenced by can_handle(), CtcpBase(), and reply_to().
The documentation for this class was generated from the following file:
src/handler/ctcp.cpp