MelanoBot: ErrorLog Class Reference
ErrorLog Class Reference
Utility for error messages.
#include <logger.hpp>
Public Member Functions
ErrorLog (const std::string &type, const std::string &error="Error")
Public Member Functions inherited from Log
Log (std::string type, char direction, int verbosity=2)
Log (const std::string &type, char direction, const std::string &message, int verbosity=2)
Log (const Log &)=delete
Log (Log &&)=delete
Log & operator= (const Log &)=delete
Log & operator= (Log &&)=delete
~Log ()
template<class T >
Log & operator<< (const T &t)
Additional Inherited Members
Public Attributes inherited from Log
std::string type
char direction
int verbosity
string::FormattedString stream
Detailed Description
Utility for error messages.
Definition at line 168 of file logger.hpp.
Constructor & Destructor Documentation
ErrorLog::ErrorLog (const std::string & type, const std::string & error = "Error") inline
Definition at line 171 of file logger.hpp.
Referenced by string::Formatter::Registry::add_formatter(), handler::HandlerFactory::build(), xonotic::XonoticConnection::command(), xonotic::XonoticConnection::create(), network::ConnectionFactory::create(), string::Formatter::Registry::formatter(), xonotic::XonoticConnection::handle_message(), Settings::initialize(), network::ServiceRegistry::initialize(), Logger::load_settings(), main(), Melanobot::Melanobot(), handler::BridgeAttach::on_handle(), StdinConnection::on_read_line(), JsonParser::parse_json_root(), xonotic::XonoticConnection::read(), handler::HandlerFactory::register_handler(), network::ServiceRegistry::register_service(), Melanobot::run(), StdinConnection::run(), network::ServiceRegistry::service(), and xonotic::XonoticConnection::XonoticConnection().
The documentation for this class was generated from the following file:
src/string/logger.hpp