MelanoBot: user::UserManager Class Reference
user::UserManager Class Reference
A class to keep track of users.
#include <user_manager.hpp>
Public Member Functions
User * add_user (const User &user)
Adds a user.
User * user (const std::string &local_id)
Get a user by local id.
const User * user (const std::string &local_id) const
User * user_by_property (const std::string &property_name, const std::string &property_value)
Get the first user with the matching property.
const User * user_by_property (const std::string &property_name, const std::string &property_value) const
std::list< User > users () const
Get all users.
template<class UnaryPredicate >
std::list< User > users (const UnaryPredicate &predicate) const
Get all users matching the given condition.
std::list< User > channel_users (const std::string &channel) const
Get all users on the given channel.
std::list< User * > channel_user_pointers (const std::string &channel)
Get all users on the given channel.
bool remove_user (const std::string &local_id)
Remove a user by local_id.
bool change_id (const std::string &old_local_id, const std::string &new_local_id)
Change user id.
void update_user (const std::string &local_id, const User &user)
Update a user.
void clear ()
Removes all users.
auto begin ()
Iterator to the first user.
auto end ()
Iterator to past the last user.
auto begin () const
Constant iterator to the first user.
auto end () const
Constant iterator to past the last user.
auto cbegin () const
Constant iterator to the first user.
auto cend () const
Constant iterator to past the last user.
std::list< User > & users_reference ()
Returns a writable reference to the user list.
const std::list< User > & users_reference () const
Private Attributes
std::list< User > users_
Detailed Description
A class to keep track of users.
Definition at line 31 of file user_manager.hpp.
Member Function Documentation
User * user::UserManager::add_user (const User & user)
Adds a user.
Note
If a different user with the same user.local_id is found, it will be overwritten
Definition at line 24 of file user_manager.cpp.
Referenced by xonotic::XonoticConnection::check_user(), and xonotic::XonoticConnection::handle_message().
auto user::UserManager::begin () inline
Iterator to the first user.
Definition at line 111 of file user_manager.hpp.
auto user::UserManager::begin () const inline
Constant iterator to the first user.
Definition at line 119 of file user_manager.hpp.
auto user::UserManager::cbegin () const inline
Constant iterator to the first user.
Definition at line 127 of file user_manager.hpp.
auto user::UserManager::cend () const inline
Constant iterator to past the last user.
Definition at line 131 of file user_manager.hpp.
bool user::UserManager::change_id (const std::string & old_local_id, const std::string & new_local_id)
Change user id.
Returns
true on success
Note
This doesn't check if a different user with the same id already exists
Definition at line 116 of file user_manager.cpp.
std::list< User * > user::UserManager::channel_user_pointers (const std::string & channel)
Get all users on the given channel.
Definition at line 88 of file user_manager.cpp.
std::list< User > user::UserManager::channel_users (const std::string & channel) const
Get all users on the given channel.
Definition at line 71 of file user_manager.cpp.
void user::UserManager::clear () inline
Removes all users.
Definition at line 106 of file user_manager.hpp.
Referenced by xonotic::XonoticConnection::connect(), and xonotic::XonoticConnection::disconnect().
auto user::UserManager::end () inline
Iterator to past the last user.
Definition at line 115 of file user_manager.hpp.
auto user::UserManager::end () const inline
Constant iterator to past the last user.
Definition at line 123 of file user_manager.hpp.
bool user::UserManager::remove_user (const std::string & local_id)
Remove a user by local_id.
Returns
true on success
Definition at line 105 of file user_manager.cpp.
Referenced by xonotic::XonoticConnection::handle_message().
void user::UserManager::update_user (const std::string & local_id, const User & user)
Update a user.
If there's no user matching local_id, user is inserted
Definition at line 127 of file user_manager.cpp.
User * user::UserManager::user (const std::string & local_id)
Get a user by local id.
Returns
A pointer to the user or null if not found
Definition at line 37 of file user_manager.cpp.
Referenced by xonotic::XonoticConnection::handle_message(), and xonotic::XonoticConnection::update_user().
const User * user::UserManager::user (const std::string & local_id) const
Definition at line 45 of file user_manager.cpp.
Referenced by xonotic::XonoticConnection::get_user().
User * user::UserManager::user_by_property (const std::string & property_name, const std::string & property_value)
Get the first user with the matching property.
Returns
A pointer to the user or null if not found
Definition at line 53 of file user_manager.cpp.
Referenced by xonotic::XonoticConnection::check_user().
const User * user::UserManager::user_by_property (const std::string & property_name, const std::string & property_value) const
Definition at line 62 of file user_manager.cpp.
Referenced by xonotic::XonoticConnection::get_user().
std::list<User> user::UserManager::users () const inline
Get all users.
Definition at line 58 of file user_manager.hpp.
Referenced by xonotic::XonoticConnection::get_users().
template<class UnaryPredicate > std::list<User> user::UserManager::users (const UnaryPredicate & predicate) const inline
Get all users matching the given condition.
Definition at line 64 of file user_manager.hpp.
std::list<User>& user::UserManager::users_reference () inline
Returns a writable reference to the user list.
Definition at line 136 of file user_manager.hpp.
Referenced by xonotic::XonoticConnection::check_user_end(), and xonotic::XonoticConnection::handle_message().
const std::list<User>& user::UserManager::users_reference () const inline
Definition at line 137 of file user_manager.hpp.
Member Data Documentation
std::list<User> user::UserManager::users_ private
Definition at line 140 of file user_manager.hpp.
Referenced by add_user(), begin(), cbegin(), cend(), change_id(), channel_user_pointers(), channel_users(), clear(), end(), remove_user(), update_user(), user(), user_by_property(), users(), and users_reference().
The documentation for this class was generated from the following files:
src/user/user_manager.hpp
src/user/user_manager.cpp