MelanoBot: handler::EventMessageBase Class Reference
handler::EventMessageBase Class Reference
Base class for JoinMessage and similar.
#include <bridge.hpp>
Public Member Functions
EventMessageBase (network::Message::Type type, const Settings &settings,::handler::HandlerContainer *parent)
bool can_handle (const network::Message &msg) const override
Checks if a message can be handled.
Public Member Functions inherited from handler::Handler
Handler (const Settings &settings, HandlerContainer *parent)
Handler (const Handler &)=delete
Handler & operator= (const Handler &)=delete
virtual ~Handler ()
Melanobot * melanobot () const final
Get the top-level bot for this HandlerContainer.
virtual bool handle (network::Message &msg)
Attempt to handle the message.
virtual void initialize ()
Called at startup in case it needs to perform some initialization.
virtual void finalize ()
Called when the connection ends.
virtual std::string get_property (const std::string &name) const
Get a property by name.
void populate_properties (const std::vector< std::string > &properties, PropertyTree &output) const override
Simply appends globally the given property.
Public Member Functions inherited from handler::HandlerContainer
virtual ~HandlerContainer ()
Protected Member Functions
bool on_handle (network::Message &msg) override
Required for concrete handlers, performs the handler actions.
virtual Properties message_replacements (const network::Message &msg) const
Protected Member Functions inherited from handler::Handler
virtual std::string reply_channel (const network::Message &msg) const
Returns the preferred output channel for the given message.
virtual void reply_to (const network::Message &input, network::OutputMessage output) const
Send a reply to a message.
void reply_to (const network::Message &msg, const string::FormattedString &text) const
void reply_to (const network::Message &msg, const std::string &text) const
template<class HandlerT >
HandlerT * get_parent () const
Find the parent handler with the given type.
Private Attributes
network::Message::Type type
Type of messages to be handled.
std::string prefix
Message prefix.
std::string message
Message to send.
bool action = false
Whether it should output an action.
bool on_self = false
Whether to be triggered when the joining user has the same name as the source connection.
bool on_others =true
Whether to be triggered when the joining user name differs from the source connection.
network::Duration timeout {network::Duration::zero()}
Output message timeout.
Additional Inherited Members
Protected Attributes inherited from handler::Handler
int priority {0}
Message priority.
Melanobot * bot {nullptr}
Pointer to the main bot.
Handler * parent_handler {nullptr}
Pointer to a handler containing this one.
Detailed Description
Base class for JoinMessage and similar.
Definition at line 103 of file bridge.hpp.
Constructor & Destructor Documentation
handler::EventMessageBase::EventMessageBase (network::Message::Type type, const Settings & settings, ::handler::HandlerContainer * parent) inline
Definition at line 106 of file bridge.hpp.
Referenced by handler::JoinMessage::JoinMessage(), handler::KickMessage::KickMessage(), handler::PartMessage::PartMessage(), and handler::RenameMessage::RenameMessage().
Member Function Documentation
bool handler::EventMessageBase::can_handle (const network::Message & msg) const inline override virtual
Checks if a message can be handled.
Precondition
msg.source not null
Returns
true if the message can be handled by the handler
Reimplemented from handler::Handler.
Definition at line 125 of file bridge.hpp.
virtual Properties handler::EventMessageBase::message_replacements (const network::Message & msg) const inline protected virtual
Reimplemented in handler::KickMessage.
Definition at line 152 of file bridge.hpp.
Referenced by on_handle().
bool handler::EventMessageBase::on_handle (network::Message & msg) inline override protected virtual
Required for concrete handlers, performs the handler actions.
Returns
true if the message has been handled and needs no further processing
Implements handler::Handler.
Definition at line 133 of file bridge.hpp.
Member Data Documentation
bool handler::EventMessageBase::action = false private
Whether it should output an action.
Definition at line 169 of file bridge.hpp.
Referenced by EventMessageBase(), and on_handle().
std::string handler::EventMessageBase::message private
Message to send.
Definition at line 168 of file bridge.hpp.
Referenced by EventMessageBase(), and on_handle().
bool handler::EventMessageBase::on_others =true private
Whether to be triggered when the joining user name differs from the source connection.
Definition at line 171 of file bridge.hpp.
Referenced by can_handle(), and EventMessageBase().
bool handler::EventMessageBase::on_self = false private
Whether to be triggered when the joining user has the same name as the source connection.
Definition at line 170 of file bridge.hpp.
Referenced by can_handle(), and EventMessageBase().
std::string handler::EventMessageBase::prefix private
Message prefix.
Definition at line 167 of file bridge.hpp.
Referenced by EventMessageBase(), and on_handle().
network::Duration handler::EventMessageBase::timeout {network::Duration::zero()} private
Output message timeout.
Definition at line 172 of file bridge.hpp.
Referenced by EventMessageBase(), and on_handle().
network::Message::Type handler::EventMessageBase::type private
Type of messages to be handled.
Definition at line 166 of file bridge.hpp.
Referenced by can_handle(), and EventMessageBase().
The documentation for this class was generated from the following file:
modules/core/handler/bridge.hpp