MelanoBot: network::irc::Network Class Reference
network::irc::Network Class Reference
A collection of servers.
#include <irc.hpp>
Public Types
typedef std::vector< Server > ServerList
Public Member Functions
Network (const Server &server)
Network (const ServerList &servers)
Network (const Network &other)
Network & operator= (const Network &other)=delete
const Server & current () const
Current server.
const Server & next ()
Advances to the next server in the list and returns it.
int size () const
Number of servers.
Private Attributes
ServerList servers
std::atomic< unsigned > current_server { 0 }
Detailed Description
A collection of servers.
Definition at line 79 of file irc.hpp.
Member Typedef Documentation
typedef std::vector<Server> network::irc::Network::ServerList
Definition at line 82 of file irc.hpp.
Constructor & Destructor Documentation
network::irc::Network::Network (const Server & server) inline explicit
Definition at line 84 of file irc.hpp.
Referenced by network::irc::IrcConnection::IrcConnection().
network::irc::Network::Network (const ServerList & servers) inline explicit
Definition at line 86 of file irc.hpp.
Referenced by Network().
network::irc::Network::Network (const Network & other) inline
Definition at line 93 of file irc.hpp.
Referenced by network::irc::IrcConnection::IrcConnection().
Member Function Documentation
const Server& network::irc::Network::current () const inline
Current server.
Definition at line 103 of file irc.hpp.
Referenced by network::irc::IrcConnection::connect(), next(), and network::irc::IrcConnection::server().
const Server& network::irc::Network::next () inline
Advances to the next server in the list and returns it.
Note
Acts as a circular buffer, will always return a valid server
Definition at line 112 of file irc.hpp.
Referenced by network::irc::IrcConnection::reconnect().
Network& network::irc::Network::operator= (const Network & other) delete
Note
Deleted because it would require a lock
int network::irc::Network::size () const inline
Number of servers.
Note
Always >= 0
Definition at line 124 of file irc.hpp.
Member Data Documentation
std::atomic<unsigned> network::irc::Network::current_server { 0 } private
Todo:
needs atomic?
Definition at line 134 of file irc.hpp.
Referenced by next().
ServerList network::irc::Network::servers private
Definition at line 130 of file irc.hpp.
Referenced by current(), Network(), next(), and size().
The documentation for this class was generated from the following file:
src/network/irc.hpp