MelanoBot: ConcurrentContainer< Container > Class Template Reference
ConcurrentContainer< Container > Class Template Reference
Container wrapper which makes it fit for concurrent use.
#include <concurrent_container.hpp>
Public Types
typedef Container container_type
typedef Container::value_type value_type
typedef Container::reference reference
typedef Container::const_reference const_reference
typedef void(Container::* method_push)(const_reference)
typedef void(Container::* method_pop)()
typedef const_reference(Container::* method_get)() const
Public Member Functions
ConcurrentContainer (method_push container_push, method_pop container_pop, method_get container_get)
void push (const_reference item)
Add an element to the container.
void pop (reference item)
Retrieve an element from the container.
bool active () const
Whether the container is allowed to process data.
void start ()
Starts the container.
void stop ()
Stops the container.
Container & get_container ()
Returns a reference to the container without any locks.
Private Member Functions
bool wait_condition () const
Private Attributes
method_push container_push
method_pop container_pop
method_get container_get
Container container
std::atomic< bool > run {true}
std::mutex mutex
std::condition_variable condition
Detailed Description
template<class Container>
class ConcurrentContainer< Container >
Container wrapper which makes it fit for concurrent use.
To be used with one consumer and multiple producers. It only provides utilities for insertion and extraction.
Definition at line 35 of file concurrent_container.hpp.
Member Typedef Documentation
template<class Container> typedef Container::const_reference ConcurrentContainer< Container >::const_reference
Definition at line 41 of file concurrent_container.hpp.
template<class Container> typedef Container ConcurrentContainer< Container >::container_type
Definition at line 38 of file concurrent_container.hpp.
template<class Container> typedef const_reference(Container::* ConcurrentContainer< Container >::method_get)() const
Definition at line 44 of file concurrent_container.hpp.
template<class Container> typedef void(Container::* ConcurrentContainer< Container >::method_pop)()
Definition at line 43 of file concurrent_container.hpp.
template<class Container> typedef void(Container::* ConcurrentContainer< Container >::method_push)(const_reference)
Definition at line 42 of file concurrent_container.hpp.
template<class Container> typedef Container::reference ConcurrentContainer< Container >::reference
Definition at line 40 of file concurrent_container.hpp.
template<class Container> typedef Container::value_type ConcurrentContainer< Container >::value_type
Definition at line 39 of file concurrent_container.hpp.
Constructor & Destructor Documentation
template<class Container> ConcurrentContainer< Container >::ConcurrentContainer (method_push container_push, method_pop container_pop, method_get container_get) inline
Definition at line 46 of file concurrent_container.hpp.
Member Function Documentation
template<class Container> bool ConcurrentContainer< Container >::active () const inline
Whether the container is allowed to process data.
Definition at line 85 of file concurrent_container.hpp.
Referenced by network::irc::Buffer::process(), Melanobot::run(), network::ThreadedAsyncService::run(), and network::irc::Buffer::run_output().
template<class Container> Container& ConcurrentContainer< Container >::get_container () inline
Returns a reference to the container without any locks.
Definition at line 110 of file concurrent_container.hpp.
template<class Container> void ConcurrentContainer< Container >::pop (reference item) inline
Retrieve an element from the container.
Waits until there are elements to get or active() is false
Definition at line 72 of file concurrent_container.hpp.
Referenced by network::irc::Buffer::process(), Melanobot::run(), and network::ThreadedAsyncService::run().
template<class Container> void ConcurrentContainer< Container >::push (const_reference item) inline
Add an element to the container.
Acquires a lock, inserts the item and notifies the consumer.
If active() is not true, it will discard any input
Definition at line 59 of file concurrent_container.hpp.
Referenced by network::ThreadedAsyncService::async_query(), network::irc::Buffer::insert(), and Melanobot::message().
template<class Container> void ConcurrentContainer< Container >::start () inline
Starts the container.
Note
This is the state after construction
Postcondition
active() is true
Definition at line 92 of file concurrent_container.hpp.
Referenced by network::irc::Buffer::run_output(), and network::ThreadedAsyncService::start().
template<class Container> void ConcurrentContainer< Container >::stop () inline
Stops the container.
Postcondition
active() is false
Definition at line 101 of file concurrent_container.hpp.
Referenced by Melanobot::stop(), network::irc::Buffer::stop(), and network::ThreadedAsyncService::stop().
template<class Container> bool ConcurrentContainer< Container >::wait_condition () const inline private
Definition at line 122 of file concurrent_container.hpp.
Referenced by ConcurrentContainer< std::queue< T, Container > >::pop().
Member Data Documentation
template<class Container> std::condition_variable ConcurrentContainer< Container >::condition private
Definition at line 120 of file concurrent_container.hpp.
Referenced by ConcurrentContainer< std::queue< T, Container > >::pop(), ConcurrentContainer< std::queue< T, Container > >::push(), and ConcurrentContainer< std::queue< T, Container > >::stop().
template<class Container> Container ConcurrentContainer< Container >::container private
Definition at line 116 of file concurrent_container.hpp.
Referenced by ConcurrentContainer< std::queue< T, Container > >::get_container(), ConcurrentContainer< std::queue< T, Container > >::pop(), ConcurrentContainer< std::queue< T, Container > >::push(), and ConcurrentContainer< std::queue< T, Container > >::wait_condition().
template<class Container> method_get ConcurrentContainer< Container >::container_get private
Definition at line 115 of file concurrent_container.hpp.
Referenced by ConcurrentContainer< std::queue< T, Container > >::ConcurrentContainer(), and ConcurrentContainer< std::queue< T, Container > >::pop().
template<class Container> method_pop ConcurrentContainer< Container >::container_pop private
Definition at line 114 of file concurrent_container.hpp.
Referenced by ConcurrentContainer< std::queue< T, Container > >::ConcurrentContainer(), and ConcurrentContainer< std::queue< T, Container > >::pop().
template<class Container> method_push ConcurrentContainer< Container >::container_push private
Definition at line 113 of file concurrent_container.hpp.
Referenced by ConcurrentContainer< std::queue< T, Container > >::ConcurrentContainer(), and ConcurrentContainer< std::queue< T, Container > >::push().
template<class Container> std::mutex ConcurrentContainer< Container >::mutex private
Definition at line 119 of file concurrent_container.hpp.
template<class Container> std::atomic<bool> ConcurrentContainer< Container >::run {true} private
Definition at line 118 of file concurrent_container.hpp.
Referenced by ConcurrentContainer< std::queue< T, Container > >::active(), ConcurrentContainer< std::queue< T, Container > >::pop(), ConcurrentContainer< std::queue< T, Container > >::push(), ConcurrentContainer< std::queue< T, Container > >::start(), ConcurrentContainer< std::queue< T, Container > >::stop(), and ConcurrentContainer< std::queue< T, Container > >::wait_condition().
The documentation for this class was generated from the following file:
src/concurrent_container.hpp