MelanoBot: timer::DateTime Class Reference
timer::DateTime Class Reference
A class representing a date and time.
#include <time.hpp>
Public Types
using Clock = std::chrono::system_clock
Wall clock time.
using Time = Clock::time_point
Time point.
using Duration = Clock::duration
Public Member Functions
DateTime ()
DateTime (const Time &time)
constexpr DateTime (int32_t year, Month month, days day)
constexpr DateTime (int32_t year, Month month, days day, hours hour, minutes minute, seconds second=seconds(0), milliseconds millisecond=milliseconds(0))
SUPER_CONSTEXPR Time time_point () const noexcept
Build a time point from the DateTime.
SUPER_CONSTEXPR int64_t unix () const noexcept
Return as a unix timestamp.
constexpr auto millisecond () const noexcept
Milliseconds.
constexpr auto second () const noexcept
Seconds.
constexpr auto minute () const noexcept
Minutes.
constexpr auto hour () const noexcept
Hour of the day [0,23].
constexpr auto hour12 () const noexcept
Hour of the day [1,12].
constexpr bool am () const noexcept
Whether it's a.m. (12:00 am = midnight, 12:00pm = noon)
constexpr bool pm () const noexcept
Whether it's a.m. (12:00 am = midnight, 12:00pm = noon)
constexpr auto day () const noexcept
Day of the month [1,31].
SUPER_CONSTEXPR int year_day () const noexcept
Day of the year [0,365].
constexpr Month month () const noexcept
Month.
constexpr int month_int () const noexcept
Month (as an int)
constexpr auto year () const noexcept
Year.
constexpr bool leap_year () const noexcept
Whether the year is leap.
constexpr int month_days (Month m) const noexcept
Number of days in the given month.
SUPER_CONSTEXPR WeekDay week_day () const noexcept
Evaluates the week day.
SUPER_CONSTEXPR void set_time (hours hour, minutes minute, seconds second=seconds(0), milliseconds millisecond=milliseconds(0)) noexcept
Set the time without changing the date.
SUPER_CONSTEXPR void set_date (int32_t year, Month month, days day) noexcept
Set the date without changing the time.
SUPER_CONSTEXPR void set_date (Month month, days day) noexcept
Set the date without changing the year or the time.
SUPER_CONSTEXPR void set_year (int32_t year) noexcept
Sets the year.
SUPER_CONSTEXPR void set_month (Month month) noexcept
Sets the month.
SUPER_CONSTEXPR void set_day (int day) noexcept
Sets the day of the month.
SUPER_CONSTEXPR void set_hour (uint8_t hour) noexcept
Sets the hour of the day [0,23].
SUPER_CONSTEXPR void set_minute (uint8_t minute) noexcept
Sets the minute of the hour [0,59].
SUPER_CONSTEXPR void set_second (uint8_t second) noexcept
Sets the second of the minute [0,59].
SUPER_CONSTEXPR void set_millisecond (uint8_t milliseconds) noexcept
Sets the milliseconds of the second [0,999].
template<class Rep , class Period >
DateTime & operator+= (const std::chrono::duration< Rep, Period > &dur) noexcept
Add a duration.
template<class Rep , class Period >
SUPER_CONSTEXPR DateTime operator+ (const std::chrono::duration< Rep, Period > &dur) const noexcept
template<class Rep , class Period >
DateTime & operator-= (const std::chrono::duration< Rep, Period > &dur) noexcept
Subtract a duration.
template<class Rep , class Period >
SUPER_CONSTEXPR DateTime operator- (const std::chrono::duration< Rep, Period > &dur) const noexcept
SUPER_CONSTEXPR Duration operator- (const DateTime &rhs) const noexcept
SUPER_CONSTEXPR bool operator< (const DateTime &rhs) const noexcept
SUPER_CONSTEXPR bool operator> (const DateTime &rhs) const noexcept
constexpr bool operator== (const DateTime &rhs) const noexcept
constexpr bool operator!= (const DateTime &rhs) const noexcept
SUPER_CONSTEXPR bool operator<= (const DateTime &rhs) const noexcept
SUPER_CONSTEXPR bool operator>= (const DateTime &rhs) const noexcept
Static Public Member Functions
static constexpr int year_days (int32_t year) noexcept
Number of days in a year.
static constexpr bool leap_year (int32_t year) noexcept
Whether the year is leap.
static constexpr int month_days (int32_t year, Month m) noexcept
Number of days in the given month.
Static Private Member Functions
template<class T1 , class T2 >
static void subtract_helper (int nextunit, T1 &mask, T1 &ms, T2 &member) noexcept
Helper function for operator-=()
template<class T1 , class T2 >
static void add_helper (int nextunit, T1 &mask, T1 &ms, T2 &member) noexcept
static constexpr int32_t positive_year (int32_t year) noexcept
Private Attributes
int32_t year_
Year.
Month month_
Month.
int8_t day_
Day of the month [1,31].
int8_t hour_
Hour [0,23].
int8_t minute_
Minute [0,59].
int8_t second_
Second [0,59].
int16_t milliseconds_
Milli seconds [0,10^3)
Detailed Description
A class representing a date and time.
Note
Some functions assume std::chrono::system_clock starts on the unix epoch
Definition at line 305 of file time.hpp.
Member Typedef Documentation
using timer::DateTime::Clock = std::chrono::system_clock
Wall clock time.
Definition at line 308 of file time.hpp.
using timer::DateTime::Duration = Clock::duration
Definition at line 310 of file time.hpp.
using timer::DateTime::Time = Clock::time_point
Time point.
Definition at line 309 of file time.hpp.
Constructor & Destructor Documentation
timer::DateTime::DateTime () inline
Definition at line 313 of file time.hpp.
Referenced by timer::format(), and timer::TimeParser::parse_day().
timer::DateTime::DateTime (const Time & time) inline
Definition at line 315 of file time.hpp.
Referenced by DateTime().
constexpr timer::DateTime::DateTime (int32_t year, Month month, days day) inline
Definition at line 321 of file time.hpp.
constexpr timer::DateTime::DateTime (int32_t year, Month month, days day, hours hour, minutes minute, seconds second = seconds(0), milliseconds millisecond = milliseconds(0)) inline
Definition at line 324 of file time.hpp.
Referenced by DateTime().
Member Function Documentation
template<class T1 , class T2 > static void timer::DateTime::add_helper (int nextunit, T1 & mask, T1 & ms, T2 & member) inline static private noexcept
Definition at line 833 of file time.hpp.
constexpr bool timer::DateTime::am () const inline noexcept
Whether it's a.m. (12:00 am = midnight, 12:00pm = noon)
Definition at line 395 of file time.hpp.
Referenced by timer::format_char().
constexpr auto timer::DateTime::day () const inline noexcept
Day of the month [1,31].
Definition at line 403 of file time.hpp.
Referenced by timer::format_char(), timer::TimeParser::parse_date_desc(), and year_day().
constexpr auto timer::DateTime::hour () const inline noexcept
Hour of the day [0,23].
Definition at line 387 of file time.hpp.
Referenced by timer::format_char().
constexpr auto timer::DateTime::hour12 () const inline noexcept
Hour of the day [1,12].
Definition at line 391 of file time.hpp.
Referenced by timer::format_char().
constexpr bool timer::DateTime::leap_year () const inline noexcept
Whether the year is leap.
Note
This is true for the Gregorian calendar and disregards oddities of dates before 15 October 1582
Definition at line 439 of file time.hpp.
Referenced by timer::format_char().
static constexpr bool timer::DateTime::leap_year (int32_t year) inline static noexcept
Whether the year is leap.
Note
This is true for the Gregorian calendar and disregards oddities of dates before 15 October 1582
Definition at line 448 of file time.hpp.
Referenced by leap_year(), month_days(), and year_days().
constexpr auto timer::DateTime::millisecond () const inline noexcept
Milliseconds.
Definition at line 374 of file time.hpp.
Referenced by timer::format_char().
constexpr auto timer::DateTime::minute () const inline noexcept
Minutes.
Definition at line 383 of file time.hpp.
Referenced by timer::format_char().
constexpr Month timer::DateTime::month () const inline noexcept
Month.
Definition at line 425 of file time.hpp.
Referenced by timer::format_char(), and timer::TimeParser::parse_date_desc().
constexpr int timer::DateTime::month_days (Month m) const inline noexcept
Number of days in the given month.
Definition at line 458 of file time.hpp.
Referenced by timer::format_char(), operator+=(), operator-=(), set_day(), and year_day().
static constexpr int timer::DateTime::month_days (int32_t year, Month m) inline static noexcept
Number of days in the given month.
Definition at line 465 of file time.hpp.
Referenced by DateTime(), timer::TimeParser::lex_date(), and month_days().
constexpr int timer::DateTime::month_int () const inline noexcept
Month (as an int)
Definition at line 429 of file time.hpp.
Referenced by timer::format_char().
constexpr bool timer::DateTime::operator!= (const DateTime & rhs) const inline noexcept
Definition at line 786 of file time.hpp.
template<class Rep , class Period > SUPER_CONSTEXPR DateTime timer::DateTime::operator+ (const std::chrono::duration< Rep, Period > & dur) const inline noexcept
Definition at line 648 of file time.hpp.
Referenced by timer::TimeParser::parse_day().
template<class Rep , class Period > DateTime& timer::DateTime::operator+= (const std::chrono::duration< Rep, Period > & dur) inline noexcept
Add a duration.
Definition at line 591 of file time.hpp.
Referenced by DateTime(), timer::TimeParser::next_weekday(), and timer::TimeParser::parse_time_point().
template<class Rep , class Period > SUPER_CONSTEXPR DateTime timer::DateTime::operator- (const std::chrono::duration< Rep, Period > & dur) const inline noexcept
Definition at line 715 of file time.hpp.
SUPER_CONSTEXPR Duration timer::DateTime::operator- (const DateTime & rhs) const inline noexcept
Definition at line 721 of file time.hpp.
Referenced by fun::PonyCountDown::json_success().
template<class Rep , class Period > DateTime& timer::DateTime::operator-= (const std::chrono::duration< Rep, Period > & dur) inline noexcept
Subtract a duration.
Template Parameters
Duration a chrono duration
Definition at line 659 of file time.hpp.
Referenced by timer::TimeParser::parse_time_point().
SUPER_CONSTEXPR bool timer::DateTime::operator< (const DateTime & rhs) const inline noexcept
Definition at line 727 of file time.hpp.
SUPER_CONSTEXPR bool timer::DateTime::operator<= (const DateTime & rhs) const inline noexcept
Definition at line 791 of file time.hpp.
constexpr bool timer::DateTime::operator== (const DateTime & rhs) const inline noexcept
Definition at line 775 of file time.hpp.
Referenced by operator!=().
SUPER_CONSTEXPR bool timer::DateTime::operator> (const DateTime & rhs) const inline noexcept
Definition at line 751 of file time.hpp.
Referenced by fun::PonyCountDown::json_success(), and operator<=().
SUPER_CONSTEXPR bool timer::DateTime::operator>= (const DateTime & rhs) const inline noexcept
Definition at line 796 of file time.hpp.
constexpr bool timer::DateTime::pm () const inline noexcept
Whether it's a.m. (12:00 am = midnight, 12:00pm = noon)
Definition at line 399 of file time.hpp.
static constexpr int32_t timer::DateTime::positive_year (int32_t year) inline static private noexcept
Definition at line 853 of file time.hpp.
Referenced by week_day().
constexpr auto timer::DateTime::second () const inline noexcept
Seconds.
Note
No leap seconds
Definition at line 379 of file time.hpp.
Referenced by timer::format_char().
SUPER_CONSTEXPR void timer::DateTime::set_date (int32_t year, Month month, days day) inline noexcept
Set the date without changing the time.
Definition at line 517 of file time.hpp.
Referenced by timer::TimeParser::lex_date(), operator+=(), operator-=(), and timer::TimeParser::parse_date_desc().
SUPER_CONSTEXPR void timer::DateTime::set_date (Month month, days day) inline noexcept
Set the date without changing the year or the time.
Definition at line 526 of file time.hpp.
SUPER_CONSTEXPR void timer::DateTime::set_day (int day) inline noexcept
Sets the day of the month.
Definition at line 551 of file time.hpp.
Referenced by set_date(), and set_month().
SUPER_CONSTEXPR void timer::DateTime::set_hour (uint8_t hour) inline noexcept
Sets the hour of the day [0,23].
Definition at line 558 of file time.hpp.
Referenced by set_time().
SUPER_CONSTEXPR void timer::DateTime::set_millisecond (uint8_t milliseconds) inline noexcept
Sets the milliseconds of the second [0,999].
Definition at line 580 of file time.hpp.
Referenced by set_time().
SUPER_CONSTEXPR void timer::DateTime::set_minute (uint8_t minute) inline noexcept
Sets the minute of the hour [0,59].
Definition at line 565 of file time.hpp.
Referenced by set_time().
SUPER_CONSTEXPR void timer::DateTime::set_month (Month month) inline noexcept
Sets the month.
Note
It might change the day if its greater than month_days(month)
Definition at line 543 of file time.hpp.
SUPER_CONSTEXPR void timer::DateTime::set_second (uint8_t second) inline noexcept
Sets the second of the minute [0,59].
Note
no leap seconds
Definition at line 573 of file time.hpp.
Referenced by set_time().
SUPER_CONSTEXPR void timer::DateTime::set_time (hours hour, minutes minute, seconds second = seconds(0), milliseconds millisecond = milliseconds(0)) inline noexcept
Set the time without changing the date.
Definition at line 505 of file time.hpp.
Referenced by timer::TimeParser::parse_time().
SUPER_CONSTEXPR void timer::DateTime::set_year (int32_t year) inline noexcept
Sets the year.
Definition at line 535 of file time.hpp.
Referenced by set_date().
template<class T1 , class T2 > static void timer::DateTime::subtract_helper (int nextunit, T1 & mask, T1 & ms, T2 & member) inline static private noexcept
Helper function for operator-=()
Definition at line 815 of file time.hpp.
SUPER_CONSTEXPR Time timer::DateTime::time_point () const inline noexcept
Build a time point from the DateTime.
Definition at line 339 of file time.hpp.
SUPER_CONSTEXPR int64_t timer::DateTime::unix () const inline noexcept
Return as a unix timestamp.
Definition at line 349 of file time.hpp.
Referenced by timer::format_char(), operator-(), and time_point().
SUPER_CONSTEXPR WeekDay timer::DateTime::week_day () const inline noexcept
Evaluates the week day.
Definition at line 486 of file time.hpp.
Referenced by timer::format_char(), and timer::TimeParser::next_weekday().
constexpr auto timer::DateTime::year () const inline noexcept
Year.
Definition at line 433 of file time.hpp.
Referenced by timer::format_char(), fun::Discord::on_handle(), and timer::TimeParser::parse_date_desc().
SUPER_CONSTEXPR int timer::DateTime::year_day () const inline noexcept
Day of the year [0,365].
Note
Zero based
Definition at line 408 of file time.hpp.
Referenced by timer::format_char(), fun::Discord::on_handle(), operator+=(), operator-=(), and unix().
static constexpr int timer::DateTime::year_days (int32_t year) inline static noexcept
Number of days in a year.
Definition at line 418 of file time.hpp.
Referenced by operator+=(), operator-=(), and unix().
Member Data Documentation
int8_t timer::DateTime::day_ private
Day of the month [1,31].
Definition at line 805 of file time.hpp.
Referenced by DateTime(), day(), operator+=(), operator-=(), operator<(), operator==(), operator>(), set_day(), set_month(), and week_day().
int8_t timer::DateTime::hour_ private
Hour [0,23].
Definition at line 806 of file time.hpp.
Referenced by am(), DateTime(), hour(), hour12(), operator+=(), operator-=(), operator<(), operator==(), operator>(), pm(), set_hour(), and unix().
int16_t timer::DateTime::milliseconds_ private
Milli seconds [0,10^3)
Definition at line 809 of file time.hpp.
Referenced by DateTime(), millisecond(), operator+=(), operator-(), operator-=(), operator<(), operator==(), operator>(), set_millisecond(), and time_point().
int8_t timer::DateTime::minute_ private
Minute [0,59].
Definition at line 807 of file time.hpp.
Referenced by DateTime(), minute(), operator+=(), operator-=(), operator<(), operator==(), operator>(), set_minute(), and unix().
Month timer::DateTime::month_ private
Month.
Definition at line 804 of file time.hpp.
Referenced by DateTime(), month(), month_int(), operator+=(), operator-=(), operator<(), operator==(), operator>(), set_date(), set_day(), set_month(), week_day(), and year_day().
int8_t timer::DateTime::second_ private
Second [0,59].
Todo:
(allow leap seconds?)
Definition at line 808 of file time.hpp.
Referenced by DateTime(), operator+=(), operator-=(), operator<(), operator==(), operator>(), second(), set_second(), and unix().
int32_t timer::DateTime::year_ private
Year.
Definition at line 803 of file time.hpp.
Referenced by DateTime(), leap_year(), month_days(), operator+=(), operator-=(), operator<(), operator==(), operator>(), set_year(), unix(), week_day(), and year().
The documentation for this class was generated from the following file:
src/time/time.hpp