MelanoBot: network::UdpIo Class Reference
network::UdpIo Class Reference
Class providing a simple interface for UDP connections.
#include <udp_io.hpp>
Public Member Functions
UdpIo ()=default
UdpIo (const UdpIo &)=delete
UdpIo (UdpIo &&)=delete
UdpIo & operator= (const UdpIo &)=delete
UdpIo & operator= (UdpIo &&)=delete
std::string::size_type max_datagram_size () const
Maximum size of a datagram in bytes.
void max_datagram_size (std::string::size_type size)
Sets the maximum size of a datagram in bytes.
bool connect (const Server &server)
Connects to the given server.
void disconnect ()
Disconnects (if connected)
bool connected () const
Checks if the socket is connected.
bool write (std::string datagram)
Synchronous write.
std::string read ()
Synchronous read.
void run_input ()
Blocks while connected and handles asynchronous reads.
network::Server remote_endpoint () const
Endpoint used to send datagram to.
network::Server local_endpoint () const
Local connection endpoint.
Public Attributes
std::function< void(const
std::string &message)> on_error
Called when a network error arises.
std::function< void()> on_failure
Called when an error will make it impossible to continue processing the connection.
std::function< void(const
std::string &datagram)> on_async_receive
Called after a successful asynchronous read.
Private Member Functions
void schedule_read ()
Schedules an asyncrhonous read.
void on_receive (const boost::system::error_code &error, std::size_t nbytes)
Async read callback.
Private Attributes
boost::asio::io_service io_service
IO service.
boost::asio::ip::udp::resolver resolver {io_service}
Query resolver.
boost::asio::ip::udp::socket socket {io_service}
Socket.
std::string::size_type max_bytes = 1024
Max size of a datagram.
std::string receive_buffer
Buffer for async reads.
Detailed Description
Class providing a simple interface for UDP connections.
Definition at line 33 of file udp_io.hpp.
Constructor & Destructor Documentation
network::UdpIo::UdpIo () default
network::UdpIo::UdpIo (const UdpIo &) delete
network::UdpIo::UdpIo (UdpIo &&) delete
Member Function Documentation
bool network::UdpIo::connect (const Server & server) inline
Connects to the given server.
Returns
true on success
Definition at line 77 of file udp_io.hpp.
Referenced by xonotic::XonoticConnection::connect().
bool network::UdpIo::connected () const inline
Checks if the socket is connected.
Definition at line 112 of file udp_io.hpp.
Referenced by xonotic::XonoticConnection::connect(), disconnect(), xonotic::XonoticConnection::disconnect(), local_endpoint(), and remote_endpoint().
void network::UdpIo::disconnect () inline
Disconnects (if connected)
Definition at line 97 of file udp_io.hpp.
Referenced by xonotic::XonoticConnection::disconnect().
network::Server network::UdpIo::local_endpoint () const inline
Local connection endpoint.
Definition at line 183 of file udp_io.hpp.
Referenced by xonotic::XonoticConnection::update_connection().
std::string::size_type network::UdpIo::max_datagram_size () const inline
Maximum size of a datagram in bytes.
Definition at line 60 of file udp_io.hpp.
void network::UdpIo::max_datagram_size (std::string::size_type size) inline
Sets the maximum size of a datagram in bytes.
Definition at line 68 of file udp_io.hpp.
Referenced by xonotic::XonoticConnection::XonoticConnection().
void network::UdpIo::on_receive (const boost::system::error_code & error, std::size_t nbytes) inline private
Async read callback.
Definition at line 214 of file udp_io.hpp.
Referenced by schedule_read().
UdpIo& network::UdpIo::operator= (const UdpIo &) delete
UdpIo& network::UdpIo::operator= (UdpIo &&) delete
std::string network::UdpIo::read () inline
Synchronous read.
Reads a datagram (max max_bytes) and returns it as a string
Definition at line 140 of file udp_io.hpp.
Referenced by xonotic::XonoticConnection::cleanup_connection().
network::Server network::UdpIo::remote_endpoint () const inline
Endpoint used to send datagram to.
Definition at line 172 of file udp_io.hpp.
void network::UdpIo::run_input () inline
Blocks while connected and handles asynchronous reads.
Definition at line 157 of file udp_io.hpp.
Referenced by xonotic::XonoticConnection::connect().
void network::UdpIo::schedule_read () inline private
Schedules an asyncrhonous read.
Definition at line 201 of file udp_io.hpp.
Referenced by on_receive(), and run_input().
bool network::UdpIo::write (std::string datagram) inline
Synchronous write.
Writes datagram to the udp socket
Returns
true on success
Todo:
maybe truncate to max_bytes
Definition at line 124 of file udp_io.hpp.
Referenced by xonotic::XonoticConnection::write().
Member Data Documentation
boost::asio::io_service network::UdpIo::io_service private
IO service.
Definition at line 192 of file udp_io.hpp.
std::string::size_type network::UdpIo::max_bytes = 1024 private
Max size of a datagram.
Definition at line 195 of file udp_io.hpp.
Referenced by max_datagram_size(), read(), and schedule_read().
std::function<void(const std::string& datagram)> network::UdpIo::on_async_receive
Called after a successful asynchronous read.
Definition at line 49 of file udp_io.hpp.
Referenced by on_receive(), and xonotic::XonoticConnection::XonoticConnection().
std::function<void(const std::string& message)> network::UdpIo::on_error
Called when a network error arises.
Definition at line 39 of file udp_io.hpp.
Referenced by connect(), disconnect(), on_receive(), read(), run_input(), write(), and xonotic::XonoticConnection::XonoticConnection().
std::function<void()> network::UdpIo::on_failure
Called when an error will make it impossible to continue processing the connection.
Note
Always called after a call to on_error
Definition at line 45 of file udp_io.hpp.
Referenced by connect(), run_input(), and xonotic::XonoticConnection::XonoticConnection().
std::string network::UdpIo::receive_buffer private
Buffer for async reads.
Definition at line 196 of file udp_io.hpp.
Referenced by on_receive(), and schedule_read().
boost::asio::ip::udp::resolver network::UdpIo::resolver {io_service} private
Query resolver.
Definition at line 193 of file udp_io.hpp.
boost::asio::ip::udp::socket network::UdpIo::socket {io_service} private
Socket.
Definition at line 194 of file udp_io.hpp.
The documentation for this class was generated from the following file:
src/network/udp_io.hpp