MelanoBot: handler::HandlerFactory Class Reference
handler::HandlerFactory Class Reference
Handler Factory.
#include <handler.hpp>
Classes
struct RegisterHandler
Dummy class for auto-registration.
Public Types
typedef std::function< Handler
*(const Settings &, Melanobot *)> CreateFunction
Function object type used to create instances.
Public Member Functions
Handler * build (const std::string &handler_name, const Settings &settings, Melanobot *bot) const
Build a handler from its name and settings.
Static Public Member Functions
static HandlerFactory & instance ()
Private Member Functions
HandlerFactory ()
HandlerFactory (const HandlerFactory &)=delete
Private Attributes
std::unordered_map
< std::string, CreateFunction > factory
Detailed Description
Handler Factory.
Definition at line 231 of file handler.hpp.
Member Typedef Documentation
typedef std::function<Handler*(const Settings&,Melanobot*)> handler::HandlerFactory::CreateFunction
Function object type used to create instances.
Definition at line 237 of file handler.hpp.
Constructor & Destructor Documentation
handler::HandlerFactory::HandlerFactory () inline private
Definition at line 285 of file handler.hpp.
handler::HandlerFactory::HandlerFactory (const HandlerFactory &) private delete
Member Function Documentation
Handler* handler::HandlerFactory::build (const std::string & handler_name, const Settings & settings, Melanobot * bot) const inline
Build a handler from its name and settings.
Returns
nullptr if it could not be created
Definition at line 265 of file handler.hpp.
Referenced by Melanobot::Melanobot(), and handler::SimpleGroup::SimpleGroup().
static HandlerFactory& handler::HandlerFactory::instance () inline static
Definition at line 255 of file handler.hpp.
Referenced by Melanobot::Melanobot(), and handler::SimpleGroup::SimpleGroup().
Member Data Documentation
std::unordered_map<std::string,CreateFunction> handler::HandlerFactory::factory private
Definition at line 288 of file handler.hpp.
Referenced by build().
The documentation for this class was generated from the following file:
src/handler/handler.hpp