MelanoBot: timer::basic_timer< Clock > Class Template Reference
timer::basic_timer< Clock > Class Template Reference
A timer which performs a task after some time on a separate thread.
#include <time.hpp>
Public Types
using clock_type = Clock
Clock.
using duration_type = typename Clock::duration
Duration.
using function_type = std::function< void()>
Callback type.
Public Member Functions
basic_timer (function_type action={}, duration_type timeout=duration_type::zero(), bool repeating=true)
basic_timer (const basic_timer &rhs)
basic_timer & operator= (const basic_timer &rhs)
basic_timer (basic_timer &&rhs)
basic_timer & operator= (basic_timer &&rhs)
~basic_timer ()
bool start ()
Start the timer with the already-set duration.
bool running () const
Whether the timer has been started and is still running.
bool reset (duration_type timeout)
Stop the timer and set a new timeout.
void stop ()
Stop the timer.
Private Member Functions
void run ()
Runs the timer.
Private Attributes
duration_type timeout
Timer duration.
std::atomic< bool > repeating {false}
Whether it should start over once finished.
std::atomic< bool > active {false}
Whether it's currently running.
std::condition_variable condition
Wait condition.
function_type action
Executed on timeout.
std::thread thread
Thread where the callback is executed.
Detailed Description
template<class Clock>
class timer::basic_timer< Clock >
A timer which performs a task after some time on a separate thread.
Template Parameters
Clock A clock type
Definition at line 43 of file time.hpp.
Member Typedef Documentation
template<class Clock > using timer::basic_timer< Clock >::clock_type = Clock
Clock.
Definition at line 46 of file time.hpp.
template<class Clock > using timer::basic_timer< Clock >::duration_type = typename Clock::duration
Duration.
Definition at line 47 of file time.hpp.
template<class Clock > using timer::basic_timer< Clock >::function_type = std::function<void()>
Callback type.
Definition at line 48 of file time.hpp.
Constructor & Destructor Documentation
template<class Clock > timer::basic_timer< Clock >::basic_timer (function_type action = {}, duration_type timeout = duration_type::zero(), bool repeating = true) inline explicit
Definition at line 50 of file time.hpp.
Referenced by xonotic::XonoticConnection::XonoticConnection().
template<class Clock > timer::basic_timer< Clock >::basic_timer (const basic_timer< Clock > & rhs) inline
Definition at line 60 of file time.hpp.
template<class Clock > timer::basic_timer< Clock >::basic_timer (basic_timer< Clock > && rhs) inline
Definition at line 72 of file time.hpp.
template<class Clock > timer::basic_timer< Clock >::~basic_timer () inline
Definition at line 89 of file time.hpp.
Member Function Documentation
template<class Clock > basic_timer& timer::basic_timer< Clock >::operator= (const basic_timer< Clock > & rhs) inline
Definition at line 63 of file time.hpp.
template<class Clock > basic_timer& timer::basic_timer< Clock >::operator= (basic_timer< Clock > && rhs) inline
Definition at line 80 of file time.hpp.
Referenced by xonotic::XonoticConnection::XonoticConnection().
template<class Clock > bool timer::basic_timer< Clock >::reset (duration_type timeout) inline
Stop the timer and set a new timeout.
Returns
true on success
Definition at line 118 of file time.hpp.
template<class Clock > void timer::basic_timer< Clock >::run () inline private
Runs the timer.
Definition at line 152 of file time.hpp.
Referenced by timer::basic_timer< Clock >::start().
template<class Clock > bool timer::basic_timer< Clock >::running () const inline
Whether the timer has been started and is still running.
Definition at line 109 of file time.hpp.
Referenced by timer::basic_timer< Clock >::start(), timer::basic_timer< Clock >::stop(), and xonotic::XonoticConnection::update_connection().
template<class Clock > bool timer::basic_timer< Clock >::start () inline
Start the timer with the already-set duration.
Note
If timeout is zero, repeating will be ignored
Returns
true on success
Definition at line 96 of file time.hpp.
Referenced by timer::basic_timer< Clock >::reset(), and xonotic::XonoticConnection::update_connection().
template<class Clock > void timer::basic_timer< Clock >::stop () inline
Stop the timer.
Definition at line 128 of file time.hpp.
Referenced by xonotic::XonoticConnection::disconnect(), timer::basic_timer< Clock >::reset(), and timer::basic_timer< Clock >::~basic_timer().
Member Data Documentation
template<class Clock > function_type timer::basic_timer< Clock >::action private
Executed on timeout.
Definition at line 146 of file time.hpp.
Referenced by timer::basic_timer< Clock >::basic_timer(), timer::basic_timer< Clock >::operator=(), timer::basic_timer< Clock >::run(), and timer::basic_timer< Clock >::start().
template<class Clock > std::atomic<bool> timer::basic_timer< Clock >::active {false} private
Whether it's currently running.
Definition at line 144 of file time.hpp.
Referenced by timer::basic_timer< Clock >::run(), and timer::basic_timer< Clock >::stop().
template<class Clock > std::condition_variable timer::basic_timer< Clock >::condition private
Wait condition.
Definition at line 145 of file time.hpp.
Referenced by timer::basic_timer< Clock >::run(), and timer::basic_timer< Clock >::stop().
template<class Clock > std::atomic<bool> timer::basic_timer< Clock >::repeating {false} private
Whether it should start over once finished.
Definition at line 143 of file time.hpp.
Referenced by timer::basic_timer< Clock >::basic_timer(), timer::basic_timer< Clock >::operator=(), and timer::basic_timer< Clock >::run().
template<class Clock > std::thread timer::basic_timer< Clock >::thread private
Thread where the callback is executed.
Definition at line 147 of file time.hpp.
template<class Clock > duration_type timer::basic_timer< Clock >::timeout private
Timer duration.
Definition at line 142 of file time.hpp.
Referenced by timer::basic_timer< Clock >::basic_timer(), timer::basic_timer< Clock >::operator=(), timer::basic_timer< Clock >::run(), and timer::basic_timer< Clock >::start().
The documentation for this class was generated from the following file:
src/time/time.hpp