MelanoBot: string::FormatFlags Class Reference
string::FormatFlags Class Reference
String formatting flags.
#include <string.hpp>
Public Types
enum FormatFlagsEnum { NO_FORMAT = 0, BOLD = 1, UNDERLINE = 2 }
Public Member Functions
constexpr FormatFlags (FormatFlagsEnum flags) noexcept
constexpr FormatFlags () noexcept=default
constexpr operator bool () const noexcept
constexpr FormatFlags operator| (const FormatFlags &o) const noexcept
constexpr FormatFlags operator& (const FormatFlags &o) const noexcept
constexpr FormatFlags operator& (int o) const noexcept
constexpr FormatFlags operator^ (const FormatFlags &o) const noexcept
constexpr FormatFlags operator~ () const noexcept
constexpr bool operator== (const FormatFlags &o) const noexcept
FormatFlags & operator|= (const FormatFlags &o) noexcept
FormatFlags & operator&= (const FormatFlags &o) noexcept
FormatFlags & operator&= (int o) noexcept
FormatFlags & operator^= (const FormatFlags &o) noexcept
Private Member Functions
constexpr FormatFlags (int flags) noexcept
Private Attributes
int flags = 0
Friends
constexpr FormatFlags operator| (FormatFlags::FormatFlagsEnum a, FormatFlags::FormatFlagsEnum b) noexcept
Detailed Description
String formatting flags.
Definition at line 99 of file string.hpp.
Member Enumeration Documentation
enum string::FormatFlags::FormatFlagsEnum
Enumerator
NO_FORMAT
BOLD
UNDERLINE
Definition at line 102 of file string.hpp.
Constructor & Destructor Documentation
constexpr string::FormatFlags::FormatFlags (FormatFlagsEnum flags) inline noexcept
Definition at line 107 of file string.hpp.
constexpr string::FormatFlags::FormatFlags () default noexcept
constexpr string::FormatFlags::FormatFlags (int flags) inline private noexcept
Definition at line 173 of file string.hpp.
Member Function Documentation
constexpr string::FormatFlags::operator bool () const inline explicit noexcept
Definition at line 111 of file string.hpp.
constexpr FormatFlags string::FormatFlags::operator& (const FormatFlags & o) const inline noexcept
Definition at line 118 of file string.hpp.
constexpr FormatFlags string::FormatFlags::operator& (int o) const inline noexcept
Definition at line 122 of file string.hpp.
Referenced by irc::FormatterIrc::decode(), irc::FormatterIrc::format_flags(), string::FormatterAnsi::format_flags(), and string::FormatterConfig::format_flags().
FormatFlags& string::FormatFlags::operator&= (const FormatFlags & o) inline noexcept
Definition at line 148 of file string.hpp.
FormatFlags& string::FormatFlags::operator&= (int o) inline noexcept
Definition at line 154 of file string.hpp.
Referenced by string::FormatterAnsi::decode().
constexpr bool string::FormatFlags::operator== (const FormatFlags & o) const inline noexcept
Definition at line 137 of file string.hpp.
Referenced by string::FormatterAnsi::decode(), and irc::FormatterIrc::format_flags().
constexpr FormatFlags string::FormatFlags::operator^ (const FormatFlags & o) const inline noexcept
Definition at line 127 of file string.hpp.
FormatFlags& string::FormatFlags::operator^= (const FormatFlags & o) inline noexcept
Definition at line 160 of file string.hpp.
constexpr FormatFlags string::FormatFlags::operator| (const FormatFlags & o) const inline noexcept
Definition at line 113 of file string.hpp.
FormatFlags& string::FormatFlags::operator|= (const FormatFlags & o) inline noexcept
Definition at line 142 of file string.hpp.
Referenced by irc::FormatterIrc::decode(), string::FormatterAnsi::decode(), and string::FormatterConfig::decode().
constexpr FormatFlags string::FormatFlags::operator~ () const inline noexcept
Definition at line 132 of file string.hpp.
Friends And Related Function Documentation
constexpr FormatFlags operator| (FormatFlags::FormatFlagsEnum a, FormatFlags::FormatFlagsEnum b) friend
Definition at line 166 of file string.hpp.
Referenced by handler::Handler::get_parent(), Melanomodule::register_connection(), Melanomodule::register_formatter(), Melanomodule::register_handler(), Melanomodule::register_service(), and string::simple_wildcard().
Member Data Documentation
int string::FormatFlags::flags = 0 private
Definition at line 175 of file string.hpp.
Referenced by FormatFlags(), operator bool(), operator&(), operator&=(), operator==(), operator^(), operator^=(), operator|(), operator|=(), and operator~().
The documentation for this class was generated from the following file:
src/string/string.hpp