MelanoBot: xonotic::ParseEventlog Class Reference
xonotic::ParseEventlog Class Reference abstract
Base class for handlers parsing the Xonotic eventlog.
#include <status.hpp>
Public Member Functions
ParseEventlog (std::string regex, const Settings &settings, HandlerContainer *parent)
bool can_handle (const network::Message &msg) const override
Checks if a message can be handled.
Public Member Functions inherited from handler::Handler
Handler (const Settings &settings, HandlerContainer *parent)
Handler (const Handler &)=delete
Handler & operator= (const Handler &)=delete
virtual ~Handler ()
Melanobot * melanobot () const final
Get the top-level bot for this HandlerContainer.
virtual bool handle (network::Message &msg)
Attempt to handle the message.
virtual void initialize ()
Called at startup in case it needs to perform some initialization.
virtual void finalize ()
Called when the connection ends.
virtual std::string get_property (const std::string &name) const
Get a property by name.
void populate_properties (const std::vector< std::string > &properties, PropertyTree &output) const override
Simply appends globally the given property.
Public Member Functions inherited from handler::HandlerContainer
virtual ~HandlerContainer ()
Protected Member Functions
bool on_handle (network::Message &msg) override
Required for concrete handlers, performs the handler actions.
virtual bool on_handle (network::Message &msg, const std::smatch &match)=0
Protected Member Functions inherited from handler::Handler
virtual std::string reply_channel (const network::Message &msg) const
Returns the preferred output channel for the given message.
virtual void reply_to (const network::Message &input, network::OutputMessage output) const
Send a reply to a message.
void reply_to (const network::Message &msg, const string::FormattedString &text) const
void reply_to (const network::Message &msg, const std::string &text) const
template<class HandlerT >
HandlerT * get_parent () const
Find the parent handler with the given type.
Private Attributes
std::regex regex
Additional Inherited Members
Protected Attributes inherited from handler::Handler
int priority {0}
Message priority.
Melanobot * bot {nullptr}
Pointer to the main bot.
Handler * parent_handler {nullptr}
Pointer to a handler containing this one.
Detailed Description
Base class for handlers parsing the Xonotic eventlog.
It defines a new on_handle which accepts a regex_result
Definition at line 177 of file status.hpp.
Constructor & Destructor Documentation
xonotic::ParseEventlog::ParseEventlog (std::string regex, const Settings & settings, HandlerContainer * parent) inline
Definition at line 180 of file status.hpp.
Referenced by xonotic::ShowVoteCall::ShowVoteCall(), xonotic::ShowVoteDo::ShowVoteDo(), xonotic::ShowVoteLogin::ShowVoteLogin(), xonotic::ShowVoteResult::ShowVoteResult(), xonotic::ShowVoteStop::ShowVoteStop(), and xonotic::XonoticMatchScore::XonoticMatchScore().
Member Function Documentation
bool xonotic::ParseEventlog::can_handle (const network::Message & msg) const inline override virtual
Checks if a message can be handled.
Precondition
msg.source not null
Returns
true if the message can be handled by the handler
Reimplemented from handler::Handler.
Reimplemented in xonotic::XonoticMatchScore.
Definition at line 185 of file status.hpp.
bool xonotic::ParseEventlog::on_handle (network::Message & msg) inline override protected virtual
Required for concrete handlers, performs the handler actions.
Returns
true if the message has been handled and needs no further processing
Implements handler::Handler.
Definition at line 191 of file status.hpp.
virtual bool xonotic::ParseEventlog::on_handle (network::Message & msg, const std::smatch & match) protected pure virtual
Implemented in xonotic::XonoticMatchScore, xonotic::ShowVoteDo, xonotic::ShowVoteLogin, xonotic::ShowVoteStop, xonotic::ShowVoteResult, and xonotic::ShowVoteCall.
Referenced by on_handle().
Member Data Documentation
std::regex xonotic::ParseEventlog::regex private
Definition at line 204 of file status.hpp.
The documentation for this class was generated from the following file:
modules/xonotic/handler/status.hpp