MelanoBot: string::FormattedStream Class Reference
string::FormattedStream Class Reference
Simple way to create FormattedString objects.
#include <string.hpp>
Public Member Functions
FormattedStream (const std::string &input_formatter)
FormattedStream ()
operator FormattedString () const
FormattedString str () const
const FormattedStream & operator<< (const std::string &text) const
const FormattedStream & operator<< (const char *text) const
const FormattedStream & operator<< (const color::Color12 &color) const
const FormattedStream & operator<< (const FormatFlags &format_flags) const
const FormattedStream & operator<< (FormatFlags::FormatFlagsEnum format_flags) const
const FormattedStream & operator<< (ClearFormatting) const
const FormattedStream & operator<< (char c) const
const FormattedStream & operator<< (const FormattedString &string) const
template<class T >
const FormattedStream & operator<< (const T &obj) const
std::string encode (const std::string &output_formatter) const
std::string encode (Formatter *output_formatter) const
bool empty () const
Private Attributes
FormattedString buffer
Formatter * formatter
Detailed Description
Simple way to create FormattedString objects.
Definition at line 561 of file string.hpp.
Constructor & Destructor Documentation
string::FormattedStream::FormattedStream (const std::string & input_formatter) inline explicit
Definition at line 564 of file string.hpp.
Referenced by handler::SearchWebSearx::json_success(), and handler::Handler::reply_to().
string::FormattedStream::FormattedStream () inline
Definition at line 566 of file string.hpp.
Referenced by handler::Help::on_handle(), handler::BridgeChat::on_handle(), handler::ListInsert::on_handle(), and handler::ListRemove::on_handle().
Member Function Documentation
bool string::FormattedStream::empty () const inline
Definition at line 636 of file string.hpp.
Referenced by handler::Help::on_handle().
std::string string::FormattedStream::encode (const std::string & output_formatter) const inline
Definition at line 626 of file string.hpp.
std::string string::FormattedStream::encode (Formatter * output_formatter) const inline
Definition at line 631 of file string.hpp.
string::FormattedStream::operator FormattedString () const inline
Definition at line 569 of file string.hpp.
const FormattedStream& string::FormattedStream::operator<< (const std::string & text) const inline
Definition at line 572 of file string.hpp.
const FormattedStream& string::FormattedStream::operator<< (const char * text) const inline
Definition at line 583 of file string.hpp.
const FormattedStream& string::FormattedStream::operator<< (const color::Color12 & color) const inline
Definition at line 587 of file string.hpp.
const FormattedStream& string::FormattedStream::operator<< (const FormatFlags & format_flags) const inline
Definition at line 592 of file string.hpp.
const FormattedStream& string::FormattedStream::operator<< (FormatFlags::FormatFlagsEnum format_flags) const inline
Definition at line 597 of file string.hpp.
const FormattedStream& string::FormattedStream::operator<< (ClearFormatting) const inline
Definition at line 602 of file string.hpp.
const FormattedStream& string::FormattedStream::operator<< (char c) const inline
Definition at line 607 of file string.hpp.
const FormattedStream& string::FormattedStream::operator<< (const FormattedString & string) const inline
Definition at line 612 of file string.hpp.
template<class T > const FormattedStream& string::FormattedStream::operator<< (const T & obj) const inline
Definition at line 619 of file string.hpp.
FormattedString string::FormattedStream::str () const inline
Definition at line 570 of file string.hpp.
Referenced by handler::SearchWebSearx::json_success(), handler::Help::on_handle(), handler::BridgeChat::on_handle(), operator FormattedString(), irc::handler::CtcpBase::reply_to(), handler::Handler::reply_to(), and Log::~Log().
Member Data Documentation
FormattedString string::FormattedStream::buffer mutable private
Definition at line 639 of file string.hpp.
Referenced by empty(), encode(), operator<<(), and str().
Formatter* string::FormattedStream::formatter private
Definition at line 640 of file string.hpp.
Referenced by FormattedStream(), and operator<<().
The documentation for this class was generated from the following file:
src/string/string.hpp