MelanoBot: network::ConnectionFactory Class Reference
network::ConnectionFactory Class Reference
Creates connections from settings.
#include <connection.hpp>
Classes
class RegisterConnection
Auto-registration helper.
Public Types
typedef std::function
< Connection *(Melanobot *bot,
const Settings &)> Contructor
Public Member Functions
void register_connection (const std::string &protocol_name, const Contructor &function)
Registers a connection type.
Connection * create (Melanobot *bot, const Settings &settings)
Creates a connection from its settings.
Static Public Member Functions
static ConnectionFactory & instance ()
Singleton instance.
Private Member Functions
ConnectionFactory ()
ConnectionFactory (const ConnectionFactory &)=delete
Private Attributes
std::unordered_map
< std::string, Contructor > factory
Detailed Description
Creates connections from settings.
Definition at line 324 of file connection.hpp.
Member Typedef Documentation
typedef std::function<Connection*(Melanobot* bot, const Settings&)> network::ConnectionFactory::Contructor
Definition at line 327 of file connection.hpp.
Constructor & Destructor Documentation
network::ConnectionFactory::ConnectionFactory () inline private
Definition at line 376 of file connection.hpp.
network::ConnectionFactory::ConnectionFactory (const ConnectionFactory &) private delete
Member Function Documentation
Connection* network::ConnectionFactory::create (Melanobot * bot, const Settings & settings) inline
Creates a connection from its settings.
Definition at line 363 of file connection.hpp.
Referenced by Melanobot::Melanobot().
static ConnectionFactory& network::ConnectionFactory::instance () inline static
Singleton instance.
Definition at line 343 of file connection.hpp.
Referenced by Melanobot::Melanobot(), and network::ConnectionFactory::RegisterConnection::RegisterConnection().
void network::ConnectionFactory::register_connection (const std::string & protocol_name, const Contructor & function) inline
Registers a connection type.
Exceptions
CriticalException If a protocol is defined twice
Definition at line 353 of file connection.hpp.
Referenced by network::ConnectionFactory::RegisterConnection::RegisterConnection().
Member Data Documentation
std::unordered_map<std::string,Contructor> network::ConnectionFactory::factory private
Definition at line 379 of file connection.hpp.
Referenced by create(), and register_connection().
The documentation for this class was generated from the following file:
src/network/connection.hpp