MelanoBot: ConfigurationError Class Reference
ConfigurationError Class Reference
Class representing an error occurring during configuration.
#include <settings.hpp>
Public Member Functions
ConfigurationError (const std::string &msg="Invalid configuration parameters")
Detailed Description
Class representing an error occurring during configuration.
Definition at line 119 of file settings.hpp.
Constructor & Destructor Documentation
ConfigurationError::ConfigurationError (const std::string & msg = "Invalid configuration parameters") inline
Definition at line 122 of file settings.hpp.
Referenced by handler::AdminGroup::AdminGroup(), handler::Bridge::Bridge(), ConfigurationError(), irc::handler::CtcpBase::CtcpBase(), handler::EventMessageBase::EventMessageBase(), handler::FilterGroup::FilterGroup(), handler::Handler::Handler(), handler::BridgeAttach::initialize(), handler::BridgeAttachChannel::initialize(), handler::ListClear::ListClear(), handler::ListInsert::ListInsert(), handler::ListRemove::ListRemove(), xonotic::RconCommand::RconCommand(), handler::Reply::Reply(), network::require_service(), and handler::SearchVideoYoutube::SearchVideoYoutube().
The documentation for this class was generated from the following file:
src/settings.hpp