MelanoBot: Log Class Reference
Log Class Reference
Simple log stream-like interface.
#include <logger.hpp>
Public Member Functions
Log (std::string type, char direction, int verbosity=2)
Log (const std::string &type, char direction, const std::string &message, int verbosity=2)
Log (const Log &)=delete
Log (Log &&)=delete
Log & operator= (const Log &)=delete
Log & operator= (Log &&)=delete
~Log ()
template<class T >
Log & operator<< (const T &t)
Public Attributes
std::string type
char direction
int verbosity
string::FormattedString stream
Detailed Description
Simple log stream-like interface.
Definition at line 128 of file logger.hpp.
Constructor & Destructor Documentation
Log::Log (std::string type, char direction, int verbosity = 2) inline
Definition at line 131 of file logger.hpp.
Referenced by handler::Bridge::attach(), handler::Bridge::attach_channel(), xonotic::XonoticConnection::command(), ErrorLog::ErrorLog(), xonotic::XonoticConnection::handle_message(), network::ServiceRegistry::initialize(), Log(), main(), StdinConnection::on_read_line(), network::http::HttpService::query(), xonotic::XonoticConnection::read(), xonotic::XonoticConnection::request_challenge(), StdinConnection::say(), and xonotic::XonoticConnection::update_user().
Log::Log (const std::string & type, char direction, const std::string & message, int verbosity = 2) inline
Definition at line 135 of file logger.hpp.
Log::Log (const Log &) delete
Log::Log (Log &&) delete
Log::~Log () inline
Definition at line 145 of file logger.hpp.
Member Function Documentation
template<class T > Log& Log::operator<< (const T & t) inline
Definition at line 152 of file logger.hpp.
Log& Log::operator= (const Log &) delete
Log& Log::operator= (Log &&) delete
Member Data Documentation
char Log::direction
Definition at line 160 of file logger.hpp.
Referenced by Log(), and ~Log().
string::FormattedString Log::stream
Definition at line 162 of file logger.hpp.
Referenced by ErrorLog::ErrorLog(), Log(), operator<<(), and ~Log().
std::string Log::type
Definition at line 159 of file logger.hpp.
Referenced by Log(), and ~Log().
int Log::verbosity
Definition at line 161 of file logger.hpp.
Referenced by Log(), and ~Log().
The documentation for this class was generated from the following file:
src/string/logger.hpp