MelanoBot: handler::Handler Class Reference
handler::Handler Class Reference abstract
Message handler abstract base class.
#include <handler.hpp>
Public Member Functions
Handler (const Settings &settings, HandlerContainer *parent)
Handler (const Handler &)=delete
Handler & operator= (const Handler &)=delete
virtual ~Handler ()
Melanobot * melanobot () const final
Get the top-level bot for this HandlerContainer.
virtual bool handle (network::Message &msg)
Attempt to handle the message.
virtual bool can_handle (const network::Message &msg) const
Checks if a message can be handled.
virtual void initialize ()
Called at startup in case it needs to perform some initialization.
virtual void finalize ()
Called when the connection ends.
virtual std::string get_property (const std::string &name) const
Get a property by name.
void populate_properties (const std::vector< std::string > &properties, PropertyTree &output) const override
Simply appends globally the given property.
Public Member Functions inherited from handler::HandlerContainer
virtual ~HandlerContainer ()
Protected Member Functions
virtual bool on_handle (network::Message &msg)=0
Required for concrete handlers, performs the handler actions.
virtual std::string reply_channel (const network::Message &msg) const
Returns the preferred output channel for the given message.
virtual void reply_to (const network::Message &input, network::OutputMessage output) const
Send a reply to a message.
void reply_to (const network::Message &msg, const string::FormattedString &text) const
void reply_to (const network::Message &msg, const std::string &text) const
template<class HandlerT >
HandlerT * get_parent () const
Find the parent handler with the given type.
Protected Attributes
int priority {0}
Message priority.
Melanobot * bot {nullptr}
Pointer to the main bot.
Handler * parent_handler {nullptr}
Pointer to a handler containing this one.
Detailed Description
Message handler abstract base class.
To create concrete handlers, inherit this class and specialize the virtual methods (see their own documentation).
For simple cases, inherit SimpleAction and specialize on_handle().
To make a handler visible to HandlerFactory, use Melanomodule::register_handler.
The constructor of a handler class must have the same signature as the one used here to work properly.
Definition at line 49 of file handler.hpp.
Constructor & Destructor Documentation
handler::Handler::Handler (const Settings & settings, HandlerContainer * parent) inline
Definition at line 52 of file handler.hpp.
Referenced by irc::handler::AcceptInvite::AcceptInvite(), handler::BridgeChat::BridgeChat(), handler::Chanhax::Chanhax(), xonotic::ConnectionEvents::ConnectionEvents(), irc::handler::CtcpBase::CtcpBase(), handler::EventMessageBase::EventMessageBase(), handler::FilterGroup::FilterGroup(), irc::handler::IrcKickRejoin::IrcKickRejoin(), xonotic::ParseEventlog::ParseEventlog(), irc::handler::QGetWhois::QGetWhois(), irc::handler::QSendWhois::QSendWhois(), handler::Reply::Reply(), handler::SimpleAction::SimpleAction(), irc::handler::Whois330::Whois330(), xonotic::XonoticJoinPart::XonoticJoinPart(), and xonotic::XonoticMatchStart::XonoticMatchStart().
handler::Handler::Handler (const Handler &) delete
virtual handler::Handler::~Handler () inline virtual
Definition at line 62 of file handler.hpp.
Member Function Documentation
virtual bool handler::Handler::can_handle (const network::Message & msg) const inline virtual
Checks if a message can be handled.
Precondition
msg.source not null
Returns
true if the message can be handled by the handler
Reimplemented in xonotic::XonoticMatchScore, handler::Reply, handler::SimpleAction, handler::Chanhax, fun::AnswerQuestions, xonotic::ParseEventlog, irc::handler::WhoisCheckMe, xonotic::XonoticMatchStart, handler::FilterGroup, handler::EventMessageBase, irc::handler::AcceptInvite, xonotic::XonoticJoinPart, irc::handler::QGetWhois, xonotic::ConnectionEvents, irc::handler::QSendWhois, handler::BridgeChat, irc::handler::CtcpBase, handler::SimpleGroup, irc::handler::IrcKickRejoin, and irc::handler::Whois330.
Definition at line 84 of file handler.hpp.
Referenced by handle().
virtual void handler::Handler::finalize () inline virtual
Called when the connection ends.
Todo:
is this needed?
Reimplemented in handler::SimpleGroup.
Definition at line 97 of file handler.hpp.
Referenced by handler::SimpleGroup::finalize(), and Melanobot::run().
template<class HandlerT > HandlerT* handler::Handler::get_parent () const inline protected
Find the parent handler with the given type.
Template Parameters
HandlerT Handler type
Walks up the handler tree to find a parent with the given type
Returns
The found parent or nullptr if not found
Definition at line 179 of file handler.hpp.
Referenced by handler::BridgeAttach::initialize(), and handler::BridgeAttachChannel::initialize().
virtual std::string handler::Handler::get_property (const std::string & name) const inline virtual
Get a property by name.
Note
If you inherit a Handler class, it is recommended that you override this for properties of that class but still call the parent version.
The Help handler uses the property "name" to determine if a handler has to be displayed, and uses "synopsis" and "help" to display information
Reimplemented in handler::Action, handler::SimpleAction, handler::Chanhax, handler::AbstractList, handler::AdminGroup, irc::handler::CtcpBase, and handler::SimpleGroup.
Definition at line 108 of file handler.hpp.
Referenced by irc::handler::CtcpBase::get_property(), handler::Chanhax::get_property(), handler::SimpleAction::get_property(), handler::SimpleGroup::populate_properties(), Melanobot::populate_properties(), and populate_properties().
virtual bool handler::Handler::handle (network::Message & msg) inline virtual
Attempt to handle the message.
Precondition
msg.source and msg.destination not null
Returns
true if the message has been handled and needs no further processing
Note
Unless you really need to, override on_handle()
Reimplemented in handler::SimpleAction.
Definition at line 72 of file handler.hpp.
Referenced by handler::SimpleGroup::on_handle(), handler::AbstractList::on_handle(), and Melanobot::run().
virtual void handler::Handler::initialize () inline virtual
Called at startup in case it needs to perform some initialization.
Reimplemented in handler::BridgeAttachChannel, handler::BridgeAttach, and handler::SimpleGroup.
Definition at line 92 of file handler.hpp.
Referenced by handler::SimpleGroup::initialize(), and Melanobot::run().
Melanobot* handler::Handler::melanobot () const inline final virtual
Get the top-level bot for this HandlerContainer.
Implements handler::HandlerContainer.
Definition at line 64 of file handler.hpp.
virtual bool handler::Handler::on_handle (network::Message & msg) protected pure virtual
Required for concrete handlers, performs the handler actions.
Returns
true if the message has been handled and needs no further processing
Implemented in handler::Time, handler::Action, handler::Reply, handler::Cointoss, handler::Chanhax, fun::Discord, handler::ServerHost, fun::RainbowBridgeChat, handler::Echo, irc::handler::CtcpClientInfo, fun::Slap, handler::AdminDisconnect, handler::ListClear, irc::handler::CtcpTime, handler::AdminConnect, handler::SearchWebSearx, fun::AnswerQuestions, xonotic::ParseEventlog, irc::handler::CtcpPing, handler::ListRemove, irc::handler::WhoisCheckMe, handler::AdminReconnect, irc::handler::CtcpUserInfo, handler::UrbanDictionary, xonotic::XonoticMatchStart, irc::handler::AdminRaw, handler::FilterGroup, fun::PonyCountDown, irc::handler::CtcpSource, handler::EventMessageBase, handler::ListInsert, irc::handler::AcceptInvite, handler::AbstractList, handler::SearchImageGoogle, xonotic::XonoticJoinPart, fun::RenderPony, irc::handler::QGetWhois, irc::handler::CtcpVersion, irc::handler::AdminPart, handler::BridgeAttachChannel, fun::ChuckNorris, xonotic::ConnectionEvents, handler::BridgeAttach, handler::Help, irc::handler::QSendWhois, irc::handler::AdminJoin, fun::ReverseText, handler::SimpleGroup, handler::BridgeChat, xonotic::RconCommand, irc::handler::IrcKickRejoin, fun::Morse, handler::SearchVideoYoutube, handler::License, handler::Bridge, irc::handler::Whois330, irc::handler::AdminNick, and handler::AdminQuit.
Referenced by handle(), and handler::SimpleAction::handle().
Handler& handler::Handler::operator= (const Handler &) delete
void handler::Handler::populate_properties (const std::vector< std::string > & properties, PropertyTree & output) const inline override virtual
Simply appends globally the given property.
Implements handler::HandlerContainer.
Reimplemented in handler::SimpleGroup.
Definition at line 118 of file handler.hpp.
Referenced by handler::SimpleGroup::populate_properties(), and Melanobot::populate_properties().
virtual std::string handler::Handler::reply_channel (const network::Message & msg) const inline protected virtual
Returns the preferred output channel for the given message.
If msg comes from multiple channels, the first one is used
Reimplemented in handler::SimpleAction.
Definition at line 140 of file handler.hpp.
Referenced by handler::EventMessageBase::on_handle(), and reply_to().
virtual void handler::Handler::reply_to (const network::Message & input, network::OutputMessage output) const inline protected virtual
Send a reply to a message.
Note
output priority and channel will be overwritten
Reimplemented in irc::handler::CtcpBase.
Definition at line 155 of file handler.hpp.
Referenced by handler::EventMessageBase::on_handle(), handler::Action::on_handle(), and reply_to().
void handler::Handler::reply_to (const network::Message & msg, const string::FormattedString & text) const inline protected
Definition at line 161 of file handler.hpp.
Referenced by xonotic::XonoticMatchScore::handle_end(), handler::SearchVideoYoutube::json_success(), handler::SearchWebSearx::json_success(), handler::Help::on_handle(), xonotic::ConnectionEvents::on_handle(), xonotic::XonoticJoinPart::on_handle(), handler::ListInsert::on_handle(), xonotic::XonoticMatchStart::on_handle(), handler::ListRemove::on_handle(), xonotic::ShowVoteCall::on_handle(), xonotic::ShowVoteResult::on_handle(), xonotic::ShowVoteStop::on_handle(), xonotic::ShowVoteLogin::on_handle(), xonotic::ShowVoteDo::on_handle(), and xonotic::XonoticMatchScore::print_scores().
void handler::Handler::reply_to (const network::Message & msg, const std::string & text) const inline protected
Definition at line 165 of file handler.hpp.
Referenced by handler::SearchVideoYoutube::json_success(), handler::SearchImageGoogle::json_success(), handler::UrbanDictionary::json_success(), handler::SearchWebSearx::json_success(), handler::License::on_handle(), irc::handler::IrcKickRejoin::on_handle(), irc::handler::CtcpVersion::on_handle(), handler::AbstractList::on_handle(), handler::ListInsert::on_handle(), irc::handler::CtcpSource::on_handle(), irc::handler::CtcpUserInfo::on_handle(), handler::ListRemove::on_handle(), irc::handler::CtcpPing::on_handle(), irc::handler::CtcpTime::on_handle(), handler::ListClear::on_handle(), handler::Echo::on_handle(), handler::ServerHost::on_handle(), handler::Cointoss::on_handle(), handler::Reply::on_handle(), handler::Action::on_handle(), and handler::Time::on_handle().
Member Data Documentation
Melanobot* handler::Handler::bot {nullptr} protected
Pointer to the main bot.
Definition at line 197 of file handler.hpp.
Referenced by handler::AdminGroup::AdminGroup(), handler::Bridge::Bridge(), Handler(), melanobot(), handler::AdminQuit::on_handle(), handler::Help::on_handle(), handler::BridgeAttach::on_handle(), irc::handler::CtcpClientInfo::on_handle(), and handler::SimpleGroup::SimpleGroup().
Handler* handler::Handler::parent_handler {nullptr} protected
Pointer to a handler containing this one.
Definition at line 201 of file handler.hpp.
Referenced by get_parent(), and Handler().
int handler::Handler::priority {0} protected
Message priority.
Definition at line 193 of file handler.hpp.
Referenced by get_property(), Handler(), irc::handler::IrcKickRejoin::on_handle(), handler::BridgeChat::on_handle(), xonotic::RconCommand::on_handle(), irc::handler::QSendWhois::on_handle(), handler::EventMessageBase::on_handle(), irc::handler::WhoisCheckMe::on_handle(), handler::Command::on_handle(), irc::handler::CtcpBase::reply_to(), and reply_to().
The documentation for this class was generated from the following file:
src/handler/handler.hpp