MelanoBot: network::irc::Buffer Class Reference
network::irc::Buffer Class Reference
IRC buffer.
#include <irc.hpp>
Public Member Functions
Buffer (IrcConnection &irc, const Settings &settings={})
void insert (const Command &cmd)
Inserts a command to the buffer.
void process ()
Process the top command (if any)
void write (const Command &cmd)
Outputs directly a line from the command.
void connect (const Server &server)
Connect to the given server.
void disconnect ()
Disconnect from the server.
void start ()
Starts the io service.
void stop ()
Stops the io service.
bool connected () const
Checks if the connection is active.
Private Member Functions
void run_input ()
While active, keep processing reads.
void run_output ()
While active, keep processing writes.
void schedule_read ()
Schedules an asynchronous line read.
void write_line (std::string line)
Writes a line to the socket.
void on_read_line (const boost::system::error_code &error)
Async hook on network input.
Private Attributes
IrcConnection & irc
ConcurrentPriorityQueue< Command > buffer
Store messages when it isn't possible to send them.
std::thread thread_output
Thread running the output.
std::thread thread_input
Thread running the input.
unsigned flood_max_length = 510
Maximum nuber of bytes in a message (longer messages will be truncated)
Time flood_timer
Message timer.
Duration flood_timer_max
Maximum duration the flood timer can be ahead of now.
Duration flood_timer_penalty
Message penalty.
boost::asio::streambuf buffer_read
boost::asio::streambuf buffer_write
boost::asio::io_service io_service
boost::asio::ip::tcp::resolver resolver {io_service}
boost::asio::ip::tcp::socket socket {io_service}
Detailed Description
IRC buffer.
Contains the network connection and performs flood checking
Definition at line 118 of file irc.hpp.
Constructor & Destructor Documentation
network::irc::Buffer::Buffer (IrcConnection & irc, const Settings & settings = {}) explicit
Definition at line 50 of file irc.cpp.
Referenced by network::irc::IrcConnection::IrcConnection().
Member Function Documentation
void network::irc::Buffer::connect (const Server & server)
Connect to the given server.
Threading
Threads: external
Locks: none
Todo:
async with error checking
Definition at line 146 of file irc.cpp.
Referenced by network::irc::IrcConnection::connect().
bool network::irc::Buffer::connected () const
Checks if the connection is active.
Threading
Threads: external
Locks: none
Definition at line 164 of file irc.cpp.
Referenced by connect(), and network::irc::IrcConnection::connect().
void network::irc::Buffer::disconnect ()
Disconnect from the server.
Threading
Threads: external
Locks: none
Todo:
try catch
Definition at line 157 of file irc.cpp.
Referenced by connect(), network::irc::IrcConnection::disconnect(), and stop().
void network::irc::Buffer::insert (const Command & cmd)
Inserts a command to the buffer.
Threading
Threads: external
Locks: buffer
Definition at line 92 of file irc.cpp.
Referenced by network::irc::IrcConnection::command().
void network::irc::Buffer::on_read_line (const boost::system::error_code & error) private
Async hook on network input.
Threading
Threads: irc_in
Locks: none
Definition at line 175 of file irc.cpp.
Referenced by schedule_read().
void network::irc::Buffer::process ()
Process the top command (if any)
Threading
Threads: irc_out
Locks: buffer(waits for input, waits for flood timer)
Definition at line 97 of file irc.cpp.
Referenced by run_output().
void network::irc::Buffer::run_input () private
While active, keep processing reads.
Todo:
catch exception thrown on broken pipe
Definition at line 65 of file irc.cpp.
Referenced by start().
void network::irc::Buffer::run_output () private
While active, keep processing writes.
Definition at line 59 of file irc.cpp.
Referenced by start().
void network::irc::Buffer::schedule_read () private
Schedules an asynchronous line read.
Threading
Threads: irc_in
Locks: none (async)
Definition at line 169 of file irc.cpp.
Referenced by on_read_line(), and run_input().
void network::irc::Buffer::start ()
Starts the io service.
Threading
Threads: main
Definition at line 73 of file irc.cpp.
Referenced by network::irc::IrcConnection::start().
void network::irc::Buffer::stop ()
Stops the io service.
Threading
Threads: main
Definition at line 81 of file irc.cpp.
Referenced by network::irc::IrcConnection::stop(), and network::irc::IrcConnection::~IrcConnection().
void network::irc::Buffer::write (const Command & cmd)
Outputs directly a line from the command.
Threading
Threads: irc_out, external(quit)
Locks: none
Definition at line 116 of file irc.cpp.
Referenced by network::irc::IrcConnection::disconnect(), and process().
void network::irc::Buffer::write_line (std::string line) private
Writes a line to the socket.
Threading
Threads: irc_out, external(quit)
Locks: none
Note
this is synchronous, if it becomes async, keep QUIT as a sync message before disconnect()
Todo:
maybe try to strip and
from line
Definition at line 130 of file irc.cpp.
Referenced by write().
Member Data Documentation
ConcurrentPriorityQueue<Command> network::irc::Buffer::buffer private
Store messages when it isn't possible to send them.
Definition at line 179 of file irc.hpp.
Referenced by insert(), process(), run_output(), and stop().
boost::asio::streambuf network::irc::Buffer::buffer_read private
Definition at line 210 of file irc.hpp.
Referenced by on_read_line(), and schedule_read().
boost::asio::streambuf network::irc::Buffer::buffer_write private
Definition at line 211 of file irc.hpp.
Referenced by write_line().
unsigned network::irc::Buffer::flood_max_length = 510 private
Maximum nuber of bytes in a message (longer messages will be truncated)
See also
http://tools.ietf.org/html/rfc2812#section-2.3
Definition at line 192 of file irc.hpp.
Referenced by Buffer(), and write_line().
Time network::irc::Buffer::flood_timer private
Message timer.
See also
http://tools.ietf.org/html/rfc2813#section-5.8
Definition at line 197 of file irc.hpp.
Referenced by Buffer(), connect(), process(), and write_line().
Duration network::irc::Buffer::flood_timer_max private
Maximum duration the flood timer can be ahead of now.
See also
http://tools.ietf.org/html/rfc2813#section-5.8
Definition at line 202 of file irc.hpp.
Referenced by Buffer(), and process().
Duration network::irc::Buffer::flood_timer_penalty private
Message penalty.
See also
http://tools.ietf.org/html/rfc2813#section-5.8
Definition at line 207 of file irc.hpp.
Referenced by Buffer(), process(), and write_line().
boost::asio::io_service network::irc::Buffer::io_service private
Definition at line 212 of file irc.hpp.
IrcConnection& network::irc::Buffer::irc private
Definition at line 173 of file irc.hpp.
Referenced by Buffer(), on_read_line(), and write_line().
boost::asio::ip::tcp::resolver network::irc::Buffer::resolver {io_service} private
Definition at line 213 of file irc.hpp.
boost::asio::ip::tcp::socket network::irc::Buffer::socket {io_service} private
Definition at line 214 of file irc.hpp.
std::thread network::irc::Buffer::thread_input private
Thread running the input.
Definition at line 187 of file irc.hpp.
Referenced by start(), and stop().
std::thread network::irc::Buffer::thread_output private
Thread running the output.
Definition at line 183 of file irc.hpp.
Referenced by start(), and stop().
The documentation for this class was generated from the following files:
src/network/irc.hpp
src/network/irc.cpp