MelanoBot: timer::TimeParser Class Reference
timer::TimeParser Class Reference
Parses a time description.
#include <time_parser.hpp>
Classes
struct Token
Parsed token.
Public Types
using Clock = DateTime::Clock
using Time = typename Clock::time_point
using Duration = typename Clock::duration
Public Member Functions
TimeParser (std::istream &input)
DateTime parse_time_point ()
Parses a time point.
Duration parse_duration ()
Parses a duration.
Private Member Functions
Token lex_identifier (char c)
Lex an identifier.
Token lex_time (std::string &lexed)
Lexes a time (12:34[:56[.789]])
Token lex_date (std::string &lexed)
Lexes a date 1234-02-23.
std::string lex_raw_number (char &c)
Lex a number without any other processing.
Token lex_number (char c)
Lex a number.
Token lex ()
Reads the next token.
void scan ()
Reads the next token into lookahead.
template<class T >
T token_val ()
Extract value from lookahead.
template<class DurationT >
Duration duration_cast (DurationT &&dur)
Convert any duration type into Duration.
Duration parse_atomic_duration ()
Parses an atomic duration.
DateTime parse_date_time ()
Parses a date and (optionally) a time.
DateTime parse_day ()
Parses a day.
DateTime parse_date_desc ()
Parses a date description.
DateTime next_weekday (WeekDay wday)
Day matching the given week day.
void parse_month_day (int &day)
Parse a day of the month into day.
void parse_time (DateTime &out)
Parses a time and writes it to out.
Static Private Member Functions
template<class DurationT >
static bool is_unit (const std::string &str)
Checks if a string is a unit description for the given duration type.
Private Attributes
Token lookahead
Last read token.
std::istream input
Input stream.
Detailed Description
Parses a time description.
Definition at line 30 of file time_parser.hpp.
Member Typedef Documentation
using timer::TimeParser::Clock = DateTime::Clock
Definition at line 33 of file time_parser.hpp.
using timer::TimeParser::Duration = typename Clock::duration
Definition at line 35 of file time_parser.hpp.
using timer::TimeParser::Time = typename Clock::time_point
Definition at line 34 of file time_parser.hpp.
Constructor & Destructor Documentation
timer::TimeParser::TimeParser (std::istream & input) inline
Definition at line 37 of file time_parser.hpp.
Referenced by timer::parse_duration(), and timer::parse_time().
Member Function Documentation
template<class DurationT > Duration timer::TimeParser::duration_cast (DurationT && dur) inline private
Convert any duration type into Duration.
Definition at line 335 of file time_parser.hpp.
Referenced by parse_atomic_duration().
template<class DurationT > static bool timer::TimeParser::is_unit (const std::string & str) inline static private
Checks if a string is a unit description for the given duration type.
Template Parameters
DurationT one of the type aliases like seconds and friends
Definition at line 345 of file time_parser.hpp.
Referenced by parse_atomic_duration(), and parse_duration().
Token timer::TimeParser::lex () inline private
Reads the next token.
Definition at line 296 of file time_parser.hpp.
Referenced by scan().
Token timer::TimeParser::lex_date (std::string & lexed) inline private
Lexes a date 1234-02-23.
Parameters
lexed Lexed year
Precondition
lexed contains only decimal digits
A '-' has been lexed
Definition at line 236 of file time_parser.hpp.
Referenced by lex_number().
Token timer::TimeParser::lex_identifier (char c) inline private
Lex an identifier.
Parameters
c Lookahead character
Definition at line 158 of file time_parser.hpp.
Referenced by lex().
Token timer::TimeParser::lex_number (char c) inline private
Lex a number.
Parameters
c Lookahead character
Definition at line 282 of file time_parser.hpp.
Referenced by lex().
std::string timer::TimeParser::lex_raw_number (char & c) inline private
Lex a number without any other processing.
Parameters
c Lookahead character
Definition at line 267 of file time_parser.hpp.
Referenced by lex_date(), lex_number(), and lex_time().
Token timer::TimeParser::lex_time (std::string & lexed) inline private
Lexes a time (12:34[:56[.789]])
Parameters
lexed Lexed first two digits
Precondition
lexed contains two decimal digits
A ':' has been lexed
Definition at line 200 of file time_parser.hpp.
Referenced by lex_number().
DateTime timer::TimeParser::next_weekday (WeekDay wday) inline private
Day matching the given week day.
Definition at line 516 of file time_parser.hpp.
Referenced by parse_date_desc().
Duration timer::TimeParser::parse_atomic_duration () inline private
Parses an atomic duration.
ATOMIC_DURATION         ::= number unit
Definition at line 366 of file time_parser.hpp.
Referenced by parse_duration().
DateTime timer::TimeParser::parse_date_desc () inline private
Parses a date description.
DATE_DESC       ::= OPT_WEEK_DAY month MONTH_DAY OPT_YEAR
                | OPT_WEEK_DAY MONTH_DAY month OPT_YEAR
                | week_day | "next" week_day
OPT_WEEK_DAY    ::= (eps) | week_day
ORDINAL_SUFFIX  ::= st | nd | rd | th
OPT_YEAR        ::= (eps) | number
Definition at line 462 of file time_parser.hpp.
Referenced by parse_day().
DateTime timer::TimeParser::parse_date_time () inline private
Parses a date and (optionally) a time.
DATE_TIME       ::= DAY OPT_TIME
OPT_TIME        ::= (eps) | at TIME | TIME | "T" TIME
Definition at line 417 of file time_parser.hpp.
Referenced by parse_time_point().
DateTime timer::TimeParser::parse_day () inline private
Parses a day.
DAY     ::= rel_date | date | DATE_DESC
Definition at line 433 of file time_parser.hpp.
Referenced by parse_date_time().
Duration timer::TimeParser::parse_duration () inline
Parses a duration.
DURATION        ::= HOUR_OPT DURATION_SEQ
HOUR_OPT        ::= (eps) | time | time "h" | time "min"
DURATION_SEQ    ::= ATOMIC_DURATION | ATOMIC_DURATION DURATION_SEQ | (eps)
Definition at line 79 of file time_parser.hpp.
Referenced by timer::parse_duration(), and parse_time_point().
void timer::TimeParser::parse_month_day (int & day) inline private
Parse a day of the month into day.
MONTH_DAY       ::= number | number ORDINAL_SUFFIX
Definition at line 536 of file time_parser.hpp.
Referenced by parse_date_desc().
void timer::TimeParser::parse_time (DateTime & out) inline private
Parses a time and writes it to out.
TIME    ::= time | time AMPM
Definition at line 557 of file time_parser.hpp.
Referenced by parse_date_time().
DateTime timer::TimeParser::parse_time_point () inline
Parses a time point.
TIME_POINT      ::= NOW_TIME | DATE_TIME
NOW_TIME        ::= now
                |   now + DURATION
                |   now - DURATION
Definition at line 51 of file time_parser.hpp.
Referenced by timer::parse_time().
void timer::TimeParser::scan () inline private
Reads the next token into lookahead.
Definition at line 318 of file time_parser.hpp.
Referenced by parse_atomic_duration(), parse_date_desc(), parse_date_time(), parse_day(), parse_duration(), parse_month_day(), parse_time(), parse_time_point(), and TimeParser().
template<class T > T timer::TimeParser::token_val () inline private
Extract value from lookahead.
Definition at line 327 of file time_parser.hpp.
Referenced by parse_atomic_duration(), parse_date_desc(), parse_date_time(), parse_day(), parse_duration(), parse_month_day(), and parse_time().
Member Data Documentation
std::istream timer::TimeParser::input private
Input stream.
Definition at line 151 of file time_parser.hpp.
Referenced by lex(), lex_date(), lex_identifier(), lex_number(), lex_raw_number(), lex_time(), and TimeParser().
Token timer::TimeParser::lookahead private
Last read token.
Definition at line 150 of file time_parser.hpp.
Referenced by parse_atomic_duration(), parse_date_desc(), parse_date_time(), parse_day(), parse_duration(), parse_month_day(), parse_time(), parse_time_point(), scan(), and token_val().
The documentation for this class was generated from the following file:
src/time/time_parser.hpp