MelanoBot: string::Format Class Reference
string::Format Class Reference
Formatting flag.
#include <string.hpp>
Public Member Functions
Format (const FormatFlags &flags)
std::string to_string (const Formatter &formatter) const override
Visitor format to string.
Public Member Functions inherited from string::Element
virtual ~Element ()
std::string to_string (Formatter *formatter) const
Private Attributes
FormatFlags flags
Detailed Description
Formatting flag.
Definition at line 375 of file string.hpp.
Constructor & Destructor Documentation
string::Format::Format (const FormatFlags & flags) inline
Definition at line 378 of file string.hpp.
Referenced by string::FormatterAnsi::decode(), string::FormatterIrc::decode(), and string::FormattedStream::operator<<().
Member Function Documentation
std::string string::Format::to_string (const Formatter & formatter) const inline override virtual
Visitor format to string.
Implements string::Element.
Definition at line 380 of file string.hpp.
Member Data Documentation
FormatFlags string::Format::flags private
Definition at line 386 of file string.hpp.
Referenced by Format(), and to_string().
The documentation for this class was generated from the following file:
src/string/string.hpp