MelanoBot: string::BasicTrie< MappedType > Class Template Reference
string::BasicTrie< MappedType > Class Template Reference
Prefix Tree with optionally associated data.
#include <trie.hpp>
Classes
class iterator
Handle to the node.
struct TrieNode
A node in the tree.
class TrieNodeData
Class to allow real data as well as no data (void) for TrieNode.
Public Types
using value_type = MappedType
using key_type = std::string
using const_iterator = iterator
Public Member Functions
BasicTrie ()
Constructs an empty tree O(1)
BasicTrie (const std::initializer_list< std::string > &il)
Initialize from the words in the initializer list.
BasicTrie (const BasicTrie &other)
Copies from another trie O(number of nodes in other)
BasicTrie & operator= (const BasicTrie &other)
Copies from another trie O(number of nodes in other)
BasicTrie (BasicTrie &&other) noexcept
BasicTrie & operator= (BasicTrie &&other) noexcept
~BasicTrie ()
bool empty () const
Returns true if the trie doesn't have any meaningful node.
iterator insert (const std::string &word, const TrieNodeData &data={})
Adds a new word to the trie O(word.size())
void prepend (char c)
Prepends a single character to all words O(number of node) (caused by deepen)
void prepend (const std::string &prefix)
Prepends a prefix to all words O(prefix.size())
void erase (const std::string &word)
Removes a word from the trie O(word.size())
bool contains (const std::string &word) const
Checks if a word exists O(word.size())
bool contains_prefix (const std::string &word) const
Checks if a prefix exists O(word.size())
iterator root () const
Returns an iterator to the root O(1)
iterator find (const std::string &word) const
Returns an iterator to the root O(word.size())
template<class Functor >
void recurse (const Functor &functor) const
Recursively call a function on iterators O(number of nodes)
Private Member Functions
void remove_dangling (TrieNode *node)
Removes branches which don't lead to any word O(h)
TrieNode * find_node (const std::string &word) const
Finds a node matching the given word (or prefix)
template<class Functor >
void recurse (const TrieNode *node, const Functor &functor, const std::string &prefix) const
Recursively call a function on iterators O(nodes in the sub-tree)
Private Attributes
TrieNode * root_
Root node.
Detailed Description
template<class MappedType>
class string::BasicTrie< MappedType >
Prefix Tree with optionally associated data.
Template Parameters
MappedType Value associated with the keys. Must be void or DefaultConstructible, MoveConstructible For deep copy to work, CopyAssignable
Definition at line 37 of file trie.hpp.
Member Typedef Documentation
template<class MappedType > using string::BasicTrie< MappedType >::const_iterator = iterator
Definition at line 265 of file trie.hpp.
template<class MappedType > using string::BasicTrie< MappedType >::key_type = std::string
Definition at line 41 of file trie.hpp.
template<class MappedType > using string::BasicTrie< MappedType >::value_type = MappedType
Definition at line 40 of file trie.hpp.
Constructor & Destructor Documentation
template<class MappedType > string::BasicTrie< MappedType >::BasicTrie () inline
Constructs an empty tree O(1)
Definition at line 271 of file trie.hpp.
template<class MappedType > string::BasicTrie< MappedType >::BasicTrie (const std::initializer_list< std::string > & il) inline
Initialize from the words in the initializer list.
Definition at line 276 of file trie.hpp.
template<class MappedType > string::BasicTrie< MappedType >::BasicTrie (const BasicTrie< MappedType > & other) inline
Copies from another trie O(number of nodes in other)
Definition at line 286 of file trie.hpp.
template<class MappedType > string::BasicTrie< MappedType >::BasicTrie (BasicTrie< MappedType > && other) inline noexcept
Definition at line 298 of file trie.hpp.
template<class MappedType > string::BasicTrie< MappedType >::~BasicTrie () inline
Definition at line 309 of file trie.hpp.
Member Function Documentation
template<class MappedType > bool string::BasicTrie< MappedType >::contains (const std::string & word) const inline
Checks if a word exists O(word.size())
Definition at line 390 of file trie.hpp.
template<class MappedType > bool string::BasicTrie< MappedType >::contains_prefix (const std::string & word) const inline
Checks if a prefix exists O(word.size())
Definition at line 400 of file trie.hpp.
template<class MappedType > bool string::BasicTrie< MappedType >::empty () const inline
Returns true if the trie doesn't have any meaningful node.
Definition at line 317 of file trie.hpp.
Referenced by string::BasicTrie< MappedType >::prepend(), and string::replace().
template<class MappedType > void string::BasicTrie< MappedType >::erase (const std::string & word) inline
Removes a word from the trie O(word.size())
Definition at line 376 of file trie.hpp.
template<class MappedType > iterator string::BasicTrie< MappedType >::find (const std::string & word) const inline
Returns an iterator to the root O(word.size())
Definition at line 418 of file trie.hpp.
template<class MappedType > TrieNode* string::BasicTrie< MappedType >::find_node (const std::string & word) const inline private
Finds a node matching the given word (or prefix)
Returns
nullptr if not found O(word.size())
Definition at line 464 of file trie.hpp.
Referenced by string::BasicTrie< MappedType >::contains(), string::BasicTrie< MappedType >::contains_prefix(), string::BasicTrie< MappedType >::erase(), and string::BasicTrie< MappedType >::find().
template<class MappedType > iterator string::BasicTrie< MappedType >::insert (const std::string & word, const TrieNodeData & data = {}) inline
Adds a new word to the trie O(word.size())
Definition at line 326 of file trie.hpp.
Referenced by string::BasicTrie< MappedType >::BasicTrie(), and string::make_trie().
template<class MappedType > BasicTrie& string::BasicTrie< MappedType >::operator= (const BasicTrie< MappedType > & other) inline
Copies from another trie O(number of nodes in other)
Definition at line 292 of file trie.hpp.
template<class MappedType > BasicTrie& string::BasicTrie< MappedType >::operator= (BasicTrie< MappedType > && other) inline noexcept
Definition at line 303 of file trie.hpp.
template<class MappedType > void string::BasicTrie< MappedType >::prepend (char c) inline
Prepends a single character to all words O(number of node) (caused by deepen)
Definition at line 340 of file trie.hpp.
template<class MappedType > void string::BasicTrie< MappedType >::prepend (const std::string & prefix) inline
Prepends a prefix to all words O(prefix.size())
Definition at line 354 of file trie.hpp.
Referenced by string::replace().
template<class MappedType > template<class Functor > void string::BasicTrie< MappedType >::recurse (const Functor & functor) const inline
Recursively call a function on iterators O(number of nodes)
Template Parameters
Functor function object taking an iterator and a std::string
Calls functor repeatedly passing an iterator to the node and its prefix as a std::string
Definition at line 433 of file trie.hpp.
template<class MappedType > template<class Functor > void string::BasicTrie< MappedType >::recurse (const TrieNode * node, const Functor & functor, const std::string & prefix) const inline private
Recursively call a function on iterators O(nodes in the sub-tree)
Definition at line 481 of file trie.hpp.
template<class MappedType > void string::BasicTrie< MappedType >::remove_dangling (TrieNode * node) inline private
Removes branches which don't lead to any word O(h)
Definition at line 446 of file trie.hpp.
Referenced by string::BasicTrie< MappedType >::erase().
template<class MappedType > iterator string::BasicTrie< MappedType >::root () const inline
Returns an iterator to the root O(1)
Definition at line 409 of file trie.hpp.
Referenced by string::replace().
Member Data Documentation
template<class MappedType > TrieNode* string::BasicTrie< MappedType >::root_ private
Root node.
Definition at line 440 of file trie.hpp.
Referenced by string::BasicTrie< MappedType >::BasicTrie(), string::BasicTrie< MappedType >::empty(), string::BasicTrie< MappedType >::find_node(), string::BasicTrie< MappedType >::operator=(), string::BasicTrie< MappedType >::prepend(), string::BasicTrie< MappedType >::recurse(), string::BasicTrie< MappedType >::root(), and string::BasicTrie< MappedType >::~BasicTrie().
The documentation for this class was generated from the following file:
src/string/trie.hpp