MelanoBot: string::Formatter Class Reference
string::Formatter Class Reference abstract
Abstract formatting visitor (and factory)
#include <string.hpp>
Classes
class FormatterFactory
Internal factory.
Public Member Functions
virtual ~Formatter ()
virtual std::string ascii (char c) const =0
Encode a single ASCII character.
virtual std::string ascii (const std::string &s) const =0
Encode a simple ASCII string.
virtual std::string color (const color::Color12 &color) const =0
Encode a color code.
virtual std::string format_flags (FormatFlags flags) const =0
Encode format flags.
virtual std::string unicode (const Unicode &c) const =0
Encode a unicode (non-ASCII) character.
virtual std::string qfont (const QFont &c) const =0
Encode a Darkpaces weird character.
virtual std::string clear () const =0
Clear all formatting.
virtual FormattedString decode (const std::string &source) const =0
Decode a string.
virtual std::string name () const =0
Name of the format.
Static Public Member Functions
static Formatter * formatter (const std::string &name)
Get a string formatter from name.
Detailed Description
Abstract formatting visitor (and factory)
Note
Formatters should register here
Definition at line 179 of file string.hpp.
Constructor & Destructor Documentation
virtual string::Formatter::~Formatter () inline virtual
Definition at line 225 of file string.hpp.
Member Function Documentation
virtual std::string string::Formatter::ascii (char c) const pure virtual
Encode a single ASCII character.
Implemented in string::FormatterUtf8, and xonotic::Formatter.
Referenced by string::Character::to_string().
virtual std::string string::Formatter::ascii (const std::string & s) const pure virtual
Encode a simple ASCII string.
Implemented in string::FormatterUtf8, and xonotic::Formatter.
Referenced by string::AsciiSubstring::to_string().
virtual std::string string::Formatter::clear () const pure virtual
Clear all formatting.
Implemented in string::FormatterAnsi, string::FormatterUtf8, xonotic::Formatter, and irc::FormatterIrc.
Referenced by Logger::log(), and string::ClearFormatting::to_string().
virtual std::string string::Formatter::color (const color::Color12 & color) const pure virtual
Encode a color code.
Todo:
Background colors?
Implemented in string::FormatterAnsi, string::FormatterUtf8, xonotic::Formatter, and irc::FormatterIrc.
Referenced by Logger::log(), and string::Color::to_string().
virtual FormattedString string::Formatter::decode (const std::string & source) const pure virtual
Decode a string.
Implemented in string::FormatterAnsi, string::FormatterAscii, string::FormatterUtf8, xonotic::Formatter, and irc::FormatterIrc.
Referenced by handler::BridgeChat::on_handle(), handler::ReverseText::on_handle(), and string::FormattedStream::operator<<().
virtual std::string string::Formatter::format_flags (FormatFlags flags) const pure virtual
Encode format flags.
Implemented in string::FormatterAnsi, string::FormatterUtf8, xonotic::Formatter, and irc::FormatterIrc.
Referenced by string::Format::to_string().
static Formatter* string::Formatter::formatter (const std::string & name) inline static
Get a string formatter from name.
Definition at line 270 of file string.hpp.
Referenced by string::FormattedString::encode(), string::FormattedStream::FormattedStream(), and Logger::load_settings().
virtual std::string string::Formatter::name () const pure virtual
Name of the format.
Implemented in string::FormatterAnsi, string::FormatterAscii, string::FormatterUtf8, xonotic::Formatter, and irc::FormatterIrc.
Referenced by string::Formatter::FormatterFactory::add_formatter().
virtual std::string string::Formatter::qfont (const QFont & c) const pure virtual
Encode a Darkpaces weird character.
Implemented in string::FormatterUtf8, and xonotic::Formatter.
Referenced by string::QFont::to_string().
virtual std::string string::Formatter::unicode (const Unicode & c) const pure virtual
Encode a unicode (non-ASCII) character.
Implemented in string::FormatterAnsi, string::FormatterAscii, string::FormatterUtf8, and xonotic::Formatter.
Referenced by string::Unicode::to_string().
The documentation for this class was generated from the following file:
src/string/string.hpp