MelanoBot: Melanobot Class Reference
Melanobot Class Reference
Main bot class.
#include <melanobot.hpp>
Public Member Functions
Melanobot (const Settings &settings)
~Melanobot ()
void run ()
Runs the bot.
void stop ()
Stops the bot.
void message (const network::Message &msg)
Inform the bot there's an incoming message.
network::Connection * connection (const std::string &name) const
Get connection by name.
void populate_properties (const std::vector< std::string > &property, PropertyTree &output) const override
Populates output from properties of its children.
Public Member Functions inherited from handler::HandlerContainer
virtual ~HandlerContainer ()
Private Attributes
std::unordered_map
< std::string,
network::Connection * > connections
std::vector< handler::Handler * > handlers
ConcurrentQueue< network::Message > messages
Detailed Description
Main bot class.
Definition at line 37 of file melanobot.hpp.
Constructor & Destructor Documentation
Melanobot::Melanobot (const Settings & settings) explicit
Definition at line 23 of file melanobot.cpp.
Referenced by main().
Melanobot::~Melanobot ()
Definition at line 54 of file melanobot.cpp.
Member Function Documentation
network::Connection * Melanobot::connection (const std::string & name) const
Get connection by name.
Returns
NULL if not found
Definition at line 106 of file melanobot.cpp.
Referenced by handler::SimpleGroup::SimpleGroup().
void Melanobot::message (const network::Message & msg)
Inform the bot there's an incoming message.
Threading
Threads: main
Locks: messages
Definition at line 101 of file melanobot.cpp.
Referenced by network::irc::IrcConnection::handle_message().
void Melanobot::populate_properties (const std::vector< std::string > & properties, PropertyTree & output) const override virtual
Populates output from properties of its children.
Implements handler::HandlerContainer.
Definition at line 114 of file melanobot.cpp.
Referenced by handler::Help::on_handle(), and handler::CtcpClientInfo::on_handle().
void Melanobot::run ()
Runs the bot.
Threading
Threads: main
Locks: messages(not continuous)
Definition at line 68 of file melanobot.cpp.
Referenced by main().
void Melanobot::stop ()
Stops the bot.
Threading
Threads: external
Locks: none
Definition at line 62 of file melanobot.cpp.
Referenced by network::irc::IrcConnection::error_stop(), handler::AdminQuit::on_handle(), and ~Melanobot().
Member Data Documentation
std::unordered_map<std::string,network::Connection*> Melanobot::connections private
Todo:
allow dynamic connection/handler creation (requires locking)
Definition at line 71 of file melanobot.hpp.
Referenced by connection(), Melanobot(), and run().
std::vector<handler::Handler*> Melanobot::handlers private
Definition at line 72 of file melanobot.hpp.
Referenced by Melanobot(), and populate_properties().
ConcurrentQueue<network::Message> Melanobot::messages private
Definition at line 74 of file melanobot.hpp.
Referenced by message(), run(), and stop().
The documentation for this class was generated from the following files:
src/melanobot.hpp
src/melanobot.cpp