MelanoBot: string::BasicQuickStream< CharT, Traits > Class Template Reference
string::BasicQuickStream< CharT, Traits > Class Template Reference
Quick and simple unformatted string input stream.
#include <quickstream.hpp>
Public Types
using char_type = CharT
using string_type = std::basic_string< CharT, Traits >
using pos_type = typename string_type::size_type
using size_type = typename string_type::size_type
using int_type = typename Traits::int_type
using regex_type = std::basic_regex< CharT >
using match_type = std::match_results< typename string_type::const_iterator >
Public Member Functions
BasicQuickStream ()
BasicQuickStream (std::string input)
const string_type & str () const noexcept
Returns the contained string.
void str (const string_type &string)
Change the source string.
bool eof () const noexcept
Whether it reached the end of the string.
operator bool () const noexcept
Whether it reached past the end of the string.
void clear () noexcept
Clears errors.
int_type next () noexcept
Extracts and returns the next character.
void unget () noexcept
Undoes get() or ignore()
pos_type tell_pos () const noexcept
Returns the current read position.
void set_pos (pos_type p) noexcept
Changes the read position.
int_type peek () const noexcept
Returns the next character without extracting it.
void ignore () noexcept
Extracts the next character.
void ignore (size_type n) noexcept
Extracts n characters.
void ignore (size_type n, char_type delim) noexcept
Extracts until delim has been foun or at most n characters.
string_type get_line (char_type delim= '\n')
Get a string, until delim.
bool get_int (int &out) noexcept
Reads a simple int (without sign) expressed in base 10.
int get_int () noexcept
std::string get_regex (const regex_type &regex, std::regex_constants::match_flag_type match_flags=std::regex_constants::match_default)
Extract a string matching the given regex, starting at the current position.
bool get_regex (const regex_type &regex, match_type &match, std::regex_constants::match_flag_type match_flags=std::regex_constants::match_default)
Extract a regex result matching the given regex, starting at the current position.
bool regex_match (const regex_type &regex, match_type &match, std::regex_constants::match_flag_type match_flags=std::regex_constants::match_default) const
Returns whether the source matches the given regex, starting from the current position.
bool regex_match (const regex_type &regex, std::regex_constants::match_flag_type match_flags=std::regex_constants::match_default) const
Private Attributes
string_type source
Source string.
pos_type pos = 0
Position in the source string.
Detailed Description
template<class CharT, class Traits = std::char_traits<CharT>>
class string::BasicQuickStream< CharT, Traits >
Quick and simple unformatted string input stream.
Invariant
pos Points to the next character returned by next()
if eof() returns true, next() returns Traits::eof()
Note
Part of the interfacte is different from std::istream as it behaves differently from it
Definition at line 36 of file quickstream.hpp.
Member Typedef Documentation
template<class CharT, class Traits = std::char_traits<CharT>> using string::BasicQuickStream< CharT, Traits >::char_type = CharT
Definition at line 39 of file quickstream.hpp.
template<class CharT, class Traits = std::char_traits<CharT>> using string::BasicQuickStream< CharT, Traits >::int_type = typename Traits::int_type
Definition at line 43 of file quickstream.hpp.
template<class CharT, class Traits = std::char_traits<CharT>> using string::BasicQuickStream< CharT, Traits >::match_type = std::match_results<typename string_type::const_iterator>
Definition at line 45 of file quickstream.hpp.
template<class CharT, class Traits = std::char_traits<CharT>> using string::BasicQuickStream< CharT, Traits >::pos_type = typename string_type::size_type
Definition at line 41 of file quickstream.hpp.
template<class CharT, class Traits = std::char_traits<CharT>> using string::BasicQuickStream< CharT, Traits >::regex_type = std::basic_regex<CharT>
Definition at line 44 of file quickstream.hpp.
template<class CharT, class Traits = std::char_traits<CharT>> using string::BasicQuickStream< CharT, Traits >::size_type = typename string_type::size_type
Definition at line 42 of file quickstream.hpp.
template<class CharT, class Traits = std::char_traits<CharT>> using string::BasicQuickStream< CharT, Traits >::string_type = std::basic_string<CharT,Traits>
Definition at line 40 of file quickstream.hpp.
Constructor & Destructor Documentation
template<class CharT, class Traits = std::char_traits<CharT>> string::BasicQuickStream< CharT, Traits >::BasicQuickStream () inline
Definition at line 47 of file quickstream.hpp.
template<class CharT, class Traits = std::char_traits<CharT>> string::BasicQuickStream< CharT, Traits >::BasicQuickStream (std::string input) inline
Definition at line 48 of file quickstream.hpp.
Member Function Documentation
template<class CharT, class Traits = std::char_traits<CharT>> void string::BasicQuickStream< CharT, Traits >::clear () inline noexcept
Clears errors.
Definition at line 86 of file quickstream.hpp.
template<class CharT, class Traits = std::char_traits<CharT>> bool string::BasicQuickStream< CharT, Traits >::eof () const inline noexcept
Whether it reached the end of the string.
Definition at line 70 of file quickstream.hpp.
Referenced by string::BasicQuickStream< char >::get_int(), string::BasicQuickStream< char >::get_line(), string::BasicQuickStream< char >::get_regex(), string::BasicQuickStream< char >::ignore(), string::Utf8Parser::parse(), and string::BasicQuickStream< char >::regex_match().
template<class CharT, class Traits = std::char_traits<CharT>> bool string::BasicQuickStream< CharT, Traits >::get_int (int & out) inline noexcept
Reads a simple int (without sign) expressed in base 10.
Returns
true on success
Definition at line 186 of file quickstream.hpp.
Referenced by string::FormatterAnsi::decode().
template<class CharT, class Traits = std::char_traits<CharT>> int string::BasicQuickStream< CharT, Traits >::get_int () inline noexcept
Definition at line 194 of file quickstream.hpp.
template<class CharT, class Traits = std::char_traits<CharT>> string_type string::BasicQuickStream< CharT, Traits >::get_line (char_type delim = '\n') inline
Get a string, until delim.
delim is extracted but not inserted in the returned string
Definition at line 171 of file quickstream.hpp.
Referenced by string::FormatterConfig::decode().
template<class CharT, class Traits = std::char_traits<CharT>> std::string string::BasicQuickStream< CharT, Traits >::get_regex (const regex_type & regex, std::regex_constants::match_flag_type match_flags = std::regex_constants::match_default) inline
Extract a string matching the given regex, starting at the current position.
Definition at line 208 of file quickstream.hpp.
template<class CharT, class Traits = std::char_traits<CharT>> bool string::BasicQuickStream< CharT, Traits >::get_regex (const regex_type & regex, match_type & match, std::regex_constants::match_flag_type match_flags = std::regex_constants::match_default) inline
Extract a regex result matching the given regex, starting at the current position.
Returns
true if the regex has been matched
Definition at line 229 of file quickstream.hpp.
Referenced by irc::FormatterIrc::decode(), and xonotic::Formatter::decode().
template<class CharT, class Traits = std::char_traits<CharT>> void string::BasicQuickStream< CharT, Traits >::ignore () inline noexcept
Extracts the next character.
Definition at line 141 of file quickstream.hpp.
Referenced by xonotic::Formatter::decode(), and string::FormatterAnsi::decode().
template<class CharT, class Traits = std::char_traits<CharT>> void string::BasicQuickStream< CharT, Traits >::ignore (size_type n) inline noexcept
Extracts n characters.
Definition at line 149 of file quickstream.hpp.
template<class CharT, class Traits = std::char_traits<CharT>> void string::BasicQuickStream< CharT, Traits >::ignore (size_type n, char_type delim) inline noexcept
Extracts until delim has been foun or at most n characters.
Definition at line 157 of file quickstream.hpp.
template<class CharT, class Traits = std::char_traits<CharT>> int_type string::BasicQuickStream< CharT, Traits >::next () inline noexcept
Extracts and returns the next character.
Returns
A valid character or Traits::eof()
Definition at line 96 of file quickstream.hpp.
Referenced by string::FormatterAnsi::decode(), and string::Utf8Parser::parse().
template<class CharT, class Traits = std::char_traits<CharT>> string::BasicQuickStream< CharT, Traits >::operator bool () const inline explicit noexcept
Whether it reached past the end of the string.
Definition at line 78 of file quickstream.hpp.
template<class CharT, class Traits = std::char_traits<CharT>> int_type string::BasicQuickStream< CharT, Traits >::peek () const inline noexcept
Returns the next character without extracting it.
Returns
A valid character or Traits::eof()
Definition at line 133 of file quickstream.hpp.
Referenced by xonotic::Formatter::decode(), and string::FormatterAnsi::decode().
template<class CharT, class Traits = std::char_traits<CharT>> bool string::BasicQuickStream< CharT, Traits >::regex_match (const regex_type & regex, match_type & match, std::regex_constants::match_flag_type match_flags = std::regex_constants::match_default) const inline
Returns whether the source matches the given regex, starting from the current position.
Note
It doesn't move forward the stream position
Definition at line 247 of file quickstream.hpp.
template<class CharT, class Traits = std::char_traits<CharT>> bool string::BasicQuickStream< CharT, Traits >::regex_match (const regex_type & regex, std::regex_constants::match_flag_type match_flags = std::regex_constants::match_default) const inline
Definition at line 259 of file quickstream.hpp.
template<class CharT, class Traits = std::char_traits<CharT>> void string::BasicQuickStream< CharT, Traits >::set_pos (pos_type p) inline noexcept
Changes the read position.
Definition at line 124 of file quickstream.hpp.
template<class CharT, class Traits = std::char_traits<CharT>> const string_type& string::BasicQuickStream< CharT, Traits >::str () const inline noexcept
Returns the contained string.
Definition at line 53 of file quickstream.hpp.
template<class CharT, class Traits = std::char_traits<CharT>> void string::BasicQuickStream< CharT, Traits >::str (const string_type & string) inline
Change the source string.
Definition at line 61 of file quickstream.hpp.
Referenced by string::Utf8Parser::parse().
template<class CharT, class Traits = std::char_traits<CharT>> pos_type string::BasicQuickStream< CharT, Traits >::tell_pos () const inline noexcept
Returns the current read position.
Definition at line 115 of file quickstream.hpp.
template<class CharT, class Traits = std::char_traits<CharT>> void string::BasicQuickStream< CharT, Traits >::unget () inline noexcept
Undoes get() or ignore()
Definition at line 106 of file quickstream.hpp.
Referenced by string::FormatterAnsi::decode().
Member Data Documentation
template<class CharT, class Traits = std::char_traits<CharT>> pos_type string::BasicQuickStream< CharT, Traits >::pos = 0 private
Position in the source string.
Definition at line 269 of file quickstream.hpp.
Referenced by string::BasicQuickStream< char >::clear(), string::BasicQuickStream< char >::eof(), string::BasicQuickStream< char >::get_int(), string::BasicQuickStream< char >::get_line(), string::BasicQuickStream< char >::get_regex(), string::BasicQuickStream< char >::ignore(), string::BasicQuickStream< char >::next(), string::BasicQuickStream< char >::operator bool(), string::BasicQuickStream< char >::peek(), string::BasicQuickStream< char >::regex_match(), string::BasicQuickStream< char >::set_pos(), string::BasicQuickStream< char >::str(), string::BasicQuickStream< char >::tell_pos(), and string::BasicQuickStream< char >::unget().
template<class CharT, class Traits = std::char_traits<CharT>> string_type string::BasicQuickStream< CharT, Traits >::source private
Source string.
Definition at line 268 of file quickstream.hpp.
Referenced by string::BasicQuickStream< char >::BasicQuickStream(), string::BasicQuickStream< char >::clear(), string::BasicQuickStream< char >::eof(), string::BasicQuickStream< char >::get_int(), string::BasicQuickStream< char >::get_line(), string::BasicQuickStream< char >::ignore(), string::BasicQuickStream< char >::next(), string::BasicQuickStream< char >::operator bool(), string::BasicQuickStream< char >::peek(), string::BasicQuickStream< char >::regex_match(), and string::BasicQuickStream< char >::str().
The documentation for this class was generated from the following file:
src/string/quickstream.hpp