MelanoBot: string::BasicTrie< MappedType >::iterator Class Reference
string::BasicTrie< MappedType >::iterator Class Reference
Handle to the node.
#include <trie.hpp>
Public Member Functions
iterator ()
bool valid () const
Whether the iterator is valid O(1)
void move_up ()
Move up the trie O(1)
void move_down (char c)
Move down the trie Average: O(1) Worst: O(number of children)
bool can_move_down (char c)
Whether it can move down the tree Average: O(1) Worst: O(number of children)
bool root () const
Whether the node the root O(1)
bool accepts () const
Whether the node accepts the input O(1)
int depth () const
Depth of the node / length of the prefix O(1)
MappedType data ()
Private Member Functions
iterator (TrieNode *node)
Private Attributes
TrieNode * node {nullptr}
Node handled by the iterator.
Friends
class BasicTrie
Detailed Description
template<class MappedType>
class string::BasicTrie< MappedType >::iterator
Handle to the node.
Definition at line 182 of file trie.hpp.
Constructor & Destructor Documentation
template<class MappedType > string::BasicTrie< MappedType >::iterator::iterator () inline
Definition at line 185 of file trie.hpp.
Referenced by string::replace().
template<class MappedType > string::BasicTrie< MappedType >::iterator::iterator (TrieNode * node) inline private
Definition at line 261 of file trie.hpp.
Member Function Documentation
template<class MappedType > bool string::BasicTrie< MappedType >::iterator::accepts () const inline
Whether the node accepts the input O(1)
Definition at line 238 of file trie.hpp.
Referenced by string::replace().
template<class MappedType > bool string::BasicTrie< MappedType >::iterator::can_move_down (char c) inline
Whether it can move down the tree Average: O(1) Worst: O(number of children)
Definition at line 220 of file trie.hpp.
Referenced by string::replace().
template<class MappedType > MappedType string::BasicTrie< MappedType >::iterator::data () inline
Definition at line 252 of file trie.hpp.
Referenced by string::replace().
template<class MappedType > int string::BasicTrie< MappedType >::iterator::depth () const inline
Depth of the node / length of the prefix O(1)
Definition at line 247 of file trie.hpp.
Referenced by string::replace().
template<class MappedType > void string::BasicTrie< MappedType >::iterator::move_down (char c) inline
Move down the trie Average: O(1) Worst: O(number of children)
Definition at line 210 of file trie.hpp.
Referenced by string::replace().
template<class MappedType > void string::BasicTrie< MappedType >::iterator::move_up () inline
Move up the trie O(1)
Definition at line 200 of file trie.hpp.
template<class MappedType > bool string::BasicTrie< MappedType >::iterator::root () const inline
Whether the node the root O(1)
Definition at line 229 of file trie.hpp.
template<class MappedType > bool string::BasicTrie< MappedType >::iterator::valid () const inline
Whether the iterator is valid O(1)
Definition at line 191 of file trie.hpp.
Referenced by string::replace().
Friends And Related Function Documentation
template<class MappedType > friend class BasicTrie friend
Definition at line 263 of file trie.hpp.
Referenced by string::BasicTrie< MappedType >::find(), string::BasicTrie< MappedType >::recurse(), string::replace(), and string::BasicTrie< MappedType >::root().
Member Data Documentation
template<class MappedType > TrieNode* string::BasicTrie< MappedType >::iterator::node {nullptr} private
Node handled by the iterator.
Definition at line 259 of file trie.hpp.
Referenced by string::BasicTrie< MappedType >::iterator::accepts(), string::BasicTrie< MappedType >::iterator::can_move_down(), string::BasicTrie< MappedType >::iterator::data(), string::BasicTrie< MappedType >::iterator::depth(), string::BasicTrie< MappedType >::iterator::iterator(), string::BasicTrie< MappedType >::iterator::move_down(), string::BasicTrie< MappedType >::iterator::move_up(), string::BasicTrie< MappedType >::iterator::root(), and string::BasicTrie< MappedType >::iterator::valid().
The documentation for this class was generated from the following file:
src/string/trie.hpp