MelanoBot: handler::SimpleAction Class Reference
handler::SimpleAction Class Reference
A simple action sends a message to the same connection it came from.
#include <handler.hpp>
Public Member Functions
SimpleAction (const std::string &default_trigger, const Settings &settings, handler::HandlerContainer *parent)
Sets up the trigger.
bool can_handle (const network::Message &msg) const override
virtual bool handle (network::Message &msg) override
std::string get_property (const std::string &name) const override
Public Member Functions inherited from handler::Handler
Handler (const Settings &settings, HandlerContainer *parent)
Handler (const Handler &)=delete
Handler & operator= (const Handler &)=delete
virtual ~Handler ()
Melanobot * melanobot () const final
Get the top-level bot for this HandlerContainer.
virtual void initialize ()
Called at startup in case it needs to perform some initialization.
virtual void finalize ()
Called when the connection ends.
void populate_properties (const std::vector< std::string > &properties, PropertyTree &output) const override
Simply appends globally the given property.
Public Member Functions inherited from handler::HandlerContainer
virtual ~HandlerContainer ()
Protected Member Functions
std::string reply_channel (const network::Message &msg) const override
Returns the preferred output channel for the given message.
Protected Member Functions inherited from handler::Handler
virtual bool on_handle (network::Message &msg)=0
Required for concrete handlers, performs the handler actions.
virtual void reply_to (const network::Message &input, network::OutputMessage output) const
Send a reply to a message.
void reply_to (const network::Message &msg, const string::FormattedString &text) const
void reply_to (const network::Message &msg, const std::string &text) const
template<class HandlerT >
HandlerT * get_parent () const
Find the parent handler with the given type.
Protected Attributes
std::string trigger
String identifying the action.
bool direct = false
Whether the message needs to be direct.
std::string synopsis
Help synopsis (uses FormatterConfig)
std::string help ="Undocumented"
Help string (uses FormatterConfig)
bool public_reply = true
Whether to reply publicly or just to the sender of the message.
Protected Attributes inherited from handler::Handler
int priority {0}
Message priority.
Melanobot * bot {nullptr}
Pointer to the main bot.
Handler * parent_handler {nullptr}
Pointer to a handler containing this one.
Detailed Description
A simple action sends a message to the same connection it came from.
Follows the most basic example to define a SimpleAction handler:
class MyAction : public handler::SimpleAction
{
public:
    MyAction(const Settings& settings, handler::HandlerContainer* parent)
        : SimpleAction("default_handler",settings,parent)
    {
        some_setting = settings.get("some_setting",some_setting);
        synopsis += " text...";
        help = "Help message for MyAction";
    }
protected:
    bool on_handle(network::Message& msg) override
    {
        reply_to(msg,"I got: \""+msg.message+"\" from "+msg.from.name);
        return true;
    }
private:
    std::string some_setting = "Default value";
};
module.register_handler<MyAction>("MyAction");
Definition at line 233 of file handler.hpp.
Constructor & Destructor Documentation
handler::SimpleAction::SimpleAction (const std::string & default_trigger, const Settings & settings, handler::HandlerContainer * parent) inline
Sets up the trigger.
Parameters
default_trigger Default value for trigger (must not be empty)
settings Settings
bot Pointer to the bot instance (cannot be null)
Exceptions
ConfigurationError If the requirements stated above are not met
Todo:
flag saying whether there must be a space after the trigger (default true)
Definition at line 244 of file handler.hpp.
Referenced by handler::AbstractList::AbstractList(), handler::Action::Action(), handler::AdminConnect::AdminConnect(), handler::AdminDisconnect::AdminDisconnect(), irc::handler::AdminJoin::AdminJoin(), irc::handler::AdminNick::AdminNick(), irc::handler::AdminPart::AdminPart(), handler::AdminQuit::AdminQuit(), irc::handler::AdminRaw::AdminRaw(), handler::AdminReconnect::AdminReconnect(), handler::BridgeAttach::BridgeAttach(), handler::BridgeAttachChannel::BridgeAttachChannel(), handler::Cointoss::Cointoss(), handler::Echo::Echo(), handler::Help::Help(), handler::License::License(), handler::ListClear::ListClear(), handler::ListInsert::ListInsert(), handler::ListRemove::ListRemove(), xonotic::RconCommand::RconCommand(), handler::ServerHost::ServerHost(), handler::SimpleGroup::SimpleGroup(), handler::SimpleWebApi::SimpleWebApi(), handler::Time::Time(), and irc::handler::WhoisCheckMe::WhoisCheckMe().
Member Function Documentation
bool handler::SimpleAction::can_handle (const network::Message & msg) const inline override virtual
Checks authorization, direct, trigger and available reply channels.
Reimplemented from handler::Handler.
Reimplemented in irc::handler::WhoisCheckMe, and handler::SimpleGroup.
Definition at line 257 of file handler.hpp.
Referenced by irc::handler::WhoisCheckMe::can_handle(), and handle().
std::string handler::SimpleAction::get_property (const std::string & name) const inline override virtual
Extra properties:
trigger
name (same as trigger)
direct
help
synopsis
Reimplemented from handler::Handler.
Reimplemented in handler::Action, handler::AbstractList, handler::AdminGroup, and handler::SimpleGroup.
Definition at line 292 of file handler.hpp.
Referenced by handler::SimpleGroup::get_property(), handler::AbstractList::get_property(), and handler::Action::get_property().
virtual bool handler::SimpleAction::handle (network::Message & msg) inline override virtual
Checks with can_handle(), then creates a new message which will have the trigger stripped off and calls on_handle() with that.
Reimplemented from handler::Handler.
Definition at line 268 of file handler.hpp.
std::string handler::SimpleAction::reply_channel (const network::Message & msg) const inline override protected virtual
Returns the preferred output channel for the given message.
If msg comes from multiple channels, the first one is used
Reimplemented from handler::Handler.
Definition at line 313 of file handler.hpp.
Member Data Documentation
bool handler::SimpleAction::direct = false protected
Whether the message needs to be direct.
Definition at line 308 of file handler.hpp.
Referenced by handler::SimpleGroup::can_handle(), can_handle(), get_property(), and SimpleAction().
std::string handler::SimpleAction::help ="Undocumented" protected
Help string (uses FormatterConfig)
Definition at line 310 of file handler.hpp.
Referenced by handler::Action::Action(), handler::AdminConnect::AdminConnect(), handler::AdminDisconnect::AdminDisconnect(), irc::handler::AdminJoin::AdminJoin(), irc::handler::AdminNick::AdminNick(), irc::handler::AdminPart::AdminPart(), handler::AdminQuit::AdminQuit(), irc::handler::AdminRaw::AdminRaw(), handler::AdminReconnect::AdminReconnect(), handler::Cointoss::Cointoss(), handler::Echo::Echo(), get_property(), handler::Help::Help(), handler::License::License(), handler::ListClear::ListClear(), handler::ListInsert::ListInsert(), handler::ListRemove::ListRemove(), xonotic::RconCommand::RconCommand(), handler::SimpleGroup::SimpleGroup(), and handler::Time::Time().
bool handler::SimpleAction::public_reply = true protected
Whether to reply publicly or just to the sender of the message.
Definition at line 311 of file handler.hpp.
Referenced by reply_channel(), and SimpleAction().
std::string handler::SimpleAction::synopsis protected
Help synopsis (uses FormatterConfig)
Definition at line 309 of file handler.hpp.
Referenced by handler::Action::Action(), handler::AdminDisconnect::AdminDisconnect(), irc::handler::AdminJoin::AdminJoin(), irc::handler::AdminNick::AdminNick(), irc::handler::AdminPart::AdminPart(), handler::AdminQuit::AdminQuit(), irc::handler::AdminRaw::AdminRaw(), handler::AdminReconnect::AdminReconnect(), handler::Cointoss::Cointoss(), handler::Echo::Echo(), get_property(), handler::Help::Help(), handler::ListInsert::ListInsert(), handler::ListRemove::ListRemove(), xonotic::RconCommand::RconCommand(), SimpleAction(), handler::SimpleGroup::SimpleGroup(), and handler::Time::Time().
std::string handler::SimpleAction::trigger protected
String identifying the action.
Definition at line 307 of file handler.hpp.
Referenced by handler::AdminGroup::add(), handler::AdminGroup::AdminGroup(), handler::SimpleGroup::can_handle(), can_handle(), handler::AdminGroup::elements(), get_property(), handle(), handler::AdminGroup::remove(), SimpleAction(), and handler::SimpleGroup::SimpleGroup().
The documentation for this class was generated from the following file:
src/handler/handler.hpp