MelanoBot: Settings Class Reference
Settings Class Reference
Class containing hierarchical settings.
#include <settings.hpp>
Public Types
enum FileFormat {
FileFormat::AUTO, FileFormat::JSON, FileFormat::INI, FileFormat::XML,
FileFormat::INFO
}
File format used to open/save settings.
typedef boost::property_tree::ptree PTree
Public Member Functions
Settings ()
Settings (const PTree &p)
Settings (const std::string &file_name, FileFormat format=FileFormat::AUTO)
Load settings from file.
bool has_child (const path_type &path) const
Whether a child node/property exists.
void merge_child (const path_type &path, const Settings &child, bool overwrite)
Merge a child node with the supplied values.
Static Public Member Functions
static Settings initialize (int argc, char **argv)
Parses the program options and returns the configurations.
static std::string find_config (FileFormat format=FileFormat::AUTO)
Tries to find a file from which settings can be loaded.
Static Public Attributes
static Settings global_settings
Settings with global information.
Static Private Member Functions
static std::string find_config (const std::string &dir, FileFormat format)
Tries to find a config file in the given directory.
Static Private Attributes
static std::unordered_map
< std::string, FileFormat > format_extension
Maps extensions to file formats.
Detailed Description
Class containing hierarchical settings.
Definition at line 32 of file settings.hpp.
Member Typedef Documentation
typedef boost::property_tree::ptree Settings::PTree
Definition at line 35 of file settings.hpp.
Member Enumeration Documentation
enum Settings::FileFormat strong
File format used to open/save settings.
Enumerator
AUTO
Deduce automatically.
JSON
INI
XML
INFO
Definition at line 40 of file settings.hpp.
Constructor & Destructor Documentation
Settings::Settings () inline
Definition at line 66 of file settings.hpp.
Referenced by initialize().
Settings::Settings (const PTree & p) inline
Definition at line 67 of file settings.hpp.
Settings::Settings (const std::string & file_name, FileFormat format = FileFormat::AUTO) explicit
Load settings from file.
Exceptions
CriticalException If file_name isn't valid
Definition at line 132 of file settings.cpp.
Referenced by initialize().
Member Function Documentation
std::string Settings::find_config (FileFormat format = FileFormat::AUTO) static
Tries to find a file from which settings can be loaded.
Definition at line 196 of file settings.cpp.
Referenced by initialize().
std::string Settings::find_config (const std::string & dir, FileFormat format) static private
Tries to find a config file in the given directory.
Definition at line 171 of file settings.cpp.
Referenced by find_config().
bool Settings::has_child (const path_type & path) const inline
Whether a child node/property exists.
Definition at line 78 of file settings.hpp.
Referenced by handler::SearchWebSearx::json_success(), and merge_child().
Settings Settings::initialize (int argc, char ** argv) static
Parses the program options and returns the configurations.
It will also load the logger configuration
Definition at line 42 of file settings.cpp.
Referenced by main().
void Settings::merge_child (const path_type & path, const Settings & child, bool overwrite) inline
Merge a child node with the supplied values.
Parameters
path Path to the child
child Node with the properties to be read
overwrite If true all of the properties of child will be used, if false, only those not already found in the tree
Definition at line 90 of file settings.hpp.
Referenced by handler::SimpleGroup::SimpleGroup().
Member Data Documentation
std::unordered_map< std::string, Settings::FileFormat > Settings::format_extension static private
Initial value:
= {
    {".json",FileFormat::JSON},
    {".info",FileFormat::INFO},
    {".xml",FileFormat::XML},
    {".ini",FileFormat::INI},
}
Maps extensions to file formats.
Definition at line 105 of file settings.hpp.
Referenced by Settings().
Settings Settings::global_settings static
Settings with global information.
Definition at line 52 of file settings.hpp.
Referenced by find_config(), handler::SimpleJson::http_success(), initialize(), handler::License::License(), and main().
The documentation for this class was generated from the following files:
src/settings.hpp
src/settings.cpp