MelanoBot: StdinConnection Class Reference
StdinConnection Class Reference
Acts as a network connection to handle standard input.
#include <stdin.hpp>
Public Member Functions
StdinConnection (Melanobot *bot, const Settings &settings)
~StdinConnection ()
void stop () override
Disconnect and stop all processing.
void start () override
Start processing messages.
string::Formatter * formatter () const override
Get the string formatter.
std::string protocol () const override
Protocol identifier.
std::string name () const override
Name of the service provided by this connection, as seen by the handled protocol.
network::Server server () const override
Returns the server object to which this connection is connected to.
std::string description () const override
Returns a 1-line description of the connection (including server info)
void say (const network::OutputMessage &msg) override
Sends a message to the given channel.
Status status () const override
Returns the connection status.
void connect () override
Initialize the connection.
void disconnect (const std::string &) override
Close the connection.
void reconnect (const std::string &) override
Disconnect and connect again.
bool channel_mask (const std::vector< std::string > &, const std::string &) const override
Whether a list of channels matches the mask (Meaning depends on the specialized class)
bool user_auth (const std::string &, const std::string &) const override
Get whether a user has the given authorization level.
void update_user (const std::string &, const Properties &) override
Update the properties of a user by local_id.
user::User get_user (const std::string &) const override
Returns a copy of the user object identified by local_id.
std::vector< user::User > get_users (const std::string &) const override
Get a vector with the users in the given channel or all the users if empty.
bool add_to_group (const std::string &, const std::string &) override
Adds a user identified by user to the group group.
bool remove_from_group (const std::string &, const std::string &) override
Removes a user identified by user to the group group.
std::vector< user::User > users_in_group (const std::string &) const override
Get a vector with the users in the given group.
std::string get_property (const std::string &) const override
Get a connection property.
bool set_property (const std::string &, const std::string &) override
Set a connection property.
void command (network::Command) override
Schedules a command for execution.
Public Member Functions inherited from network::Connection
Connection ()=default
Connection (const Connection &)=delete
Connection (Connection &&)=delete
Connection & operator= (const Connection &)=delete
Connection & operator= (Connection &&)=delete
virtual ~Connection ()
Static Public Member Functions
static std::unique_ptr
< StdinConnection > create (Melanobot *bot, const Settings &settings)
Private Member Functions
void run ()
void schedule_read ()
void on_read_line (const boost::system::error_code &error)
Private Attributes
Melanobot * bot
string::Formatter * formatter_
boost::asio::streambuf buffer_read
boost::asio::io_service io_service
boost::asio::posix::stream_descriptor input {io_service, STDOUT_FILENO}
std::thread thread
Additional Inherited Members
Public Types inherited from network::Connection
enum Status {
DISCONNECTED, WAITING, CONNECTING, CHECKING,
CONNECTED
}
using AtomicStatus = std::atomic< Status >
Detailed Description
Acts as a network connection to handle standard input.
Definition at line 35 of file stdin.hpp.
Constructor & Destructor Documentation
StdinConnection::StdinConnection (Melanobot * bot, const Settings & settings) inline
Definition at line 43 of file stdin.hpp.
StdinConnection::~StdinConnection () inline
Definition at line 49 of file stdin.hpp.
Member Function Documentation
bool StdinConnection::add_to_group (const std::string & user, const std::string & group) inline override virtual
Adds a user identified by user to the group group.
Parameters
user The user local_id, derived classes may perform some parsing to interpret it as a host or global_id
group Group name
Implements network::Connection.
Definition at line 96 of file stdin.hpp.
bool StdinConnection::channel_mask (const std::vector< std::string > & channels, const std::string & mask) const inline override virtual
Whether a list of channels matches the mask (Meaning depends on the specialized class)
Implements network::Connection.
Definition at line 91 of file stdin.hpp.
void StdinConnection::command (network::Command cmd) inline override virtual
Schedules a command for execution.
Implements network::Connection.
Definition at line 102 of file stdin.hpp.
void StdinConnection::connect () inline override virtual
Initialize the connection.
Implements network::Connection.
Definition at line 88 of file stdin.hpp.
static std::unique_ptr<StdinConnection> StdinConnection::create (Melanobot * bot, const Settings & settings) inline static
Definition at line 38 of file stdin.hpp.
std::string StdinConnection::description () const inline override virtual
Returns a 1-line description of the connection (including server info)
Implements network::Connection.
Definition at line 79 of file stdin.hpp.
void StdinConnection::disconnect (const std::string & message) inline override virtual
Close the connection.
Implements network::Connection.
Definition at line 89 of file stdin.hpp.
string::Formatter* StdinConnection::formatter () const inline override virtual
Get the string formatter.
Implements network::Connection.
Definition at line 70 of file stdin.hpp.
std::string StdinConnection::get_property (const std::string & property) const inline override virtual
Get a connection property.
Implements network::Connection.
Definition at line 100 of file stdin.hpp.
user::User StdinConnection::get_user (const std::string & local_id) const inline override virtual
Returns a copy of the user object identified by local_id.
Returns
A copy of the internal record identifying the user or an empty object if the user is not found.
Implements network::Connection.
Definition at line 94 of file stdin.hpp.
std::vector<user::User> StdinConnection::get_users (const std::string & channel_mask) const inline override virtual
Get a vector with the users in the given channel or all the users if empty.
Implements network::Connection.
Definition at line 95 of file stdin.hpp.
std::string StdinConnection::name () const inline override virtual
Name of the service provided by this connection, as seen by the handled protocol.
Implements network::Connection.
Definition at line 77 of file stdin.hpp.
Referenced by on_read_line().
void StdinConnection::on_read_line (const boost::system::error_code & error) inline private
Definition at line 130 of file stdin.hpp.
Referenced by schedule_read().
std::string StdinConnection::protocol () const inline override virtual
Protocol identifier.
Implements network::Connection.
Definition at line 76 of file stdin.hpp.
void StdinConnection::reconnect (const std::string & quit_message) inline override virtual
Disconnect and connect again.
Implements network::Connection.
Definition at line 90 of file stdin.hpp.
bool StdinConnection::remove_from_group (const std::string & user, const std::string & group) inline override virtual
Removes a user identified by user to the group group.
Parameters
user The user local_id, derived classes may perform some parsing to interpret it as a host or global_id
group Group name
Implements network::Connection.
Definition at line 97 of file stdin.hpp.
void StdinConnection::run () inline private
Definition at line 112 of file stdin.hpp.
Referenced by start().
void StdinConnection::say (const network::OutputMessage & message) inline override virtual
Sends a message to the given channel.
Implements network::Connection.
Definition at line 81 of file stdin.hpp.
void StdinConnection::schedule_read () inline private
Definition at line 124 of file stdin.hpp.
Referenced by on_read_line(), and run().
network::Server StdinConnection::server () const inline override virtual
Returns the server object to which this connection is connected to.
Implements network::Connection.
Definition at line 78 of file stdin.hpp.
bool StdinConnection::set_property (const std::string & property, const std::string & value) inline override virtual
Set a connection property.
Returns
true on success
Implements network::Connection.
Definition at line 101 of file stdin.hpp.
void StdinConnection::start () inline override virtual
Start processing messages.
Reimplemented from network::Connection.
Definition at line 62 of file stdin.hpp.
Status StdinConnection::status () const inline override virtual
Returns the connection status.
Implements network::Connection.
Definition at line 87 of file stdin.hpp.
void StdinConnection::stop () inline override virtual
Disconnect and stop all processing.
Reimplemented from network::Connection.
Definition at line 55 of file stdin.hpp.
Referenced by ~StdinConnection().
void StdinConnection::update_user (const std::string & local_id, const Properties & properties) inline override virtual
Update the properties of a user by local_id.
Implements network::Connection.
Definition at line 93 of file stdin.hpp.
bool StdinConnection::user_auth (const std::string & local_id, const std::string & auth_group) const inline override virtual
Get whether a user has the given authorization level.
Implements network::Connection.
Definition at line 92 of file stdin.hpp.
std::vector<user::User> StdinConnection::users_in_group (const std::string & group) const inline override virtual
Get a vector with the users in the given group.
Implements network::Connection.
Definition at line 98 of file stdin.hpp.
Member Data Documentation
Melanobot* StdinConnection::bot private
Definition at line 105 of file stdin.hpp.
Referenced by on_read_line(), run(), and StdinConnection().
boost::asio::streambuf StdinConnection::buffer_read private
Definition at line 107 of file stdin.hpp.
Referenced by on_read_line(), and schedule_read().
string::Formatter* StdinConnection::formatter_ private
Definition at line 106 of file stdin.hpp.
Referenced by formatter(), on_read_line(), and StdinConnection().
boost::asio::posix::stream_descriptor StdinConnection::input {io_service, STDOUT_FILENO} private
Definition at line 109 of file stdin.hpp.
Referenced by schedule_read().
boost::asio::io_service StdinConnection::io_service private
Definition at line 108 of file stdin.hpp.
std::thread StdinConnection::thread private
Definition at line 110 of file stdin.hpp.
The documentation for this class was generated from the following file:
modules/posix/stdin.hpp