MelanoBot: user::UserGroup Class Reference
user::UserGroup Class Reference
A group of users.
#include <user_group.hpp>
Public Member Functions
void add_user (const User &user)
Add a user to the group.
void remove_user (const User &user)
Remove the user from the group.
bool contains (const User &user) const
Whether the user is in the group or any of its children.
void add_child (UserGroup *child)
Adds a child group.
std::vector< User > direct_users () const
Users directly in this group.
std::vector< User > all_users () const
Users in this group or in its children.
Private Attributes
std::vector< User > users
List of users.
std::vector< UserGroup * > children
Groups which inherit this group.
Detailed Description
A group of users.
Definition at line 31 of file user_group.hpp.
Member Function Documentation
void user::UserGroup::add_child (UserGroup * child)
Adds a child group.
The child group will inherit the same access as this group
Note
Always keep the structure as a tree, not doing so will mess up
Definition at line 55 of file user_group.cpp.
Referenced by user::AuthSystem::grant_access().
void user::UserGroup::add_user (const User & user)
Add a user to the group.
The way users are matched depends on which attributes user has set.
In order of priority, it will look for: global_id, host, name
If a previously added user matches user, it won't be inserted
Definition at line 24 of file user_group.cpp.
Referenced by user::AuthSystem::add_user().
std::vector< User > user::UserGroup::all_users () const
Users in this group or in its children.
Definition at line 68 of file user_group.cpp.
Referenced by all_users(), and user::AuthSystem::users_with_auth().
bool user::UserGroup::contains (const User & user) const
Whether the user is in the group or any of its children.
Definition at line 44 of file user_group.cpp.
Referenced by contains(), and user::AuthSystem::in_group().
std::vector< User > user::UserGroup::direct_users () const
Users directly in this group.
Definition at line 63 of file user_group.cpp.
Referenced by all_users().
void user::UserGroup::remove_user (const User & user)
Remove the user from the group.
Removes all matching users.
Definition at line 32 of file user_group.cpp.
Referenced by user::AuthSystem::remove_user().
Member Data Documentation
std::vector<UserGroup*> user::UserGroup::children private
Groups which inherit this group.
Definition at line 79 of file user_group.hpp.
Referenced by add_child().
std::vector<User> user::UserGroup::users private
List of users.
Definition at line 78 of file user_group.hpp.
Referenced by add_user(), direct_users(), and remove_user().
The documentation for this class was generated from the following files:
src/user/user_group.hpp
src/user/user_group.cpp