MelanoBot: string::Unicode Class Reference
string::Unicode Class Reference
Unicode point.
#include <string.hpp>
Public Member Functions
Unicode (std::string utf8, uint32_t point)
std::string to_string (const Formatter &formatter) const override
Visitor format to string.
const std::string & utf8 () const
uint32_t point () const
Public Member Functions inherited from string::Element
virtual ~Element ()
std::string to_string (Formatter *formatter) const
Private Attributes
std::string utf8_
uint32_t point_
Detailed Description
Unicode point.
Definition at line 374 of file string.hpp.
Constructor & Destructor Documentation
string::Unicode::Unicode (std::string utf8, uint32_t point) inline
Definition at line 377 of file string.hpp.
Member Function Documentation
uint32_t string::Unicode::point () const inline
Definition at line 386 of file string.hpp.
std::string string::Unicode::to_string (const Formatter & formatter) const inline override virtual
Visitor format to string.
Implements string::Element.
Definition at line 380 of file string.hpp.
const std::string& string::Unicode::utf8 () const inline
Definition at line 385 of file string.hpp.
Referenced by xonotic::Formatter::unicode(), string::FormatterUtf8::unicode(), and string::FormatterAnsi::unicode().
Member Data Documentation
uint32_t string::Unicode::point_ private
Definition at line 390 of file string.hpp.
Referenced by point(), and Unicode().
std::string string::Unicode::utf8_ private
Definition at line 389 of file string.hpp.
Referenced by Unicode(), and utf8().
The documentation for this class was generated from the following file:
src/string/string.hpp