MelanoBot: network::ServiceRegistry Class Reference
network::ServiceRegistry Class Reference
Class storing the service objects.
#include <async_service.hpp>
Classes
struct Entry
Registry entry, keeping track of loaded services.
struct RegisterService
Dummy class used to auto-register services.
Public Member Functions
void initialize (const Settings &settings)
Loads the service settings.
void start ()
Starts all services.
void stop ()
Stops all services.
AsyncService * service (const std::string &name) const
Get service by name.
Static Public Member Functions
static ServiceRegistry & instance ()
Private Member Functions
ServiceRegistry ()
ServiceRegistry (const ServiceRegistry &)=delete
Private Attributes
std::unordered_map
< std::string, Entry > services
Detailed Description
Class storing the service objects.
Note
It is assumed that the registered objects will clean up after themselves
Definition at line 181 of file async_service.hpp.
Constructor & Destructor Documentation
network::ServiceRegistry::ServiceRegistry () inline private
Definition at line 278 of file async_service.hpp.
Referenced by network::ServiceRegistry::RegisterService::RegisterService().
network::ServiceRegistry::ServiceRegistry (const ServiceRegistry &) private delete
Member Function Documentation
void network::ServiceRegistry::initialize (const Settings & settings) inline
Loads the service settings.
Definition at line 207 of file async_service.hpp.
Referenced by main().
static ServiceRegistry& network::ServiceRegistry::instance () inline static
Definition at line 198 of file async_service.hpp.
Referenced by main(), network::ServiceRegistry::RegisterService::RegisterService(), network::require_service(), and network::service().
AsyncService* network::ServiceRegistry::service (const std::string & name) const inline
Get service by name.
Definition at line 248 of file async_service.hpp.
Referenced by network::require_service(), and network::service().
void network::ServiceRegistry::start () inline
Starts all services.
Definition at line 228 of file async_service.hpp.
Referenced by main().
void network::ServiceRegistry::stop () inline
Stops all services.
Definition at line 238 of file async_service.hpp.
Referenced by main().
Member Data Documentation
std::unordered_map<std::string,Entry> network::ServiceRegistry::services private
Definition at line 276 of file async_service.hpp.
Referenced by initialize(), network::ServiceRegistry::RegisterService::RegisterService(), and service().
The documentation for this class was generated from the following file:
src/network/async_service.hpp