MelanoBot: network::Connection Class Reference
network::Connection Class Reference abstract
Abstract service connection.
#include <connection.hpp>
Public Types
enum Status {
DISCONNECTED, WAITING, CONNECTING, CHECKING,
CONNECTED
}
typedef std::atomic< Status > AtomicStatus
Public Member Functions
virtual ~Connection ()
virtual Server server () const =0
Returns the server object to which this connection is connected to.
virtual void command (const Command &cmd)=0
Schedules a command for execution.
virtual void say (const OutputMessage &message)=0
Sends a message to the given channel.
virtual Status status () const =0
Returns the connection status.
virtual std::string protocol () const =0
Protocol identifier.
virtual void connect ()=0
Initialize the connection.
virtual void disconnect (const std::string &message={})=0
Close the connection.
virtual void reconnect (const std::string &quit_message={})=0
Disconnect and connect again.
virtual void stop ()=0
Disconnect and stop all processing.
virtual void start ()=0
Start processing messages.
virtual string::Formatter * formatter () const =0
Get the string formatter.
virtual bool channel_mask (const std::vector< std::string > &channels, const std::string &mask) const =0
Whether a list of channels matches the mask (Meaning depends on the specialized class)
virtual bool user_auth (const std::string &local_id, const std::string &auth_group) const =0
Get whether a user has the given authorization level.
virtual void update_user (const std::string &local_id, const Properties &properties)=0
Update the properties of a user by local_id.
virtual user::User get_user (const std::string &local_id) const =0
Returns a copy of the user object identified by local_id.
virtual std::vector< user::User > get_users (const std::string &channel_mask="") const =0
Get a vector with the users in the given channel or all the users if empty.
virtual bool add_to_group (const std::string &user, const std::string &group)=0
Adds a user identified by user to the group group.
virtual bool remove_from_group (const std::string &user, const std::string &group)=0
Removes a user identified by user to the group group.
virtual std::vector< user::User > users_in_group (const std::string &group) const =0
Get a vector with the users in the given group.
virtual std::string name () const =0
Name of the service provided by this connection, as seen by the handled protocol.
virtual std::string get_property (const std::string &property) const =0
Get a connection property.
virtual bool set_property (const std::string &property, const std::string &value)=0
Set a connection property.
Detailed Description
Abstract service connection.
Instances of this class will be created by Melanobot from the configuration and will send Message objects and receive either Command or OutputMessage objects.
To create your own class, inherith this one and override the pure virtual methods. Then use REGISTER_CONNECTION() to register the class to the ConnectionFactory.
It is recommended that you add a static method called create in the derived class with the following signature:
YourClass* create(Melanobot* bot, const Settings& settings);
to be used with REGISTER_CONNECTION.
You should also have a corresponding log type to use for the connection, registered with REGISTER_LOG_TYPE().
Definition at line 205 of file connection.hpp.
Member Typedef Documentation
typedef std::atomic<Status> network::Connection::AtomicStatus
Definition at line 216 of file connection.hpp.
Member Enumeration Documentation
enum network::Connection::Status
Enumerator
DISCONNECTED
Connection is completely disconnected.
WAITING
Needs something before connecting.
CONNECTING
Needs some protocol action before becoming usable.
CHECKING
Connected, making sure the connection is alive.
CONNECTED
All set.
Definition at line 208 of file connection.hpp.
Constructor & Destructor Documentation
virtual network::Connection::~Connection () inline virtual
Definition at line 218 of file connection.hpp.
Member Function Documentation
virtual bool network::Connection::add_to_group (const std::string & user, const std::string & group) pure virtual
Adds a user identified by user to the group group.
Parameters
user The user local_id, derived classes may perform some parsing to interpret it as a host or global_id
group Group name
Implemented in network::irc::IrcConnection.
Referenced by handler::AdminGroup::add().
virtual bool network::Connection::channel_mask (const std::vector< std::string > & channels, const std::string & mask) const pure virtual
Whether a list of channels matches the mask (Meaning depends on the specialized class)
Implemented in network::irc::IrcConnection.
Referenced by handler::SimpleGroup::can_handle().
virtual void network::Connection::command (const Command & cmd) pure virtual
Schedules a command for execution.
Implemented in network::irc::IrcConnection.
Referenced by handler::AdminNick::on_handle(), handler::AdminJoin::on_handle(), handler::QSendWhois::on_handle(), handler::AdminPart::on_handle(), handler::AcceptInvite::on_handle(), handler::IrcKickRejoin::on_handle(), handler::AdminRaw::on_handle(), handler::WhoisCheckMe::on_handle(), and handler::CtcpBase::reply_to().
virtual void network::Connection::connect () pure virtual
Initialize the connection.
Implemented in network::irc::IrcConnection.
virtual void network::Connection::disconnect (const std::string & message = {}) pure virtual
Close the connection.
Implemented in network::irc::IrcConnection.
Referenced by handler::AdminQuit::on_handle().
virtual string::Formatter* network::Connection::formatter () const pure virtual
Get the string formatter.
Implemented in network::irc::IrcConnection.
Referenced by handler::BridgeChat::on_handle(), handler::ReverseText::on_handle(), and handler::CtcpBase::reply_to().
virtual std::string network::Connection::get_property (const std::string & property) const pure virtual
Get a connection property.
Implemented in network::irc::IrcConnection.
Referenced by handler::ServerHost::on_handle().
virtual user::User network::Connection::get_user (const std::string & local_id) const pure virtual
Returns a copy of the user object identified by local_id.
Returns
A copy of the internal record identifying the user or an empty object if the user is not found.
Implemented in network::irc::IrcConnection.
Referenced by handler::IrcJoinMessage::on_handle(), handler::QSendWhois::on_handle(), and handler::Reply::on_handle().
virtual std::vector<user::User> network::Connection::get_users (const std::string & channel_mask = "") const pure virtual
Get a vector with the users in the given channel or all the users if empty.
Implemented in network::irc::IrcConnection.
Referenced by handler::AnswerQuestions::on_handle().
virtual std::string network::Connection::name () const pure virtual
Name of the service provided by this connection, as seen by the handled protocol.
Implemented in network::irc::IrcConnection.
Referenced by handler::IrcJoinMessage::can_handle(), handler::BridgeChat::can_handle(), handler::IrcKickMessage::can_handle(), handler::IrcKickRejoin::can_handle(), handler::QSendWhois::on_handle(), and handler::AnswerQuestions::on_handle().
virtual std::string network::Connection::protocol () const pure virtual
Protocol identifier.
Implemented in network::irc::IrcConnection.
Referenced by handler::QSendWhois::can_handle(), handler::QGetWhois::can_handle(), and handler::WhoisCheckMe::can_handle().
virtual void network::Connection::reconnect (const std::string & quit_message = {}) pure virtual
Disconnect and connect again.
Implemented in network::irc::IrcConnection.
Referenced by handler::AdminReconnect::on_handle().
virtual bool network::Connection::remove_from_group (const std::string & user, const std::string & group) pure virtual
Removes a user identified by user to the group group.
Parameters
user The user local_id, derived classes may perform some parsing to interpret it as a host or global_id
group Group name
Implemented in network::irc::IrcConnection.
Referenced by handler::AdminGroup::remove().
virtual void network::Connection::say (const OutputMessage & message) pure virtual
Sends a message to the given channel.
Implemented in network::irc::IrcConnection.
Referenced by handler::BridgeChat::on_handle(), handler::Handler::reply_to(), and handler::SimpleAction::reply_to().
virtual Server network::Connection::server () const pure virtual
Returns the server object to which this connection is connected to.
Implemented in network::irc::IrcConnection.
Referenced by handler::ServerHost::on_handle().
virtual bool network::Connection::set_property (const std::string & property, const std::string & value) pure virtual
Set a connection property.
Returns
true on success
Implemented in network::irc::IrcConnection.
virtual void network::Connection::start () pure virtual
Start processing messages.
Implemented in network::irc::IrcConnection.
Referenced by Melanobot::run().
virtual Status network::Connection::status () const pure virtual
Returns the connection status.
Implemented in network::irc::IrcConnection.
virtual void network::Connection::stop () pure virtual
Disconnect and stop all processing.
Implemented in network::irc::IrcConnection.
Referenced by Melanobot::stop().
virtual void network::Connection::update_user (const std::string & local_id, const Properties & properties) pure virtual
Update the properties of a user by local_id.
Implemented in network::irc::IrcConnection.
Referenced by handler::Whois330::on_handle(), and handler::QGetWhois::on_handle().
virtual bool network::Connection::user_auth (const std::string & local_id, const std::string & auth_group) const pure virtual
Get whether a user has the given authorization level.
Implemented in network::irc::IrcConnection.
Referenced by handler::AdminGroup::add(), handler::Handler::authorized(), handler::Help::cleanup(), and handler::AdminGroup::remove().
virtual std::vector<user::User> network::Connection::users_in_group (const std::string & group) const pure virtual
Get a vector with the users in the given group.
Implemented in network::irc::IrcConnection.
Referenced by handler::AdminGroup::elements().
The documentation for this class was generated from the following file:
src/network/connection.hpp