MelanoBot: handler::SimpleJson Class Reference
handler::SimpleJson Class Reference abstract
Simple base class for handlers using AJAX web APIs.
#include <web-api.hpp>
Protected Member Functions
void request_json (const network::Message &msg, const network::Request &request)
Sends an asynchronous http request.
void http_success (const network::Message &msg, const network::Response &response) override
Called when request_http() gets a successfult response.
void http_failure (const network::Message &msg, const network::Response &) override
Called when request_http() fails.
virtual void json_success (const network::Message &msg, const Settings &parsed)=0
Called when the json request succeedes.
virtual void json_failure (const network::Message &)
Called when the json request fails.
Protected Member Functions inherited from handler::SimpleWebApi
void request_http (const network::Message &msg, const network::Request &request)
Sends an asynchronous http request.
Protected Member Functions inherited from handler::SimpleAction
std::string reply_channel (const network::Message &msg) const override
Returns the preferred output channel for the given message.
Protected Member Functions inherited from handler::Handler
virtual bool on_handle (network::Message &msg)=0
Required for concrete handlers, performs the handler actions.
virtual void reply_to (const network::Message &input, network::OutputMessage output) const
Send a reply to a message.
void reply_to (const network::Message &msg, const string::FormattedString &text) const
void reply_to (const network::Message &msg, const std::string &text) const
template<class HandlerT >
HandlerT * get_parent () const
Find the parent handler with the given type.
Additional Inherited Members
Public Member Functions inherited from handler::SimpleWebApi
SimpleWebApi (const std::string &default_trigger, const Settings &settings, handler::HandlerContainer *parent)
Public Member Functions inherited from handler::SimpleAction
SimpleAction (const std::string &default_trigger, const Settings &settings, handler::HandlerContainer *parent)
Sets up the trigger.
bool can_handle (const network::Message &msg) const override
virtual bool handle (network::Message &msg) override
std::string get_property (const std::string &name) const override
Public Member Functions inherited from handler::Handler
Handler (const Settings &settings, HandlerContainer *parent)
Handler (const Handler &)=delete
Handler & operator= (const Handler &)=delete
virtual ~Handler ()
Melanobot * melanobot () const final
Get the top-level bot for this HandlerContainer.
virtual void initialize ()
Called at startup in case it needs to perform some initialization.
virtual void finalize ()
Called when the connection ends.
virtual bool authorized (const network::Message &msg) const
Checks if a message is authorized to be executed by this message.
void populate_properties (const std::vector< std::string > &properties, PropertyTree &output) const override
Simply appends globally the given property.
Public Member Functions inherited from handler::HandlerContainer
virtual ~HandlerContainer ()
Protected Attributes inherited from handler::SimpleAction
std::string trigger
String identifying the action.
bool direct = false
std::string synopsis
Help synopsis.
std::string help ="Undocumented"
Help string.
bool public_reply = true
Whether to reply publicly or just to the sender of the message.
Protected Attributes inherited from handler::Handler
std::string auth
Authorization group required for a user message to be handled.
int priority {0}
Message priority.
Melanobot * bot {nullptr}
Pointer to the main bot.
Handler * parent_handler {nullptr}
Pointer to a handler containing this one.
Detailed Description
Simple base class for handlers using AJAX web APIs.
Definition at line 74 of file web-api.hpp.
Member Function Documentation
void handler::SimpleJson::http_failure (const network::Message & , const network::Response &) inline override protected virtual
Called when request_http() fails.
Reimplemented from handler::SimpleWebApi.
Definition at line 101 of file web-api.hpp.
void handler::SimpleJson::http_success (const network::Message & msg, const network::Response & response) inline override protected virtual
Called when request_http() gets a successfult response.
Implements handler::SimpleWebApi.
Definition at line 88 of file web-api.hpp.
virtual void handler::SimpleJson::json_failure (const network::Message &) inline protected virtual
Called when the json request fails.
Definition at line 114 of file web-api.hpp.
Referenced by http_failure(), and http_success().
virtual void handler::SimpleJson::json_success (const network::Message & msg, const Settings & parsed) protected pure virtual
Called when the json request succeedes.
Implemented in handler::SearchWebSearx, handler::UrbanDictionary, fun::ChuckNorris, handler::SearchImageGoogle, and handler::SearchVideoYoutube.
Referenced by http_success().
void handler::SimpleJson::request_json (const network::Message & msg, const network::Request & request) inline protected
Sends an asynchronous http request.
Definition at line 83 of file web-api.hpp.
Referenced by handler::SearchVideoYoutube::on_handle(), handler::SearchImageGoogle::on_handle(), handler::UrbanDictionary::on_handle(), and handler::SearchWebSearx::on_handle().
The documentation for this class was generated from the following file:
modules/web/web-api.hpp