MelanoBot: color::Color12 Class Reference
color::Color12 Class Reference
12 bit color
#include <color.hpp>
Public Types
using Component = uint8_t
Component type, will use 4 bits.
using BitMask = uint16_t
12 bit integer containing all 3 components
Public Member Functions
Color12 ()=default
Color12 (const Color12 &)=default
Color12 (Color12 &&)=default
Color12 & operator= (const Color12 &)=default
Color12 & operator= (Color12 &&)=default
SUPER_CONSTEXPR Color12 (BitMask mask)
SUPER_CONSTEXPR Color12 (Component r, Component g, Component b)
Creates a color from its rgb components.
Color12 (const std::string &s)
Creates a color from a hex string.
SUPER_CONSTEXPR bool is_valid () const
Whether the color is an actual color or invalid.
SUPER_CONSTEXPR BitMask to_bit_mask () const
Get the 12 bit mask.
Component to_4bit () const
Compress to 4 bits.
std::string to_html () const
Convert to a html color string.
SUPER_CONSTEXPR Component red () const
SUPER_CONSTEXPR Component green () const
SUPER_CONSTEXPR Component blue () const
SUPER_CONSTEXPR char hex_red () const
SUPER_CONSTEXPR char hex_green () const
SUPER_CONSTEXPR char hex_blue () const
Static Public Member Functions
static Color12 from_4bit (Component color)
Map a 4 bit color.
static SUPER_CONSTEXPR Color12 blend (Color12 c1, Color12 c2, double factor)
Blend two colors together.
static Color12 hsv (double h, double s, double v)
Get a color from HSV components in [0,1].
Static Private Member Functions
static SUPER_CONSTEXPR Component validate (Component c)
static SUPER_CONSTEXPR Component component_from_hex (char c)
static SUPER_CONSTEXPR char component_to_hex (Component c)
Private Attributes
bool valid = false
Component r = 0
Component g = 0
Component b = 0
Detailed Description
12 bit color
Definition at line 40 of file color.hpp.
Member Typedef Documentation
using color::Color12::BitMask = uint16_t
12 bit integer containing all 3 components
0xfff = white, 0xf00 = red, 0x0f0 = green, 0x00f = blue
Definition at line 52 of file color.hpp.
using color::Color12::Component = uint8_t
Component type, will use 4 bits.
Definition at line 45 of file color.hpp.
Constructor & Destructor Documentation
color::Color12::Color12 () default
Referenced by irc::FormatterIrc::color_from_string(), xonotic::Formatter::color_from_string(), and hsv().
color::Color12::Color12 (const Color12 &) default
color::Color12::Color12 (Color12 &&) default
Referenced by string::Color::Color().
SUPER_CONSTEXPR color::Color12::Color12 (BitMask mask) inline
Definition at line 61 of file color.hpp.
SUPER_CONSTEXPR color::Color12::Color12 (Component r, Component g, Component b) inline
Creates a color from its rgb components.
Definition at line 67 of file color.hpp.
Referenced by blend(), and hsv().
color::Color12::Color12 (const std::string & s) inline
Creates a color from a hex string.
Definition at line 72 of file color.hpp.
Referenced by xonotic::Formatter::color_from_string().
Member Function Documentation
static SUPER_CONSTEXPR Color12 color::Color12::blend (Color12 c1, Color12 c2, double factor) inline static
Blend two colors together.
Parameters
c1 First color
c2 Second color
factor Blend factor 0 => c1, 1 => c2
Definition at line 130 of file color.hpp.
SUPER_CONSTEXPR Component color::Color12::blue () const inline
Definition at line 118 of file color.hpp.
static SUPER_CONSTEXPR Component color::Color12::component_from_hex (char c) inline static private
Definition at line 144 of file color.hpp.
Referenced by Color12().
static SUPER_CONSTEXPR char color::Color12::component_to_hex (Component c) inline static private
Definition at line 154 of file color.hpp.
Referenced by hex_blue(), hex_green(), hex_red(), and to_html().
Color12 color::Color12::from_4bit (Component color) static
Map a 4 bit color.
least to most significant: red green blue bright
Definition at line 99 of file color.cpp.
Referenced by string::FormatterAnsi::decode().
SUPER_CONSTEXPR Component color::Color12::green () const inline
Definition at line 117 of file color.hpp.
SUPER_CONSTEXPR char color::Color12::hex_blue () const inline
Definition at line 121 of file color.hpp.
Referenced by xonotic::Formatter::color().
SUPER_CONSTEXPR char color::Color12::hex_green () const inline
Definition at line 120 of file color.hpp.
Referenced by xonotic::Formatter::color().
SUPER_CONSTEXPR char color::Color12::hex_red () const inline
Definition at line 119 of file color.hpp.
Referenced by xonotic::Formatter::color().
Color12 color::Color12::hsv (double h, double s, double v) static
Get a color from HSV components in [0,1].
Definition at line 129 of file color.cpp.
Referenced by fun::FormatterRainbow::decode().
SUPER_CONSTEXPR bool color::Color12::is_valid () const inline
Whether the color is an actual color or invalid.
Definition at line 86 of file color.hpp.
Referenced by irc::FormatterIrc::color(), xonotic::Formatter::color(), and string::FormatterAnsi::color().
Color12& color::Color12::operator= (const Color12 &) default
Referenced by Logger::register_direction().
Color12& color::Color12::operator= (Color12 &&) default
SUPER_CONSTEXPR Component color::Color12::red () const inline
Definition at line 116 of file color.hpp.
Color12::Component color::Color12::to_4bit () const
Compress to 4 bits.
least to most significant: red green blue bright
Definition at line 43 of file color.cpp.
Referenced by irc::FormatterIrc::color(), and string::FormatterAnsi::color().
SUPER_CONSTEXPR BitMask color::Color12::to_bit_mask () const inline
Get the 12 bit mask.
Definition at line 91 of file color.hpp.
Referenced by xonotic::Formatter::color().
std::string color::Color12::to_html () const
Convert to a html color string.
Definition at line 123 of file color.cpp.
static SUPER_CONSTEXPR Component color::Color12::validate (Component c) inline static private
Definition at line 143 of file color.hpp.
Referenced by Color12().
Member Data Documentation
Component color::Color12::b = 0 private
Definition at line 159 of file color.hpp.
Referenced by blend(), blue(), Color12(), hex_blue(), to_4bit(), to_bit_mask(), and to_html().
Component color::Color12::g = 0 private
Definition at line 158 of file color.hpp.
Referenced by blend(), Color12(), green(), hex_green(), to_4bit(), to_bit_mask(), and to_html().
Component color::Color12::r = 0 private
Definition at line 157 of file color.hpp.
Referenced by blend(), Color12(), hex_red(), red(), to_4bit(), to_bit_mask(), and to_html().
bool color::Color12::valid = false private
Definition at line 156 of file color.hpp.
Referenced by Color12(), is_valid(), and to_4bit().
The documentation for this class was generated from the following files:
src/string/color.hpp
src/string/color.cpp