MelanoBot: string::Formatter::FormatterFactory Class Reference
string::Formatter::FormatterFactory Class Reference
Internal factory.
Public Member Functions
FormatterFactory ()
~FormatterFactory ()
Formatter * formatter (const std::string &name)
Get a registered formatter.
void add_formatter (Formatter *instance)
Register a formatter.
Static Public Member Functions
static FormatterFactory & instance ()
Public Attributes
std::unordered_map
< std::string, Formatter * > formatters
Formatter * default_formatter = nullptr
Detailed Description
Internal factory.
Factory needs a singleton, Formatter is abstract so it needs a different class, but Formatter is the place to go to access the factory.
Also note that this doesn't really create objects since they don't need any data, so the objects are created only once.
Definition at line 191 of file string.hpp.
Constructor & Destructor Documentation
string::Formatter::FormatterFactory::FormatterFactory ()
Definition at line 159 of file string.cpp.
string::Formatter::FormatterFactory::~FormatterFactory () inline
Definition at line 202 of file string.hpp.
Member Function Documentation
void string::Formatter::FormatterFactory::add_formatter (Formatter * instance)
Register a formatter.
Definition at line 180 of file string.cpp.
Referenced by FormatterFactory(), and REGISTER_FORMATTER().
Formatter * string::Formatter::FormatterFactory::formatter (const std::string & name)
Get a registered formatter.
Exceptions
CriticalException If the formatter doesn't exist
Definition at line 167 of file string.cpp.
Referenced by string::Formatter::formatter().
static FormatterFactory& string::Formatter::FormatterFactory::instance () inline static
Definition at line 194 of file string.hpp.
Referenced by string::Formatter::formatter(), and REGISTER_FORMATTER().
Member Data Documentation
Formatter* string::Formatter::FormatterFactory::default_formatter = nullptr
Definition at line 220 of file string.hpp.
Referenced by add_formatter(), formatter(), and FormatterFactory().
std::unordered_map<std::string,Formatter*> string::Formatter::FormatterFactory::formatters
Definition at line 219 of file string.hpp.
Referenced by add_formatter(), and formatter().
The documentation for this class was generated from the following files:
src/string/string.hpp
src/string/string.cpp