MelanoBot: string::Inflector Class Reference
string::Inflector Class Reference
Class to perform simple pattern-based transformations.
#include <language.hpp>
Classes
struct Rule
Pattern/replacement pair.
Public Member Functions
Inflector (const std::initializer_list< Rule > &il)
Inflector (std::vector< std::pair< std::string, std::string >> rules, bool whole_words)
std::string inflect_all (std::string phrase)
Inflects a phrase.
std::string inflect_one (std::string phrase)
Inflects a phrase.
Private Attributes
std::vector< Rule > rules
Detailed Description
Class to perform simple pattern-based transformations.
Definition at line 31 of file language.hpp.
Constructor & Destructor Documentation
string::Inflector::Inflector (const std::initializer_list< Rule > & il) inline
Definition at line 51 of file language.hpp.
string::Inflector::Inflector (std::vector< std::pair< std::string, std::string >> rules, bool whole_words) inline
Definition at line 54 of file language.hpp.
Referenced by string::English::pronoun_to3rd().
Member Function Documentation
std::string string::Inflector::inflect_all (std::string phrase) inline
Inflects a phrase.
Parameters
phrase Phrase to inflect
Runs all the rules on the phrase
Definition at line 76 of file language.hpp.
Referenced by string::English::pronoun_to3rd().
std::string string::Inflector::inflect_one (std::string phrase) inline
Inflects a phrase.
Parameters
phrase Phrase to inflect
Runs the rules in order, stops at the first match
Note
phrase must match the regex to apply the rule
Definition at line 93 of file language.hpp.
Referenced by string::English::genitive(), string::English::imperate(), and string::English::pluralize().
Member Data Documentation
std::vector<Rule> string::Inflector::rules private
Definition at line 105 of file language.hpp.
Referenced by inflect_all(), inflect_one(), and Inflector().
The documentation for this class was generated from the following file:
src/string/language.hpp