MelanoBot: Multibuf Class Reference
Multibuf Class Reference
(Output) Stream buffer supporting multiple targets (defined by other buffers)
#include <multibuf.hpp>
Classes
struct MultibufItem
Buffer item.
Public Member Functions
Multibuf ()
Multibuf (const Multibuf &)=delete
Multibuf (Multibuf &&)=delete
Multibuf & operator= (const Multibuf &)=delete
Multibuf & operator= (Multibuf &&)=delete
~Multibuf ()
void push_buffer (std::streambuf *buffer, bool take_ownership=false)
Adds a buffer to the list of targets.
bool push_file (const std::string &name, std::ios::openmode mode=std::ios::out|std::ios::app)
Opens a file buffer and adds it to the list of targets.
Protected Member Functions
int overflow (int c) override
Writes c to the target buffers.
int sync () override
Calls sync on the target buffers.
Private Attributes
std::vector< MultibufItem * > buffers
Detailed Description
(Output) Stream buffer supporting multiple targets (defined by other buffers)
Definition at line 30 of file multibuf.hpp.
Constructor & Destructor Documentation
Multibuf::Multibuf () inline
Definition at line 33 of file multibuf.hpp.
Multibuf::Multibuf (const Multibuf &) delete
Multibuf::Multibuf (Multibuf &&) delete
Multibuf::~Multibuf () inline
Definition at line 39 of file multibuf.hpp.
Member Function Documentation
Multibuf& Multibuf::operator= (const Multibuf &) delete
Multibuf& Multibuf::operator= (Multibuf &&) delete
int Multibuf::overflow (int c) inline override protected
Writes c to the target buffers.
Definition at line 79 of file multibuf.hpp.
void Multibuf::push_buffer (std::streambuf * buffer, bool take_ownership = false) inline
Adds a buffer to the list of targets.
Parameters
buffer The buffer to add
take_ownership Whether this object shall handle the destruction of buffer
Definition at line 54 of file multibuf.hpp.
Referenced by Logger::Logger(), and push_file().
bool Multibuf::push_file (const std::string & name, std::ios::openmode mode = std::ios::out|std::ios::app) inline
Opens a file buffer and adds it to the list of targets.
Returns
Whether the file has been open successfully
Definition at line 63 of file multibuf.hpp.
Referenced by Logger::load_settings().
int Multibuf::sync () inline override protected
Calls sync on the target buffers.
Definition at line 89 of file multibuf.hpp.
Member Data Documentation
std::vector<MultibufItem*> Multibuf::buffers private
Definition at line 108 of file multibuf.hpp.
Referenced by push_buffer().
The documentation for this class was generated from the following file:
src/string/multibuf.hpp