MelanoBot: network::AsyncService Class Reference
network::AsyncService Class Reference abstract
Base class for external services that might take some time to execute.
#include <async_service.hpp>
Public Member Functions
virtual ~AsyncService ()
virtual void initialize (const Settings &settings)=0
Loads the service settings.
virtual void start ()=0
Starts the service.
virtual void stop ()=0
Stops the service.
virtual void async_query (const Request &request, const AsyncCallback &callback)=0
Asynchronous query.
virtual Response query (const Request &request)=0
Synchronous query.
virtual bool auto_load () const =0
Whether the service should be loaded without explicit configuration.
Protected Member Functions
AsyncService ()=default
AsyncService (const AsyncService &)=delete
AsyncService (AsyncService &&)=delete
AsyncService & operator= (const AsyncService &)=delete
AsyncService & operator= (AsyncService &&)=delete
Response ok (const std::string &contents, const Request &origin)
Quick way to create a successful response.
Response error (const std::string &error_message, const Request &origin)
Quick way to create a failure response.
Detailed Description
Base class for external services that might take some time to execute.
To specialize, inherit this class and register to ServiceRegistry using Melanomodule::register_service(). The derived classes should act as singletons.
You should also have a corresponding log type to use for the service, registered with Melanomodule::register_log_type().
Definition at line 70 of file async_service.hpp.
Constructor & Destructor Documentation
virtual network::AsyncService::~AsyncService () inline virtual
Definition at line 74 of file async_service.hpp.
network::AsyncService::AsyncService () protected default
network::AsyncService::AsyncService (const AsyncService &) protected delete
network::AsyncService::AsyncService (AsyncService &&) protected delete
Member Function Documentation
virtual void network::AsyncService::async_query (const Request & request, const AsyncCallback & callback) pure virtual
Asynchronous query.
Implemented in network::ThreadedAsyncService.
Referenced by handler::SimpleWebApi::request_http().
virtual bool network::AsyncService::auto_load () const pure virtual
Whether the service should be loaded without explicit configuration.
Implemented in network::http::HttpService.
Referenced by network::ServiceRegistry::register_service().
Response network::AsyncService::error (const std::string & error_message, const Request & origin) inline protected
Quick way to create a failure response.
Definition at line 127 of file async_service.hpp.
Referenced by network::http::HttpService::query().
virtual void network::AsyncService::initialize (const Settings & settings) pure virtual
Loads the service settings.
Implemented in network::http::HttpService.
Referenced by network::ServiceRegistry::initialize().
Response network::AsyncService::ok (const std::string & contents, const Request & origin) inline protected
Quick way to create a successful response.
Definition at line 117 of file async_service.hpp.
Referenced by network::http::HttpService::query().
AsyncService& network::AsyncService::operator= (const AsyncService &) protected delete
AsyncService& network::AsyncService::operator= (AsyncService &&) protected delete
virtual Response network::AsyncService::query (const Request & request) pure virtual
Synchronous query.
Implemented in network::http::HttpService.
virtual void network::AsyncService::start () pure virtual
Starts the service.
Implemented in network::ThreadedAsyncService.
Referenced by network::ServiceRegistry::start().
virtual void network::AsyncService::stop () pure virtual
Stops the service.
Implemented in network::ThreadedAsyncService.
Referenced by network::ServiceRegistry::stop().
The documentation for this class was generated from the following file:
src/network/async_service.hpp