MelanoBot: settings Namespace Reference
settings Namespace Reference
Enumerations
enum FileFormat {
FileFormat::AUTO, FileFormat::JSON, FileFormat::INI, FileFormat::XML,
FileFormat::INFO
}
File format used to open/save settings.
Functions
Settings initialize (int argc, char **argv)
Parses the program options and returns the configurations.
std::string find_config (FileFormat format=FileFormat::AUTO)
Tries to find a file from which settings can be loaded.
Settings load (const std::string &file_name, FileFormat format=FileFormat::AUTO)
Load settings from file.
bool has_child (const Settings &s, const Settings::path_type &path)
Whether a child node/property exists.
void merge (Settings &target, const Settings &source, bool overwrite)
Merge a node with the supplied values.
template<class Func >
void recurse (Settings &sett, const Func &func)
Recursively calls a functor on every node of the tree.
Variables
Settings global_settings
Settings with global information.
Enumeration Type Documentation
enum settings::FileFormat strong
File format used to open/save settings.
Enumerator
AUTO
Deduce automatically.
JSON
INI
XML
INFO
Definition at line 40 of file settings.hpp.
Function Documentation
std::string settings::find_config (FileFormat format = FileFormat::AUTO)
Tries to find a file from which settings can be loaded.
Definition at line 198 of file settings.cpp.
Referenced by initialize().
bool settings::has_child (const Settings & s, const Settings::path_type & path) inline
Whether a child node/property exists.
Definition at line 76 of file settings.hpp.
Referenced by handler::SearchWebSearx::json_success().
Settings settings::initialize (int argc, char ** argv)
Parses the program options and returns the configurations.
It will also load the logger configuration
Definition at line 42 of file settings.cpp.
Referenced by main().
Settings settings::load (const std::string & file_name, FileFormat format = FileFormat::AUTO)
Load settings from file.
Exceptions
CriticalException If file_name isn't valid
Definition at line 133 of file settings.cpp.
Referenced by initialize().
void settings::merge (Settings & target, const Settings & source, bool overwrite) inline
Merge a node with the supplied values.
Parameters
target Node to be overwritten
source Node with the properties to be read
overwrite If true all of the properties of source will be used, if false, only those not already found in the tree
Definition at line 88 of file settings.hpp.
Referenced by handler::SimpleGroup::SimpleGroup().
template<class Func > void settings::recurse (Settings & sett, const Func & func)
Recursively calls a functor on every node of the tree.
Definition at line 101 of file settings.hpp.
Referenced by handler::HandlerFactory::build_template().
Variable Documentation
Settings settings::global_settings
Settings with global information.
Definition at line 40 of file settings.cpp.
Referenced by network::ConnectionFactory::create(), irc::handler::CtcpSource::CtcpSource(), find_config(), initialize(), handler::License::License(), main(), Melanobot::Melanobot(), and JsonParser::parse_json_root().