MelanoBot: network::http Namespace Reference
network::http Namespace Reference
HTTP networking utilities.
Classes
class HttpService
HTTP Service.
Typedefs
using Parameters = std::map< std::string, std::string >
Request parameters.
Functions
std::string urlencode (const std::string &text)
Encode a string to make it fit to be used in a url.
std::string build_query (const Parameters &params)
Creates a query string from the given parameters.
Request get (const std::string &url, const Parameters &params=Parameters())
Creates a GET request.
Request post (const std::string &url, const Parameters &params=Parameters())
Creates a simple POST request.
Detailed Description
HTTP networking utilities.
Typedef Documentation
using network::http::Parameters = typedef std::map<std::string,std::string>
Request parameters.
Definition at line 36 of file http.hpp.
Function Documentation
std::string network::http::build_query (const Parameters & params)
Creates a query string from the given parameters.
Definition at line 52 of file http.cpp.
Referenced by get(), and post().
Request network::http::get (const std::string & url, const Parameters & params = Parameters())
Creates a GET request.
Definition at line 65 of file http.cpp.
Referenced by handler::SearchVideoYoutube::on_handle(), handler::SearchImageGoogle::on_handle(), handler::UrbanDictionary::on_handle(), and handler::SearchWebSearx::on_handle().
Request network::http::post (const std::string & url, const Parameters & params = Parameters())
Creates a simple POST request.
Definition at line 84 of file http.cpp.
std::string network::http::urlencode (const std::string & text)
Encode a string to make it fit to be used in a url.
Todo:
urldecode (?)
See also
http://www.faqs.org/rfcs/rfc3986.html
Definition at line 38 of file http.cpp.
Referenced by build_query().