MelanoBot: string Namespace Reference
string Namespace Reference
Namespace for string formatting.
Classes
class AsciiSubstring
Simple ASCII string.
class BasicTrie
Prefix Tree with optionally associated data.
class Character
Simple ASCII character.
class ClearFormatting
Simple class representing some code which will clear colors and formats.
class Color
Color code.
class Element
Generic element of a string.
class English
English language.
class Format
Formatting flag.
class FormatFlags
String formatting flags.
class FormattedString
A formatted string.
class Formatter
Abstract formatting visitor (and factory)
class FormatterAnsi
ANSI-formatted UTF-8 or ASCII.
class FormatterAscii
Plain ASCII.
class FormatterUtf8
Plain UTF-8.
class Inflector
Class to perform simple pattern-based transformations.
class Language
Inflects words to be used in a natural language.
class QFont
qfont character
class Unicode
Unicode point.
class Utf8Parser
Class used to parse and convert UTF-8.
Typedefs
using Trie = BasicTrie< void >
A trie with no associated data.
using StringTrie = BasicTrie< std::string >
A trie with string data.
Functions
std::string elide (std::string text, int length)
If the string is longer than length, truncates to the last word and adds an ellipsis.
std::string add_slashes (const std::string &input, const std::string &characters)
Escape all occurrences of characters with slashes.
std::string replace (const std::string &input, const std::string &from, const std::string &to)
Replace all occurrences of from in text to to.
bool simple_wildcard (const std::string &text, const std::string &pattern)
Checks if text matches the wildcard pattern.
std::vector< std::string > regex_split (const std::string &input, const std::regex &pattern, bool skip_empty=true)
Separate the string into components separated by pattern.
std::string::size_type similarity (const std::string &s1, const std::string &s2)
Returns a value representing how similar the two strings are.
unsigned long to_uint (const std::string &string, unsigned long base=10, unsigned long default_value=0)
Converts string to an unsigned integer.
std::string replace (const std::string &subject, const Properties &map, const std::string &prefix={})
Replaces the keys of map to the respective values in subject.
template<class Container >
std::string implode (const std::string &glue, const Container &elements)
Turn a container into a string.
bool starts_with (const std::string &haystack, const std::string &prefix)
Whether a string starts with the given prefix.
bool ends_with (const std::string &haystack, const std::string &suffix)
Whether a string ends with the given suffix.
std::string strtolower (std::string string)
String to lower case.
std::string strtoupper (std::string string)
String to upper case.
std::string collapse_spaces (const std::string &text)
Collapse all sequences of spaces to a single space character ' '.
std::string regex_escape (const std::string &input)
Escapes input to be inserted in a regex.
template<class Container , class = std::enable_if_t<!std::is_convertible<Container,std::string>::value>>
bool simple_wildcard (const Container &input, const std::string &pattern)
Checks if any of the elements in input matches the wildcard pattern.
std::vector< std::string > regex_split (const std::string &input, const std::string &pattern, bool skip_empty=true)
std::vector< std::string > comma_split (const std::string &input, bool skip_empty=true)
Split a string of element separated by commas and spaces.
bool is_one_of (const std::string &string, const std::initializer_list< std::string > &il)
Check if a string is one of a given set.
bool icase_equal (const std::string &a, const std::string &b) noexcept
Case-insensitive string comparison.
template<class T >
std::string to_string (T number, int digits=-1)
Converts a number to string padding with zeros to have at least digits digits.
template<class AssocContainer , class = std::enable_if_t<std::is_convertible<typename AssocContainer::key_type, std::string>::value>>
auto make_trie (const AssocContainer &container)
Builds a trie from an associative container.
template<class Container , class = void, class = std::enable_if_t<std::is_convertible<typename Container::value_type, std::string>::value>>
auto make_trie (const Container &container)
Builds a trie from a container.
Detailed Description
Namespace for string formatting.
Typedef Documentation
using string::StringTrie = typedef BasicTrie<std::string>
A trie with string data.
Definition at line 509 of file trie.hpp.
using string::Trie = typedef BasicTrie<void>
A trie with no associated data.
Definition at line 504 of file trie.hpp.
Function Documentation
std::string string::add_slashes (const std::string & input, const std::string & characters)
Escape all occurrences of characters with slashes.
Definition at line 40 of file string_functions.cpp.
Referenced by regex_escape(), and simple_wildcard().
std::string string::collapse_spaces (const std::string & text) inline
Collapse all sequences of spaces to a single space character ' '.
Definition at line 118 of file string_functions.hpp.
Referenced by handler::UrbanDictionary::json_success(), and handler::SearchWebSearx::json_success().
std::vector<std::string> string::comma_split (const std::string & input, bool skip_empty = true) inline
Split a string of element separated by commas and spaces.
Definition at line 191 of file string_functions.hpp.
Referenced by irc::handler::AdminJoin::on_handle(), and handler::Cointoss::on_handle().
std::string string::elide (std::string text, int length)
If the string is longer than length, truncates to the last word and adds an ellipsis.
Definition at line 24 of file string_functions.cpp.
Referenced by handler::UrbanDictionary::json_success(), and handler::SearchWebSearx::json_success().
bool string::ends_with (const std::string & haystack, const std::string & suffix) inline
Whether a string ends with the given suffix.
Definition at line 79 of file string_functions.hpp.
bool string::icase_equal (const std::string & a, const std::string & b) inline noexcept
Case-insensitive string comparison.
Definition at line 223 of file string_functions.hpp.
Referenced by timer::month_from_name(), and timer::weekday_from_name().
template<class Container > std::string string::implode (const std::string & glue, const Container & elements)
Turn a container into a string.
Precondition
Container::const_iterator is a ForwardIterator Container::value_type has the stream operator
Note
Should work on arrays just fine
Definition at line 40 of file string_functions.hpp.
Referenced by xonotic::XonoticConnection::command(), string::FormatterAnsi::format_flags(), handler::Help::on_handle(), handler::AbstractList::on_handle(), handler::ListInsert::on_handle(), and handler::ListRemove::on_handle().
bool string::is_one_of (const std::string & string, const std::initializer_list< std::string > & il) inline
Check if a string is one of a given set.
Definition at line 215 of file string_functions.hpp.
template<class AssocContainer , class = std::enable_if_t<std::is_convertible<typename AssocContainer::key_type, std::string>::value>> auto string::make_trie (const AssocContainer & container)
Builds a trie from an associative container.
Template Parameters
AssocContainer Associative container, AssocContainer::key_type convertible to string, AssocContainer::mapped_type is used as parameter for BasicTrie
Definition at line 518 of file trie.hpp.
Referenced by replace().
template<class Container , class = void, class = std::enable_if_t<std::is_convertible<typename Container::value_type, std::string>::value>> auto string::make_trie (const Container & container)
Builds a trie from a container.
Template Parameters
Container Container, AssocContainer::value_type convertible to string.
Definition at line 533 of file trie.hpp.
std::string string::regex_escape (const std::string & input) inline
Escapes input to be inserted in a regex.
Definition at line 131 of file string_functions.hpp.
Referenced by handler::Chanhax::Chanhax().
std::vector< std::string > string::regex_split (const std::string & input, const std::regex & pattern, bool skip_empty)
Separate the string into components separated by pattern.
Definition at line 91 of file string_functions.cpp.
Referenced by comma_split(), and regex_split().
std::vector<std::string> string::regex_split (const std::string & input, const std::string & pattern, bool skip_empty = true) inline
Definition at line 180 of file string_functions.hpp.
Referenced by handler::Cointoss::Cointoss(), and xonotic::XonoticConnection::say().
std::string string::replace (const std::string & input, const std::string & from, const std::string & to)
Replace all occurrences of from in text to to.
Definition at line 60 of file string_functions.cpp.
Referenced by simple_wildcard().
std::string string::replace (const std::string & subject, const Properties & map, const std::string & prefix = {})
Replaces the keys of map to the respective values in subject.
Parameters
subject The string to be searched in
map Term/replacement map
prefix (Optional) prefix to prepend to all terms
Todo:
could add a failure function to the trie data for less backtracking
Definition at line 173 of file string_functions.cpp.
Referenced by irc::handler::IrcJoinMessage::on_handle(), irc::handler::IrcKickMessage::on_handle(), irc::handler::IrcKickRejoin::on_handle(), handler::Reply::on_handle(), and xonotic::XonoticConnection::say().
std::string::size_type string::similarity (const std::string & s1, const std::string & s2)
Returns a value representing how similar the two strings are.
Note
This can be done more accurately but it doesn't matter for the purpose of where this function is called so a simple yet inaccurate algorithm is acceptable.
Definition at line 107 of file string_functions.cpp.
bool string::simple_wildcard (const std::string & text, const std::string & pattern)
Checks if text matches the wildcard pattern.
* matches any sequence of characters, all other characters match themselves
Definition at line 83 of file string_functions.cpp.
Referenced by simple_wildcard().
template<class Container , class = std::enable_if_t<!std::is_convertible<Container,std::string>::value>> bool string::simple_wildcard (const Container & input, const std::string & pattern)
Checks if any of the elements in input matches the wildcard pattern.
* matches any sequence of characters, all other characters match themselves
Template Parameters
Container A container of std::string
Definition at line 163 of file string_functions.hpp.
bool string::starts_with (const std::string & haystack, const std::string & prefix) inline
Whether a string starts with the given prefix.
Definition at line 64 of file string_functions.hpp.
Referenced by handler::SimpleAction::can_handle(), xonotic::XonoticConnection::get_property(), xonotic::XonoticConnection::read(), and xonotic::XonoticConnection::set_property().
std::string string::strtolower (std::string string) inline
String to lower case.
Definition at line 94 of file string_functions.hpp.
Referenced by handler::HandlerFactory::build(), handler::Reply::on_handle(), and handler::HandlerFactory::register_handler().
std::string string::strtoupper (std::string string) inline
String to upper case.
Definition at line 103 of file string_functions.hpp.
template<class T > std::string string::to_string (T number, int digits = -1)
Converts a number to string padding with zeros to have at least digits digits.
Definition at line 234 of file string_functions.hpp.
Referenced by timer::format_char().
unsigned long string::to_uint (const std::string & string, unsigned long base = 10, unsigned long default_value = 0)
Converts string to an unsigned integer.
Returns
The corresponding integer or default_value on failure
Definition at line 163 of file string_functions.cpp.
Referenced by irc::FormatterIrc::color_from_string(), JsonParser::parse_json_string(), and network::Server::Server().