MelanoBot: math Namespace Reference
math Namespace Reference
Namespace for math utilities.
Functions
long random ()
Get a uniform random integer.
long random (long max)
Get a uniform random integer between 0 and max (inclusive)
long random (long min, long max)
Get a uniform random integer between min and max (inclusive)
double random_real ()
Get a uniform random number between 0 and 1.
template<class Return = int, class Argument = double>
constexpr Return truncate (Argument x)
Truncates a number.
template<class Return = int, class Argument = double>
constexpr Return round (Argument x)
Round a number (constexpr-friendly)
template<class Argument >
constexpr auto fractional (Argument x)
Get the fractional part of a floating-point number.
template<class Argument , class Arg2 = Argument>
constexpr auto bound (Arg2 min, Argument x, Arg2 max)
Clamp a value inside a range.
Variables
static std::random_device random_device
PRNG device.
Detailed Description
Namespace for math utilities.
Function Documentation
template<class Argument , class Arg2 = Argument> constexpr auto math::bound (Arg2 min, Argument x, Arg2 max)
Clamp a value inside a range.
Template Parameters
Argument Argument type (Must be a floating point type)
Parameters
min Minimum allowed value
x Variable to be bounded
max Maximum allowed value
Definition at line 89 of file math.hpp.
Referenced by color::Color12::hsv().
template<class Argument > constexpr auto math::fractional (Argument x)
Get the fractional part of a floating-point number.
Template Parameters
Argument Argument type (Must be a floating point type)
Definition at line 76 of file math.hpp.
Referenced by color::Color12::hsv().
long math::random ()
Get a uniform random integer.
Definition at line 27 of file math.cpp.
long math::random (long max)
Get a uniform random integer between 0 and max (inclusive)
Definition at line 32 of file math.cpp.
Referenced by xonotic::XonoticConnection::command(), and fun::AnswerQuestions::random_answer().
long math::random (long min, long max)
Get a uniform random integer between min and max (inclusive)
Definition at line 37 of file math.cpp.
Referenced by random().
double math::random_real ()
Get a uniform random number between 0 and 1.
Definition at line 42 of file math.cpp.
Referenced by fun::RainbowBridgeChat::on_handle().
template<class Return = int, class Argument = double> constexpr Return math::round (Argument x)
Round a number (constexpr-friendly)
Template Parameters
Return Return type (Must be an integral type)
Argument Argument type (Must be a floating point type)
Definition at line 66 of file math.hpp.
Referenced by color::Color12::blend(), and color::Color12::hsv().
template<class Return = int, class Argument = double> constexpr Return math::truncate (Argument x)
Truncates a number.
Template Parameters
Return Return type (Must be an integral type)
Argument Argument type (Must be a floating point type)
Definition at line 55 of file math.hpp.
Variable Documentation
std::random_device math::random_device static
PRNG device.
Definition at line 25 of file math.cpp.