MelanoBot: color Namespace Reference
color Namespace Reference
Namespace for color operations.
Classes
class Color12
12 bit color
Variables
Color12 nocolor
Color12 black = Color12(0x0, 0x0, 0x0)
Color12 red = Color12(0xf, 0x0, 0x0)
Color12 green = Color12(0x0, 0xf, 0x0)
Color12 yellow = Color12(0xf, 0xf, 0x0)
Color12 blue = Color12(0x0, 0x0, 0xf)
Color12 magenta = Color12(0xf, 0x0, 0xf)
Color12 cyan = Color12(0x0, 0xf, 0xf)
Color12 white = Color12(0xf, 0xf, 0xf)
Color12 silver = Color12(0xc, 0xc, 0xc)
Color12 gray = Color12(0x8, 0x8, 0x8)
Color12 dark_red = Color12(0x8, 0x0, 0x0)
Color12 dark_green = Color12(0x0, 0x8, 0x0)
Color12 dark_yellow = Color12(0x8, 0x8, 0x0)
Color12 dark_blue = Color12(0x0, 0x0, 0x8)
Color12 dark_magenta = Color12(0x8, 0x0, 0x8)
Color12 dark_cyan = Color12(0x0, 0x8, 0x8)
Detailed Description
Namespace for color operations.
Variable Documentation
Color12 color::black = Color12(0x0, 0x0, 0x0)
Definition at line 26 of file color.cpp.
Referenced by xonotic::Formatter::color_from_match(), irc::FormatterIrc::color_from_string(), color::Color12::from_4bit(), and color::Color12::from_name().
Color12 color::blue = Color12(0x0, 0x0, 0xf)
Definition at line 30 of file color.cpp.
Referenced by xonotic::Formatter::color_from_match(), irc::FormatterIrc::color_from_string(), color::Color12::from_4bit(), and color::Color12::from_name().
Color12 color::cyan = Color12(0x0, 0xf, 0xf)
Definition at line 32 of file color.cpp.
Referenced by xonotic::Formatter::color_from_match(), irc::FormatterIrc::color_from_string(), color::Color12::from_4bit(), color::Color12::from_name(), and xonotic::XonoticConnection::update_user().
Color12 color::dark_blue = Color12(0x0, 0x0, 0x8)
Definition at line 39 of file color.cpp.
Referenced by irc::FormatterIrc::color_from_string(), color::Color12::from_4bit(), color::Color12::from_name(), main(), melanomodule_web(), and handler::Help::on_handle().
Color12 color::dark_cyan = Color12(0x0, 0x8, 0x8)
Definition at line 41 of file color.cpp.
Referenced by irc::FormatterIrc::color_from_string(), color::Color12::from_4bit(), color::Color12::from_name(), melanomodule_xonotic(), and xonotic::XonoticConnection::update_user().
Color12 color::dark_green = Color12(0x0, 0x8, 0x0)
Definition at line 37 of file color.cpp.
Referenced by handler::Bridge::attach_channel(), irc::FormatterIrc::color_from_string(), color::Color12::from_4bit(), color::Color12::from_name(), and main().
Color12 color::dark_magenta = Color12(0x8, 0x0, 0x8)
Definition at line 40 of file color.cpp.
Referenced by irc::FormatterIrc::color_from_string(), color::Color12::from_4bit(), color::Color12::from_name(), and melanomodule_irc().
Color12 color::dark_red = Color12(0x8, 0x0, 0x0)
Definition at line 36 of file color.cpp.
Referenced by irc::FormatterIrc::color_from_string(), color::Color12::from_4bit(), color::Color12::from_name(), and melanomodule_core().
Color12 color::dark_yellow = Color12(0x8, 0x8, 0x0)
Definition at line 38 of file color.cpp.
Referenced by irc::FormatterIrc::color_from_string(), color::Color12::from_4bit(), color::Color12::from_name(), main(), handler::ListInsert::on_handle(), and handler::ListRemove::on_handle().
Color12 color::gray = Color12(0x8, 0x8, 0x8)
Definition at line 35 of file color.cpp.
Referenced by xonotic::Formatter::color_from_match(), irc::FormatterIrc::color_from_string(), color::Color12::from_4bit(), and color::Color12::from_name().
Color12 color::green = Color12(0x0, 0xf, 0x0)
Definition at line 28 of file color.cpp.
Referenced by handler::Bridge::attach(), xonotic::Formatter::color_from_match(), irc::FormatterIrc::color_from_string(), color::Color12::from_4bit(), color::Color12::from_name(), and handler::ListInsert::on_handle().
Color12 color::magenta = Color12(0xf, 0x0, 0xf)
Definition at line 31 of file color.cpp.
Referenced by xonotic::Formatter::color_from_match(), irc::FormatterIrc::color_from_string(), color::Color12::from_4bit(), and color::Color12::from_name().
Color12 color::nocolor
Definition at line 25 of file color.cpp.
Referenced by handler::Bridge::attach(), fun::FormatterRainbow::decode(), string::FormatterAnsi::decode(), color::Color12::from_4bit(), color::Color12::from_name(), xonotic::XonoticConnection::handle_message(), handler::Help::on_handle(), xonotic::XonoticMatchScore::print_scores(), xonotic::XonoticConnection::say(), and xonotic::XonoticConnection::update_user().
Color12 color::red = Color12(0xf, 0x0, 0x0)
Definition at line 27 of file color.cpp.
Referenced by xonotic::Formatter::color_from_match(), irc::FormatterIrc::color_from_string(), ErrorLog::ErrorLog(), color::Color12::from_4bit(), color::Color12::from_name(), handler::Help::on_handle(), and handler::ListRemove::on_handle().
Color12 color::silver = Color12(0xc, 0xc, 0xc)
Definition at line 34 of file color.cpp.
Referenced by xonotic::Formatter::color_from_match(), irc::FormatterIrc::color_from_string(), color::Color12::from_4bit(), and color::Color12::from_name().
Color12 color::white = Color12(0xf, 0xf, 0xf)
Definition at line 33 of file color.cpp.
Referenced by handler::Bridge::attach(), xonotic::Formatter::color_from_match(), irc::FormatterIrc::color_from_string(), color::Color12::from_4bit(), color::Color12::from_name(), and melanomodule_posix().
Color12 color::yellow = Color12(0xf, 0xf, 0x0)
Definition at line 29 of file color.cpp.
Referenced by xonotic::Formatter::color_from_match(), irc::FormatterIrc::color_from_string(), color::Color12::from_4bit(), color::Color12::from_name(), and Logger::log().