MelanoBot: xonotic Namespace Reference
xonotic Namespace Reference
Namespace for Xonotic integration.
Classes
class ConnectionEvents
Show server connect/disconnect messages.
class Formatter
Darkplaces UTF-8.
class ParseEventlog
Base class for handlers parsing the Xonotic eventlog.
class RconCommand
Send a fixed rcon command to a Xonotic connection.
class ShowVoteCall
Shows :vote:vcall.
class ShowVoteDo
Shows :vote:vdo.
class ShowVoteLogin
Shows :vote:vlogin.
class ShowVoteResult
Shows :vote:v(yes|no|timeout)
class ShowVoteStop
Shows :vote:vstop.
class XonoticConnection
Creates a connection to a Xonotic server.
class XonoticJoinPart
Shows player join/part messages.
class XonoticMatchScore
Shows match scores.
class XonoticMatchStart
Shows match start messages.
Functions
std::string hmac_md4 (const std::string &input, const std::string &key)
Compute the MD4 HMAC of the given input with the given key.
std::string quote_string (const std::string &text)
Escapes characters and puts the string in double quotes.
std::string gametype_name (const std::string &short_name)
Returns the human-readable gametyp name from a short name.
void rcon (network::Connection *destination, std::vector< std::string > command, int priority=0)
Sends a rcon command.
Properties message_properties (network::Connection *source)
Returns a list of properties to be used for message formatting.
Properties message_properties (network::Connection *source, const user::User &user)
Variables
static const std::unordered_map< std::string, std::string > gametype_names
Detailed Description
Namespace for Xonotic integration.
Function Documentation
std::string xonotic::gametype_name (const std::string & short_name)
Returns the human-readable gametyp name from a short name.
Definition at line 72 of file xonotic.cpp.
std::string xonotic::hmac_md4 (const std::string & input, const std::string & key)
Compute the MD4 HMAC of the given input with the given key.
Definition at line 32 of file xonotic-connection.cpp.
Referenced by xonotic::XonoticConnection::command(), and xonotic::XonoticConnection::handle_message().
Properties xonotic::message_properties (network::Connection * source) inline
Returns a list of properties to be used for message formatting.
Todo:
replace with "?" or something
same here
Definition at line 31 of file status.hpp.
Referenced by xonotic::XonoticMatchScore::handle_end(), message_properties(), xonotic::XonoticMatchStart::on_handle(), and xonotic::ShowVoteResult::on_handle().
Properties xonotic::message_properties (network::Connection * source, const user::User & user) inline
Definition at line 49 of file status.hpp.
Referenced by xonotic::XonoticJoinPart::on_handle(), xonotic::ShowVoteCall::on_handle(), xonotic::ShowVoteStop::on_handle(), xonotic::ShowVoteLogin::on_handle(), and xonotic::ShowVoteDo::on_handle().
std::string xonotic::quote_string (const std::string & text) inline
Escapes characters and puts the string in double quotes.
Definition at line 28 of file xonotic.hpp.
Referenced by xonotic::XonoticConnection::command().
void xonotic::rcon (network::Connection * destination, std::vector< std::string > command, int priority = 0)
Sends a rcon command.
Parameters
destination Xonotic connection
command Rcon command and arguments
Definition at line 31 of file rcon.hpp.
Referenced by xonotic::RconCommand::on_handle().
Variable Documentation
const std::unordered_map<std::string, std::string> xonotic::gametype_names static
Initial value:
= {
    {"as",  "assault"},
    {"ca",  "clan arena"},
    {"cq",  "conquest"},
    {"ctf", "capture the flag"},
    {"cts", "race cts"},
    {"dom", "domination"},
    {"dm",  "deathmatch"},
    {"ft",  "freezetag"},
    {"inf", "infection"},
    {"inv", "invasion"},
    {"jb",  "jailbreak"},
    {"ka",  "keepaway"},
    {"kh",  "key hunt"},
    {"lms", "last man standing"},
    {"nb",  "nexball"},
    {"ons", "onslaught"},
    {"rc",  "race"},
    {"tdm", "team deathmatch"},
}
Definition at line 52 of file xonotic.cpp.
Referenced by gametype_name().