MelanoBot: network::irc Namespace Reference
network::irc Namespace Reference
Namespace contaning classes and functions handling the IRC protocol.
Classes
class Buffer
IRC buffer.
class IrcConnection
IRC connection.
Functions
bool is_nickchar (char c)
Whether a character is a valid nickname character.
std::string strtolower (std::string string)
Converts a string to lower case.
std::string strtoupper (std::string string)
Converts a string to upper case.
Detailed Description
Namespace contaning classes and functions handling the IRC protocol.
Function Documentation
bool network::irc::is_nickchar (char c) inline
Whether a character is a valid nickname character.
See also
http://tools.ietf.org/html/rfc2812#section-2.3.1
Todo:
currently unused
Definition at line 34 of file irc_functions.hpp.
Referenced by network::irc::IrcConnection::command().
std::string network::irc::strtolower (std::string string) inline
Converts a string to lower case.
See also
http://tools.ietf.org/html/rfc2812#section-2.2
Todo:
locale stuff if it's worth the effort
Definition at line 45 of file irc_functions.hpp.
Referenced by network::irc::IrcConnection::channel_mask(), network::irc::IrcConnection::command(), and network::irc::IrcConnection::handle_message().
std::string network::irc::strtoupper (std::string string) inline
Converts a string to upper case.
See also
http://tools.ietf.org/html/rfc2812#section-2.2
Definition at line 62 of file irc_functions.hpp.
Referenced by handler::CtcpBase::can_handle(), network::irc::IrcConnection::command(), handler::CtcpBase::CtcpBase(), and network::irc::IrcConnection::handle_message().