MelanoBot: timer Namespace Reference
timer Namespace Reference
Namespace for time utilities.
Classes
class basic_timer
A timer which performs a task after some time on a separate thread.
class DateTime
A class representing a date and time.
Typedefs
using Timer = basic_timer< std::chrono::system_clock >
Timer using the wall clock.
using days = std::chrono::duration< int64_t, std::ratio<(24 *3600)>>
Enumerations
enum Month : uint8_t {
Month::JANUARY = 1, Month::FEBRUARY = 2, Month::MARCH = 3, Month::APRIL = 4,
Month::MAY = 5, Month::JUNE = 6, Month::JULY = 7, Month::AUGUST = 8,
Month::SEPTEMBER = 9, Month::OCTOBER =10, Month::NOVEMBER =11, Month::DECEMBER =12
}
Month enum.
enum WeekDay : uint8_t {
WeekDay::MONDAY = 1, WeekDay::TUESDAY = 2, WeekDay::WEDNESDAY = 3, WeekDay::THURSDAY = 4,
WeekDay::FRIDAY = 5, WeekDay::SATURDAY = 6, WeekDay::SUNDAY = 7
}
Week day enum.
Functions
std::string month_name (Month month)
Full month name in English.
std::string month_shortname (Month month)
Short month name in English.
Optional< Month > month_from_name (const std::string &name)
Month from English name.
std::string weekday_name (WeekDay day)
Full weekday name in English.
std::string weekday_shortname (WeekDay day)
Short weekday name in English.
Optional< WeekDay > weekday_from_name (const std::string &name)
Weekday from English name.
std::string format_char (const DateTime &date_time, char c)
Returns a string from a time format character.
std::string format (const DateTime &date_time, const std::string &fmt)
Format a string from DateTime with the given format.
std::string format (const std::string &fmt)
Equivalent to format(DateTime(),fmt)
constexpr Month operator- (Month m, int i) noexcept
constexpr Month operator+ (Month m, int i) noexcept
SUPER_CONSTEXPR Month & operator+= (Month &m, int i) noexcept
SUPER_CONSTEXPR Month & operator-= (Month &m, int i) noexcept
SUPER_CONSTEXPR Month & operator++ (Month &m) noexcept
SUPER_CONSTEXPR Month operator++ (Month &m, int) noexcept
SUPER_CONSTEXPR Month & operator-- (Month &m) noexcept
SUPER_CONSTEXPR Month operator-- (Month &m, int) noexcept
constexpr WeekDay operator- (WeekDay m, int i) noexcept
constexpr WeekDay operator+ (WeekDay m, int i) noexcept
SUPER_CONSTEXPR WeekDay & operator+= (WeekDay &m, int i) noexcept
SUPER_CONSTEXPR WeekDay & operator-= (WeekDay &m, int i) noexcept
SUPER_CONSTEXPR WeekDay & operator++ (WeekDay &m) noexcept
SUPER_CONSTEXPR WeekDay operator++ (WeekDay &m, int) noexcept
SUPER_CONSTEXPR WeekDay & operator-- (WeekDay &m) noexcept
SUPER_CONSTEXPR WeekDay operator-- (WeekDay &m, int) noexcept
std::chrono::system_clock::time_point parse_time (const std::string &text)
Parses the text description of a time point.
std::chrono::system_clock::duration parse_duration (const std::string &text)
Parses the text description of a duration.
Variables
static std::vector< std::string > month_names
static std::vector< std::string > month_shortnames
static std::vector< std::string > weekday_names
static std::vector< std::string > weekday_shortnames
Detailed Description
Namespace for time utilities.
Note
It would have been called time if it weren't for the fact that the C library defines time() as a function and doesn't have namespaces.
Typedef Documentation
using timer::days = typedef std::chrono::duration<int64_t, std::ratio<(24*3600)>>
Definition at line 177 of file time.hpp.
using timer::Timer = typedef basic_timer<std::chrono::system_clock>
Timer using the wall clock.
Definition at line 171 of file time.hpp.
Enumeration Type Documentation
enum timer::Month : uint8_t strong
Month enum.
Enumerator
JANUARY
FEBRUARY
MARCH
APRIL
MAY
JUNE
JULY
AUGUST
SEPTEMBER
OCTOBER
NOVEMBER
DECEMBER
Definition at line 182 of file time.hpp.
enum timer::WeekDay : uint8_t strong
Week day enum.
Enumerator
MONDAY
TUESDAY
WEDNESDAY
THURSDAY
FRIDAY
SATURDAY
SUNDAY
Definition at line 246 of file time.hpp.
Function Documentation
std::string timer::format (const DateTime & date_time, const std::string & fmt)
Format a string from DateTime with the given format.
The character \ escapes characters so they won't be expanded
See also
http://php.net/manual/en/function.date.php
Definition at line 231 of file time_string.cpp.
Referenced by format(), and format_char().
std::string timer::format (const std::string & fmt) inline
Equivalent to format(DateTime(),fmt)
Definition at line 71 of file time_string.hpp.
Referenced by Logger::log(), and irc::handler::CtcpTime::on_handle().
std::string timer::format_char (const DateTime & date_time, char c)
Returns a string from a time format character.
See also
http://php.net/manual/en/function.date.php
Todo:
a varsion with the same format as POSIX date command
Todo:
week number
Todo:
week number
Todo:
get only last 4 digits? Handle BC?
Todo:
Swatch Internet time
Todo:
Timezone(?)
Todo:
timezone P
Todo:
timezone O
Todo:
week number
Todo:
week number
Todo:
get only last 4 digits? Handle BC?
Todo:
Swatch Internet time
Todo:
Timezone(?)
Todo:
timezone P
Todo:
timezone O
Definition at line 144 of file time_string.cpp.
Referenced by format().
Optional< Month > timer::month_from_name (const std::string & name)
Month from English name.
Definition at line 96 of file time_string.cpp.
std::string timer::month_name (Month month)
Full month name in English.
Definition at line 81 of file time_string.cpp.
Referenced by format_char().
std::string timer::month_shortname (Month month)
Short month name in English.
Definition at line 87 of file time_string.cpp.
Referenced by format_char().
constexpr Month timer::operator+ (Month m, int i) inline noexcept
Definition at line 198 of file time.hpp.
Referenced by operator+=(), and operator-().
constexpr WeekDay timer::operator+ (WeekDay m, int i) inline noexcept
Definition at line 257 of file time.hpp.
Referenced by operator+=(), and operator-().
SUPER_CONSTEXPR Month& timer::operator++ (Month & m) inline noexcept
Definition at line 219 of file time.hpp.
Referenced by operator++().
SUPER_CONSTEXPR Month timer::operator++ (Month & m, int) inline noexcept
Definition at line 224 of file time.hpp.
Referenced by timer::DateTime::operator+=(), and timer::DateTime::year_day().
SUPER_CONSTEXPR WeekDay& timer::operator++ (WeekDay & m) inline noexcept
Definition at line 278 of file time.hpp.
Referenced by operator++().
SUPER_CONSTEXPR WeekDay timer::operator++ (WeekDay & m, int) inline noexcept
Definition at line 283 of file time.hpp.
SUPER_CONSTEXPR Month& timer::operator+= (Month & m, int i) inline noexcept
Definition at line 203 of file time.hpp.
Referenced by operator++().
SUPER_CONSTEXPR WeekDay& timer::operator+= (WeekDay & m, int i) inline noexcept
Definition at line 262 of file time.hpp.
Referenced by operator++().
constexpr Month timer::operator- (Month m, int i) inline noexcept
Definition at line 208 of file time.hpp.
Referenced by operator+(), operator-(), and operator-=().
constexpr WeekDay timer::operator- (WeekDay m, int i) inline noexcept
Definition at line 267 of file time.hpp.
Referenced by operator+(), operator-(), and operator-=().
SUPER_CONSTEXPR Month& timer::operator-- (Month & m) inline noexcept
Definition at line 231 of file time.hpp.
Referenced by operator--().
SUPER_CONSTEXPR Month timer::operator-- (Month & m, int) inline noexcept
Definition at line 236 of file time.hpp.
Referenced by timer::DateTime::operator-=().
SUPER_CONSTEXPR WeekDay& timer::operator-- (WeekDay & m) inline noexcept
Definition at line 290 of file time.hpp.
Referenced by operator--().
SUPER_CONSTEXPR WeekDay timer::operator-- (WeekDay & m, int) inline noexcept
Definition at line 295 of file time.hpp.
SUPER_CONSTEXPR Month& timer::operator-= (Month & m, int i) inline noexcept
Definition at line 213 of file time.hpp.
Referenced by operator--().
SUPER_CONSTEXPR WeekDay& timer::operator-= (WeekDay & m, int i) inline noexcept
Definition at line 272 of file time.hpp.
Referenced by operator--().
std::chrono::system_clock::duration timer::parse_duration (const std::string & text)
Parses the text description of a duration.
std::chrono::system_clock::time_point timer::parse_time (const std::string & text)
Parses the text description of a time point.
Optional< WeekDay > timer::weekday_from_name (const std::string & name)
Weekday from English name.
Definition at line 129 of file time_string.cpp.
std::string timer::weekday_name (WeekDay day)
Full weekday name in English.
Definition at line 111 of file time_string.cpp.
Referenced by format_char().
std::string timer::weekday_shortname (WeekDay day)
Short weekday name in English.
Definition at line 120 of file time_string.cpp.
Referenced by format_char().
Variable Documentation
std::vector<std::string> timer::month_names static
Initial value:
=
{
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
}
Definition at line 26 of file time_string.cpp.
Referenced by month_from_name(), and month_name().
std::vector<std::string> timer::month_shortnames static
Initial value:
=
{
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "June",
    "July",
    "Aug",
    "Sept",
    "Oct",
    "Nov",
    "Dec",
}
Definition at line 42 of file time_string.cpp.
Referenced by month_from_name(), and month_shortname().
std::vector<std::string> timer::weekday_names static
Initial value:
=
{
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
}
Definition at line 58 of file time_string.cpp.
Referenced by weekday_from_name(), and weekday_name().
std::vector<std::string> timer::weekday_shortnames static
Initial value:
=
{
    "Mon",
    "Tue",
    "Wed",
    "Thu",
    "Fri",
    "Sat",
    "Sun"
}
Definition at line 69 of file time_string.cpp.
Referenced by weekday_from_name(), and weekday_shortname().