MelanoBot: src/settings.cpp File Reference
settings.cpp File Reference
#include "settings.hpp"
#include <cstdlib>
#include <boost/filesystem.hpp>
#include <boost/program_options.hpp>
#include <boost/property_tree/info_parser.hpp>
#include <boost/property_tree/ini_parser.hpp>
#include <boost/property_tree/xml_parser.hpp>
#include "string/logger.hpp"
#include "string/json.hpp"
#include "config.hpp"
Functions
static std::string find_config (const std::string &dir, settings::FileFormat format)
static std::ostream & recursive_print (std::ostream &stream, const boost::property_tree::ptree &tree, int depth=0)
Recustively prints a ptree.
std::ostream & operator<< (std::ostream &stream, const Settings &settings)
Variables
static std::unordered_map< std::string, settings::FileFormat > format_extension
Detailed Description
Author
Mattia Basaglia
Copyright
Copyright 2015 Mattia Basaglia
License
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file settings.cpp.
Function Documentation
static std::string find_config (const std::string & dir, settings::FileFormat format) static
Definition at line 173 of file settings.cpp.
Referenced by settings::find_config().
std::ostream& operator<< (std::ostream & stream, const Settings & settings)
Definition at line 238 of file settings.cpp.
static std::ostream& recursive_print (std::ostream & stream, const boost::property_tree::ptree & tree, int depth = 0) static
Recustively prints a ptree.
Definition at line 225 of file settings.cpp.
Referenced by operator<<(), and recursive_print().
Variable Documentation
std::unordered_map<std::string,settings::FileFormat> format_extension static
Initial value:
= {
    {".json",settings::FileFormat::JSON},
    {".info",settings::FileFormat::INFO},
    {".xml",settings::FileFormat::XML},
    {".ini",settings::FileFormat::INI},
}
Definition at line 33 of file settings.cpp.
Referenced by find_config(), and settings::load().