MelanoBot: timer::TimeParser::Token Struct Reference
timer::TimeParser::Token Struct Reference
Parsed token.
Public Types
enum Type {
INVALID, NUMBER, IDENTIFIER, TIME,
OPERATOR, NOW, REL_DAY, DATE,
MONTH, WEEK_DAY, AMPM
}
Token type.
Public Member Functions
Token ()
Token (Type type, std::string lexeme)
template<class T >
Token (Type type, std::string lexeme, T &&val)
Public Attributes
Type type {INVALID}
Token type.
std::string lexeme
Corresponding string.
boost::any value
Associated value.
Detailed Description
Parsed token.
Definition at line 120 of file time_parser.hpp.
Member Enumeration Documentation
enum timer::TimeParser::Token::Type
Token type.
Enumerator
INVALID
EOF or similar void.
NUMBER
A number [0-9]+ uint32_t.
IDENTIFIER
An identifier [a-z]+ void.
TIME
A time string 12:30[:00[.0]] Duration.
OPERATOR
An operator [+-] void.
NOW
Now now void.
REL_DAY
Relative day yesterday... int (day offset)
DATE
An ISO date 1234-02-27 DateTime.
MONTH
Month name January... Month.
WEEK_DAY
Week day name Saturday... WeekDay.
AMPM
am/pm am|pm bool (pm)
Definition at line 125 of file time_parser.hpp.
Constructor & Destructor Documentation
timer::TimeParser::Token::Token () inline
Definition at line 142 of file time_parser.hpp.
Referenced by timer::TimeParser::lex(), and timer::TimeParser::lex_date().
timer::TimeParser::Token::Token (Type type, std::string lexeme) inline
Definition at line 143 of file time_parser.hpp.
Referenced by timer::TimeParser::lex(), and timer::TimeParser::lex_identifier().
template<class T > timer::TimeParser::Token::Token (Type type, std::string lexeme, T && val) inline
Definition at line 146 of file time_parser.hpp.
Referenced by timer::TimeParser::lex(), timer::TimeParser::lex_date(), timer::TimeParser::lex_identifier(), timer::TimeParser::lex_number(), and timer::TimeParser::lex_time().
Member Data Documentation
std::string timer::TimeParser::Token::lexeme
Corresponding string.
Definition at line 139 of file time_parser.hpp.
Referenced by timer::TimeParser::parse_date_time(), timer::TimeParser::parse_duration(), timer::TimeParser::parse_time_point(), and Token().
Type timer::TimeParser::Token::type {INVALID}
Token type.
Definition at line 138 of file time_parser.hpp.
Referenced by timer::TimeParser::parse_atomic_duration(), timer::TimeParser::parse_date_desc(), timer::TimeParser::parse_date_time(), timer::TimeParser::parse_day(), timer::TimeParser::parse_duration(), timer::TimeParser::parse_month_day(), timer::TimeParser::parse_time(), timer::TimeParser::parse_time_point(), and Token().
boost::any timer::TimeParser::Token::value
Associated value.
Definition at line 140 of file time_parser.hpp.
Referenced by Token(), and timer::TimeParser::token_val().
The documentation for this struct was generated from the following file:
src/time/time_parser.hpp