MelanoBot: JsonParser Struct Reference
JsonParser Struct Reference
Class that populates a property tree from a JSON in a stream.
#include <json.hpp>
Classes
struct Context
Context information.
Public Member Functions
const Settings & parse (std::istream &stream, const std::string &stream_name="")
Parse the stream.
const Settings & parse_file (const std::string &file_name)
Parse the given file.
const Settings & parse_string (const std::string &json, const std::string &stream_name="")
Parse the string.
const Settings & tree () const
This can be used to get partial trees on errors.
bool error () const
Whether there has been a parsing error.
bool throws () const
Whether the parser can throw.
void throws (bool throws)
Sets whether the parser can throw.
Private Member Functions
void error (const std::string &message)
Throws an exception pointing to the current line.
void parse_json_root ()
Parses the entire file.
void parse_json_object ()
Parse a JSON object.
void parse_json_properties ()
Parse object properties.
void parse_json_array ()
Parse a JSON array.
void parse_json_array_elements ()
Parse array elements.
void parse_json_value ()
Parse a value (number, string, array, object, or other literal)
void parse_json_literal ()
Parse numeric, string and boolean literals.
std::string parse_json_string ()
Parse a string literal.
std::string parse_json_identifier ()
Parses an identifier.
double parse_json_number ()
Parse a numeric literal.
char get_skipws ()
Get the next non-space character in the stream.
bool escapeable (char c)
Whether c can be espaced on a string literal.
char escape (char c)
Escape code for \ c.
template<class T >
void put (const T &val)
Put a value in the tree.
std::string context_pos () const
Position in the tree as defined by the current context.
void context_push (const std::string &name)
Push a named context.
void context_push_array ()
Push an array context.
void context_pop ()
Pop a context.
Private Attributes
std::istream stream {nullptr}
Input stream.
std::string stream_name
Name of the file.
int line = 0
Line number.
Settings ptree
Output tree.
std::stack< Context > context
Context stack.
bool nothrow = false
If true, don't throw.
bool error_flag = false
If true, there has been an error.
Detailed Description
Class that populates a property tree from a JSON in a stream.
Unlike from boost::property_tree::json_parser::read_json it reads arrays element with their numeric index, is a bit forgiving about syntax errors and allows simple unquoted strings
Definition at line 49 of file json.hpp.
Member Function Documentation
void JsonParser::context_pop () inline private
Pop a context.
Definition at line 503 of file json.hpp.
Referenced by parse_json_array(), and parse_json_properties().
std::string JsonParser::context_pos () const inline private
Position in the tree as defined by the current context.
Definition at line 462 of file json.hpp.
Referenced by context_push(), context_push_array(), parse_json_array(), parse_json_object(), and put().
void JsonParser::context_push (const std::string & name) inline private
Push a named context.
Definition at line 480 of file json.hpp.
Referenced by parse_json_properties().
void JsonParser::context_push_array () inline private
Push an array context.
Definition at line 492 of file json.hpp.
Referenced by parse_json_array().
bool JsonParser::error () const inline
Whether there has been a parsing error.
Definition at line 110 of file json.hpp.
Referenced by handler::SimpleJson::http_success().
void JsonParser::error (const std::string & message) inline private
Throws an exception pointing to the current line.
Definition at line 135 of file json.hpp.
Referenced by parse(), parse_file(), parse_json_array(), parse_json_array_elements(), parse_json_literal(), parse_json_number(), parse_json_object(), and parse_json_properties().
char JsonParser::escape (char c) inline private
Escape code for \ c.
Definition at line 437 of file json.hpp.
Referenced by parse_json_string().
bool JsonParser::escapeable (char c) inline private
Whether c can be espaced on a string literal.
Definition at line 423 of file json.hpp.
Referenced by parse_json_string().
char JsonParser::get_skipws () inline private
Get the next non-space character in the stream.
Todo:
possibly skip comments
Definition at line 406 of file json.hpp.
Referenced by parse_json_array(), parse_json_array_elements(), parse_json_identifier(), parse_json_literal(), parse_json_object(), parse_json_properties(), parse_json_string(), and parse_json_value().
const Settings& JsonParser::parse (std::istream & stream, const std::string & stream_name = "") inline
Parse the stream.
Parameters
stream Input stream
stream_name Used for error reporting
Exceptions
JsonError On bad syntax
Returns
The property tree populated from the stream
Definition at line 58 of file json.hpp.
Referenced by parse_string().
const Settings& JsonParser::parse_file (const std::string & file_name) inline
Parse the given file.
Exceptions
JsonError On bad syntax
Returns
The property tree populated from the stream
Definition at line 74 of file json.hpp.
Referenced by Settings::Settings().
void JsonParser::parse_json_array () inline private
Parse a JSON array.
Definition at line 226 of file json.hpp.
Referenced by parse_json_value().
void JsonParser::parse_json_array_elements () inline private
Parse array elements.
Definition at line 243 of file json.hpp.
Referenced by parse_json_array().
std::string JsonParser::parse_json_identifier () inline private
Parses an identifier.
Definition at line 368 of file json.hpp.
Referenced by parse_json_literal(), and parse_json_properties().
void JsonParser::parse_json_literal () inline private
Parse numeric, string and boolean literals.
Definition at line 287 of file json.hpp.
Referenced by parse_json_value().
double JsonParser::parse_json_number () inline private
Parse a numeric literal.
Definition at line 390 of file json.hpp.
Referenced by parse_json_literal().
void JsonParser::parse_json_object () inline private
Parse a JSON object.
Definition at line 169 of file json.hpp.
Referenced by parse_json_root(), and parse_json_value().
void JsonParser::parse_json_properties () inline private
Parse object properties.
Definition at line 184 of file json.hpp.
Referenced by parse_json_object().
void JsonParser::parse_json_root () inline private
Parses the entire file.
Definition at line 143 of file json.hpp.
Referenced by parse(), and parse_file().
std::string JsonParser::parse_json_string () inline private
Parse a string literal.
Definition at line 320 of file json.hpp.
Referenced by parse_json_literal(), and parse_json_properties().
void JsonParser::parse_json_value () inline private
Parse a value (number, string, array, object, or other literal)
Definition at line 271 of file json.hpp.
Referenced by parse_json_array_elements(), and parse_json_properties().
const Settings& JsonParser::parse_string (const std::string & json, const std::string & stream_name = "") inline
Parse the string.
Exceptions
JsonError On bad syntax
Returns
The property tree populated from the stream
Definition at line 93 of file json.hpp.
Referenced by handler::SimpleJson::http_success().
template<class T > void JsonParser::put (const T & val) inline private
Put a value in the tree.
Definition at line 454 of file json.hpp.
Referenced by parse_json_literal().
bool JsonParser::throws () const inline
Whether the parser can throw.
Definition at line 118 of file json.hpp.
void JsonParser::throws (bool throws) inline
Sets whether the parser can throw.
Definition at line 126 of file json.hpp.
Referenced by handler::SimpleJson::http_success().
const Settings& JsonParser::tree () const inline
This can be used to get partial trees on errors.
Definition at line 102 of file json.hpp.
Member Data Documentation
std::stack<Context> JsonParser::context private
Context stack.
Definition at line 522 of file json.hpp.
Referenced by context_pop(), context_pos(), context_push(), context_push_array(), parse(), parse_file(), parse_json_array(), parse_json_array_elements(), parse_json_object(), and parse_json_root().
bool JsonParser::error_flag = false private
If true, there has been an error.
Definition at line 524 of file json.hpp.
Referenced by error(), and parse_json_root().
int JsonParser::line = 0 private
Line number.
Definition at line 520 of file json.hpp.
Referenced by error(), get_skipws(), parse(), parse_file(), and parse_json_string().
bool JsonParser::nothrow = false private
If true, don't throw.
Definition at line 523 of file json.hpp.
Referenced by parse_json_root(), and throws().
Settings JsonParser::ptree private
Output tree.
Definition at line 521 of file json.hpp.
Referenced by parse(), parse_file(), parse_json_array(), parse_json_object(), parse_json_root(), put(), and tree().
std::istream JsonParser::stream {nullptr} private
Input stream.
Definition at line 518 of file json.hpp.
Referenced by get_skipws(), parse(), parse_file(), parse_json_array_elements(), parse_json_identifier(), parse_json_literal(), parse_json_number(), parse_json_properties(), parse_json_string(), and parse_json_value().
std::string JsonParser::stream_name private
Name of the file.
Definition at line 519 of file json.hpp.
Referenced by error(), parse(), and parse_file().
The documentation for this struct was generated from the following file:
src/string/json.hpp