MelanoBot: network::Server Struct Reference
network::Server Struct Reference
Identifies a network server.
#include <network.hpp>
Public Member Functions
Server (std::string host, uint16_t port)
Creates an object from explicit values.
Server (const std::string &server)
Creates object from host:port string.
Server ()
Creates an invalid server.
Server (const Server &)=default
Server (Server &&) noexcept=default
Server & operator= (const Server &)=default
Server & operator= (Server &&) noexcept(std::is_nothrow_move_assignable< std::string >::value)=default
std::string name () const
Name as host:port.
Public Attributes
std::string host
uint16_t port
Detailed Description
Identifies a network server.
Definition at line 32 of file network.hpp.
Constructor & Destructor Documentation
network::Server::Server (std::string host, uint16_t port) inline
Creates an object from explicit values.
Definition at line 40 of file network.hpp.
Referenced by network::UdpIo::local_endpoint(), network::UdpIo::remote_endpoint(), and StdinConnection::server().
network::Server::Server (const std::string & server) inline explicit
Creates object from host:port string.
Definition at line 45 of file network.hpp.
Referenced by xonotic::XonoticConnection::create().
network::Server::Server () inline
Creates an invalid server.
Definition at line 57 of file network.hpp.
Referenced by network::UdpIo::local_endpoint(), and network::UdpIo::remote_endpoint().
network::Server::Server (const Server &) default
Referenced by xonotic::XonoticConnection::XonoticConnection().
network::Server::Server (Server &&) default noexcept
Member Function Documentation
std::string network::Server::name () const inline
Name as host:port.
Definition at line 67 of file network.hpp.
Referenced by xonotic::XonoticConnection::description(), xonotic::XonoticConnection::get_user(), xonotic::XonoticConnection::handle_message(), xonotic::ConnectionEvents::on_handle(), and xonotic::XonoticConnection::update_connection().
Server& network::Server::operator= (const Server &) default
Server& network::Server::operator= (Server &&) default noexcept
Member Data Documentation
std::string network::Server::host
Definition at line 34 of file network.hpp.
Referenced by network::UdpIo::connect(), xonotic::XonoticConnection::create(), name(), and Server().
uint16_t network::Server::port
Definition at line 35 of file network.hpp.
Referenced by network::UdpIo::connect(), xonotic::XonoticConnection::create(), name(), and Server().
The documentation for this struct was generated from the following file:
src/network/network.hpp