MelanoBot: Melanomodule Struct Reference
Melanomodule Struct Reference
Module descriptor.
#include <melanomodule.hpp>
Public Member Functions
template<class ConnectionT >
void register_connection (const std::string &name)
Registers a Connection class to ConnectionFactory.
void register_log_type (const std::string &name, color::Color12 color)
Registers a log type.
template<class FormatterT , class... Args>
void register_formatter (Args &&...args)
Registers a formatter.
template<class ServiceT >
void register_service (const std::string &name)
Registers a service to ServiceRegistry.
template<class HandlerT >
void register_handler (const std::string &name)
Registers a Handler to the HandlerFactory.
Public Attributes
std::string name
std::string description
Detailed Description
Module descriptor.
This class is used to add a module description and to register module-specific classes to their factory.
Definition at line 35 of file melanomodule.hpp.
Member Function Documentation
template<class ConnectionT > void Melanomodule::register_connection (const std::string & name) inline
Registers a Connection class to ConnectionFactory.
Parameters
name Connection protocol name
Definition at line 45 of file melanomodule.hpp.
Referenced by melanomodule_posix(), and melanomodule_xonotic().
template<class FormatterT , class... Args> void Melanomodule::register_formatter (Args &&... args) inline
Registers a formatter.
Template Parameters
FormatterT Formatter class
Args Constructor parameters
Definition at line 69 of file melanomodule.hpp.
Referenced by melanomodule_xonotic().
template<class HandlerT > void Melanomodule::register_handler (const std::string & name) inline
Registers a Handler to the HandlerFactory.
Template Parameters
HandlerT Handler to be registered
Parameters
name Name to be used in the configuration
Definition at line 100 of file melanomodule.hpp.
Referenced by melanomodule_core(), melanomodule_fun(), melanomodule_web(), and melanomodule_xonotic().
void Melanomodule::register_log_type (const std::string & name, color::Color12 color) inline
Registers a log type.
Parameters
name Log type name
color Color used for the log type
Definition at line 58 of file melanomodule.hpp.
Referenced by melanomodule_core(), melanomodule_irc(), melanomodule_posix(), melanomodule_web(), and melanomodule_xonotic().
template<class ServiceT > void Melanomodule::register_service (const std::string & name) inline
Registers a service to ServiceRegistry.
Template Parameters
ServiceT Name of the service class (must be a singleton)
Parameters
name Service identifier
Definition at line 84 of file melanomodule.hpp.
Referenced by melanomodule_web().
Member Data Documentation
std::string Melanomodule::description
Definition at line 38 of file melanomodule.hpp.
std::string Melanomodule::name
Definition at line 37 of file melanomodule.hpp.
The documentation for this struct was generated from the following file:
src/melanomodule.hpp