MelanoBot: network::Command Struct Reference
network::Command Struct Reference
A command to send to a connection.
#include <connection.hpp>
Public Member Functions
Command (std::string command={}, std::vector< std::string > parameters={}, int priority=0, Time timeout=Time::max())
Command (std::string command, std::vector< std::string > parameters, int priority, const Duration &duration)
Command (const Command &)=default
Command (Command &&) noexcept=default
Command & operator= (const Command &)=default
Command & operator= (Command &&) noexcept(std::is_nothrow_move_assignable< std::string >::value)=default
bool operator< (const Command &other) const
Public Attributes
std::string command
Command name.
std::vector< std::string > parameters
Optional parameters.
int priority
Priority, higher = handled sooner.
Time timein
Time of creation.
Time timeout
Time it becomes obsolete.
Detailed Description
A command to send to a connection.
Definition at line 39 of file connection.hpp.
Constructor & Destructor Documentation
network::Command::Command (std::string command = {}, std::vector< std::string > parameters = {}, int priority = 0, Time timeout = Time::max()) inline
Definition at line 47 of file connection.hpp.
Referenced by xonotic::XonoticConnection::cleanup_connection(), irc::LoginInfo::irc_command(), irc::handler::AdminNick::on_handle(), irc::handler::IrcKickRejoin::on_handle(), irc::handler::AdminJoin::on_handle(), irc::handler::QSendWhois::on_handle(), irc::handler::AdminPart::on_handle(), irc::handler::AcceptInvite::on_handle(), irc::handler::WhoisCheckMe::on_handle(), handler::Command::on_handle(), xonotic::rcon(), irc::handler::CtcpBase::reply_to(), xonotic::XonoticConnection::request_status(), xonotic::XonoticConnection::say(), and xonotic::XonoticConnection::update_connection().
network::Command::Command (std::string command, std::vector< std::string > parameters, int priority, const Duration & duration) inline
Definition at line 58 of file connection.hpp.
network::Command::Command (const Command &) default
network::Command::Command (Command &&) default noexcept
Member Function Documentation
bool network::Command::operator< (const Command & other) const inline
Definition at line 74 of file connection.hpp.
Command& network::Command::operator= (const Command &) default
Command& network::Command::operator= (Command &&) default noexcept
Member Data Documentation
std::string network::Command::command
Command name.
Definition at line 41 of file connection.hpp.
Referenced by Command(), xonotic::XonoticConnection::command(), and irc::handler::AdminRaw::on_handle().
std::vector<std::string> network::Command::parameters
Optional parameters.
Definition at line 42 of file connection.hpp.
Referenced by Command(), xonotic::XonoticConnection::command(), and irc::handler::AdminRaw::on_handle().
int network::Command::priority
Priority, higher = handled sooner.
Definition at line 43 of file connection.hpp.
Referenced by Command(), and operator<().
Time network::Command::timein
Time of creation.
Definition at line 44 of file connection.hpp.
Referenced by Command(), and operator<().
Time network::Command::timeout
Time it becomes obsolete.
Definition at line 45 of file connection.hpp.
Referenced by Command().
The documentation for this struct was generated from the following file:
src/network/connection.hpp